### ISSUE TITLE
Cannot reuse tox environment when setup.py has extra requirements in pyproject.toml

### ISSUE THREAD

**Issue by jwodder** [tox-dev/tox#1054]
Ubuntu Xenial 16.04.5  
Python 3.5.2  
tox 3.5.2 (no plugins)

If a project has a `pyproject.toml` file that declares packages besides `setuptools` and `wheel` that are required in order for `setup.py` to run, then reusing a tox virtualenv — i.e., running `tox` without `-r` when a virtualenv in `.tox` has already been created — will fail with:

```
ERROR:   py35: InvocationError for command '/home/jwodder/tmp/tox-bug/.tox/py35/bin/python /home/jwodder/tmp/tox-bug/setup.py --name' (exited with code 1)
```

That is, tox is trying to run `setup.py` within the test virtualenv even though the use of `pyproject.toml` should imply that this should only be done in an environment in which the packages listed in `pyproject.toml` are installed.

A minimal project that exhibits this bug can be found at <https://gist.github.com/jwodder/273715f59786d5125178381d2bb836ac>; run `tox` on the project twice, and the second run will fail.  Running `tox` with the `-r` option succeeds.  This happens both with & without `isolated_build` set to `True`.

**Comment by jwodder** [comment]
Running with `isolated_build = True`:

```
$ tox -vv
using tox.ini: /home/jwodder/tmp/tox-bug/tox.ini
using tox-3.5.2 from /home/jwodder/.local/lib/python3.5/site-packages/tox/__init__.py
skipping sdist step
py35 start: getenv /home/jwodder/tmp/tox-bug/.tox/py35
py35 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py35/.tox-config1
py35 create: /home/jwodder/tmp/tox-bug/.tox/py35
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug/.tox$ /usr/bin/python3 -m virtualenv --python /usr/bin/python3 py35 >/home/jwodder/tmp/tox-bug/.tox/py35/log/py35-0.log
py35 finish: getenv after 3.88 seconds
py35 start: developpkg /home/jwodder/tmp/tox-bug
py35 develop-inst: /home/jwodder/tmp/tox-bug
write config to /home/jwodder/tmp/tox-bug/.tox/py35/.tox-config1 as '3ca82c498bdce94a835bdb0dfd3c644f /usr/bin/python3\n3.5.2 0 1 0'
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/py35/bin/python -m pip install --exists-action w -e /home/jwodder/tmp/tox-bug 
Obtaining file:///home/jwodder/tmp/tox-bug
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Installing collected packages: tox-bug
  Found existing installation: tox-bug 0.1.0
    Not uninstalling tox-bug at /home/jwodder/tmp/tox-bug, outside environment /home/jwodder/tmp/tox-bug/.tox/py35
    Can't uninstall 'tox-bug'. No files were found to uninstall.
  Running setup.py develop for tox-bug
Successfully installed tox-bug
py35 finish: developpkg after 3.03 seconds
py35 start: envreport 
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/py35/bin/python -m pip freeze >/home/jwodder/tmp/tox-bug/.tox/py35/log/py35-1.log
py35 finish: envreport after 0.46 seconds
py35 installed: -e git+git@gist.github.com:273715f59786d5125178381d2bb836ac.git@9d14407308b5d8186bfb2aed929c45dcbb33242e#egg=tox_bug
py35 start: run-test-pre 
py35 run-test-pre: PYTHONHASHSEED='70761181'
py35 finish: run-test-pre after 0.00 seconds
py35 start: runtests 
py35 finish: runtests after 0.00 seconds
py35 start: run-test-post 
py35 finish: run-test-post after 0.00 seconds
py36 start: getenv /home/jwodder/tmp/tox-bug/.tox/py36
py36 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py36/.tox-config1
py36 create: /home/jwodder/tmp/tox-bug/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py36 finish: getenv after 0.00 seconds
py37 start: getenv /home/jwodder/tmp/tox-bug/.tox/py37
py37 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py37/.tox-config1
py37 create: /home/jwodder/tmp/tox-bug/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py37 finish: getenv after 0.00 seconds
___________________________________ summary ____________________________________
  py35: commands succeeded
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
  congratulations :)
$ tox -vv
  removing /home/jwodder/tmp/tox-bug/.tox/log
using tox.ini: /home/jwodder/tmp/tox-bug/tox.ini
using tox-3.5.2 from /home/jwodder/.local/lib/python3.5/site-packages/tox/__init__.py
skipping sdist step
py35 start: getenv /home/jwodder/tmp/tox-bug/.tox/py35
py35 reusing: /home/jwodder/tmp/tox-bug/.tox/py35
py35 finish: getenv after 0.09 seconds
py35 start: developpkg /home/jwodder/tmp/tox-bug
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/py35/bin/python /home/jwodder/tmp/tox-bug/setup.py --name 
py35 finish: developpkg after 0.03 seconds
py35 start: envreport 
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/py35/bin/python -m pip freeze >/home/jwodder/tmp/tox-bug/.tox/py35/log/py35-2.log
py35 finish: envreport after 0.43 seconds
py35 installed: -e git+git@gist.github.com:273715f59786d5125178381d2bb836ac.git@9d14407308b5d8186bfb2aed929c45dcbb33242e#egg=tox_bug
py36 start: getenv /home/jwodder/tmp/tox-bug/.tox/py36
py36 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py36/.tox-config1
py36 create: /home/jwodder/tmp/tox-bug/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py36 finish: getenv after 0.00 seconds
py37 start: getenv /home/jwodder/tmp/tox-bug/.tox/py37
py37 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py37/.tox-config1
py37 create: /home/jwodder/tmp/tox-bug/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py37 finish: getenv after 0.00 seconds
___________________________________ summary ____________________________________
ERROR:   py35: InvocationError for command '/home/jwodder/tmp/tox-bug/.tox/py35/bin/python /home/jwodder/tmp/tox-bug/setup.py --name' (exited with code 1)
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
```

**Comment by gaborbernat** [comment]
Looking in the logs seems at no point is virtualenv creation triggered, sure you run with isolated build there? If so we should see traces of the .package virtual environment creation.

**Comment by gaborbernat** [comment]
What's more is that skipping sdist step, so no packaging is active here.

**Comment by gaborbernat** [comment]
Oh I see what's going on, you have developer mode on. In this case tox does no virtualenv creation, as developer mode is not supported by pep 517/518. This falls into pip isolation support, so if things fail the bug will be in upstream pip.

**Comment by jwodder** [comment]
If I comment out `usedevelop = True`, tox fails with a completely different error that I can't make sense of:

```
$ tox -vv
using tox.ini: /home/jwodder/tmp/tox-bug/tox.ini
using tox-3.5.2 from /home/jwodder/.local/lib/python3.5/site-packages/tox/__init__.py
.package start: getenv /home/jwodder/tmp/tox-bug/.tox/.package
.package cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/.package/.tox-config1
.package create: /home/jwodder/tmp/tox-bug/.tox/.package
setting PATH=/home/jwodder/tmp/tox-bug/.tox/.package/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug/.tox$ /usr/bin/python3 -m virtualenv --python /usr/bin/python3 .package >/home/jwodder/tmp/tox-bug/.tox/.package/log/.package-0.log
.package installdeps: read_version ~= 0.1.0, setuptools >= 34.4.0, wheel
setting PATH=/home/jwodder/tmp/tox-bug/.tox/.package/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/.package/bin/python -m pip install 'read_version ~= 0.1.0' 'setuptools >= 34.4.0' wheel 
Collecting read_version~=0.1.0
  Using cached https://files.pythonhosted.org/packages/ca/cf/fed9a9316d7e94c7a706329ac67faff5924b192b644bda014d4d81368969/read_version-0.1.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=34.4.0 in ./.tox/.package/lib/python3.5/site-packages (40.4.3)
Requirement already satisfied: wheel in ./.tox/.package/lib/python3.5/site-packages (0.32.1)
Installing collected packages: read-version
Successfully installed read-version-0.1.0
.package finish: getenv after 4.40 seconds
.package start: finishvenv 
write config to /home/jwodder/tmp/tox-bug/.tox/.package/.tox-config1 as '3ca82c498bdce94a835bdb0dfd3c644f /usr/bin/python3\n3.5.2 0 0 0\n00000000000000000000000000000000 read_version ~= 0.1.0\n00000000000000000000000000000000 setuptools >= 34.4.0\n00000000000000000000000000000000 wheel'
.package finish: finishvenv after 0.01 seconds
.package start: get-build-requires /home/jwodder/tmp/tox-bug/.tox/.package
setting PATH=/home/jwodder/tmp/tox-bug/.tox/.package/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/.package/bin/python -c 'import setuptools.build_meta
import json

backend = setuptools.build_meta
for_build_requires = backend.get_requires_for_build_sdist(None)
print(json.dumps(for_build_requires))' >/home/jwodder/tmp/tox-bug/.tox/.package/log/.package-1.log
.package finish: get-build-requires after 0.35 seconds
.package start: perform-isolated-build /home/jwodder/tmp/tox-bug/.tox/.package
setting PATH=/home/jwodder/tmp/tox-bug/.tox/.package/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/.package/bin/python -c '
import sys
import setuptools.build_meta
basename = setuptools.build_meta.build_sdist('"'"'/home/jwodder/tmp/tox-bug/.tox/dist'"'"', { "--global-option": ["--formats=gztar"]})
print(basename)' >/home/jwodder/tmp/tox-bug/.tox/.package/log/.package-2.log
actionid: .package
msg: perform-isolated-build
cmdargs: '/home/jwodder/tmp/tox-bug/.tox/.package/bin/python -c \'\nimport sys\nimport setuptools.build_meta\nbasename = setuptools.build_meta.build_sdist(\'"\'"\'/home/jwodder/tmp/tox-bug/.tox/dist\'"\'"\', { "--global-option": ["--formats=gztar"]})\nprint(basename)\''

running sdist
running egg_info
writing top-level names to tox_bug.egg-info/top_level.txt
writing dependency_links to tox_bug.egg-info/dependency_links.txt
writing tox_bug.egg-info/PKG-INFO
reading manifest file 'tox_bug.egg-info/SOURCES.txt'
writing manifest file 'tox_bug.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating tox-bug-0.1.0
creating tox-bug-0.1.0/tox_bug.egg-info
copying files to tox-bug-0.1.0...
copying tox_bug.py -> tox-bug-0.1.0
copying tox_bug.egg-info/PKG-INFO -> tox-bug-0.1.0/tox_bug.egg-info
copying tox_bug.egg-info/SOURCES.txt -> tox-bug-0.1.0/tox_bug.egg-info
copying tox_bug.egg-info/dependency_links.txt -> tox-bug-0.1.0/tox_bug.egg-info
copying tox_bug.egg-info/top_level.txt -> tox-bug-0.1.0/tox_bug.egg-info
Writing tox-bug-0.1.0/setup.cfg
Creating tar archive
removing 'tox-bug-0.1.0' (and everything under it)
tox-bug-0.1.0.tar.gz

.package finish: perform-isolated-build after 0.34 seconds
copying new sdistfile to '/home/jwodder/.tox/distshare/tox-bug-0.1.0.tar.gz'
package .tmp/package/1/tox-bug-0.1.0.tar.gz links to dist/tox-bug-0.1.0.tar.gz (/home/jwodder/tmp/tox-bug/.tox)
py35 start: getenv /home/jwodder/tmp/tox-bug/.tox/py35
py35 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py35/.tox-config1
py35 create: /home/jwodder/tmp/tox-bug/.tox/py35
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug/.tox$ /usr/bin/python3 -m virtualenv --python /usr/bin/python3 py35 >/home/jwodder/tmp/tox-bug/.tox/py35/log/py35-0.log
py35 finish: getenv after 3.62 seconds
py35 start: installpkg /home/jwodder/tmp/tox-bug/.tox/.tmp/package/1/tox-bug-0.1.0.tar.gz
py35 inst: /home/jwodder/tmp/tox-bug/.tox/.tmp/package/1/tox-bug-0.1.0.tar.gz
write config to /home/jwodder/tmp/tox-bug/.tox/py35/.tox-config1 as '3ca82c498bdce94a835bdb0dfd3c644f /usr/bin/python3\n3.5.2 0 0 0'
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/py35/bin/python -m pip install --exists-action w /home/jwodder/tmp/tox-bug/.tox/.tmp/package/1/tox-bug-0.1.0.tar.gz 
Processing ./.tox/.tmp/package/1/tox-bug-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jwodder/tmp/tox-bug/.tox/py35/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-snzqlerb/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-snzqlerb/
py35 finish: installpkg after 0.77 seconds
py35 start: envreport 
setting PATH=/home/jwodder/tmp/tox-bug/.tox/py35/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jwodder/bin:/home/jwodder/.local/bin:/opt/jwodder/bin
  /home/jwodder/tmp/tox-bug$ /home/jwodder/tmp/tox-bug/.tox/py35/bin/python -m pip freeze >/home/jwodder/tmp/tox-bug/.tox/py35/log/py35-1.log
py35 finish: envreport after 0.42 seconds
py35 installed: tox-bug==0.1.0
py36 start: getenv /home/jwodder/tmp/tox-bug/.tox/py36
py36 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py36/.tox-config1
py36 create: /home/jwodder/tmp/tox-bug/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py36 finish: getenv after 0.00 seconds
py37 start: getenv /home/jwodder/tmp/tox-bug/.tox/py37
py37 cannot reuse: no previous config /home/jwodder/tmp/tox-bug/.tox/py37/.tox-config1
py37 create: /home/jwodder/tmp/tox-bug/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py37 finish: getenv after 0.00 seconds
___________________________________ summary ____________________________________
ERROR:   py35: InvocationError for command '/home/jwodder/tmp/tox-bug/.tox/py35/bin/python -m pip install --exists-action w /home/jwodder/tmp/tox-bug/.tox/.tmp/package/1/tox-bug-0.1.0.tar.gz' (exited with code 1)
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
cleanup /home/jwodder/tmp/tox-bug/.tox/.tmp/package/1/tox-bug-0.1.0.tar.gz
```

**Comment by jwodder** [comment]
On further inspection, it seems that `setup.py` is missing from `.tox/dist/tox-bug-0.1.0.tar.gz`, but it's present if I create the sdist with `python3 setup.py sdist`.

**Comment by gaborbernat** [comment]
You ran into https://github.com/pypa/setuptools/issues/1506

**Comment by gaborbernat** [comment]
@jwodder as a workaround add setup.py to Manifest.in, until setuptools fixes the bug.
