### ISSUE TITLE
better error message when the packaging basepython cannot be found

### ISSUE THREAD

**Issue by tjanez** [tox-dev/tox#1063]
I encountered this when setting up a new Python package named [django-priority-batch](https://github.com/genialis/django-priority-batch).

The [`tox.ini` file from the `master` branch where `isolate_build` is not specified](https://github.com/genialis/django-priority-batch/blob/b24de968e524d21e683850d260966ce9478d1d71/tox.ini).
The [corresponding build jobs work on Travis CI](https://travis-ci.org/genialis/django-priority-batch/builds/443151445).

If I [add `isolated_build = True` to the `tox.ini`](https://github.com/genialis/django-priority-batch/blob/0584e228fa4d05a9259a7ca23839a885bcdcf14a/tox.ini#L9), then the [`py36` Tox environment Travis job](https://travis-ci.org/genialis/django-priority-batch/jobs/443175126) fails with:

```
.package create: /home/travis/build/genialis/django-priority-batch/.tox/.package
SKIPPED: InterpreterNotFound: python3.7
ERROR: invocation failed (errno 2), args: /home/travis/build/genialis/django-priority-batch/.tox/.package/bin/python -c 'import setuptools.build_meta
import json
backend = setuptools.build_meta
for_build_requires = backend.get_requires_for_build_sdist(None)
print(json.dumps(for_build_requires))', cwd: /home/travis/build/genialis/django-priority-batch
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/session.py", line 42, in cmdline
    main(args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/session.py", line 49, in main
    retcode = build_session(config).runcommand()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/session.py", line 446, in runcommand
    return self.subcommand_test()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/session.py", line 566, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/package.py", line 23, in tox_package
    session.package, session.dist = get_package(session)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/package.py", line 43, in get_package
    package = acquire_package(config, report, session)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/package.py", line 97, in acquire_package
    path = build_package(config, report, session)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/package.py", line 126, in build_package
    return build_isolated(config, report, session)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/package.py", line 186, in build_isolated
    build_requires = get_build_requires(build_info, package_venv, session)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/package.py", line 292, in get_build_requires
    cwd=session.config.setupdir,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/venv.py", line 532, in _pcall
    args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret, returnout=returnout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/session.py", line 170, in popen
    popen = self._popen(args, cwd, env=env, stdout=stdout, stderr=subprocess.STDOUT)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox/session.py", line 267, in _popen
    env=env,
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/genialis/django-priority-batch/.tox/.package/bin/python': '/home/travis/build/genialis/django-priority-batch/.tox/.package/bin/python'
```
I guess the problem is that Tox somehow tries to use Python 3.7 for isolated package building but it doesn't find it since this is a `py36` Tox environment and  hence fails.

**Comment by gaborbernat** [comment]
It's because:

```
basepython =
    py36: python3.6
    # Ensure all other environments use the latest supported Python version.
    !py36: python3.7
```
So all envs other than py36 will use ``python3.7``, the ``.package`` included. You can just set it to ``python`` if you want to use instead whatever is the default.

```
```
[testenv:.package]
basepython = python
```	
```

We probably should throw a better error in such cases.

**Comment by tjanez** [comment]
> So all envs other than py36 will use `python3.7`, the `.package` included. You can just set it to `python`, if you want to use instead whatever is the default.

@gaborbernat, thanks for explaining this. I somehow missed the fact that isolated builds are also _special_ Tox environments that my settings apply to.

**Comment by gaborbernat** [comment]
I think we fixed this now.
