### ISSUE TITLE
failed to create jython environment

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#1073]
While trying to add jython test to virtualenv bumped into the fact that we cannot create an environment with jython :cry: 

```

Traceback (most recent call last):
  File "/home/bernat/.local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/session.py", line 41, in cmdline
    main(args)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/session.py", line 46, in main
    config = prepare(args)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/session.py", line 28, in prepare
    config = parseconfig(args)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 232, in parseconfig
    ParseIni(config, config_file, content)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1060, in __init__
    config.envconfigs[name] = self.make_envconfig(name, section, reader._subs, config)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1125, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1331, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1531, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1564, in processcommand
    new_word = reader._replace(word)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1378, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1414, in do_replace
    expanded = substitute_once(value)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1412, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1459, in _replace_match
    return self._replace_substitution(match)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 1496, in _replace_substitution
    val = val()
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 897, in get_envsitepackagesdir
    x = self.config.interpreters.get_sitepackagesdir(info=self.python_info, envdir=self.envdir)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/config.py", line 903, in python_info
    return self.config.interpreters.get_info(envconfig=self)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/interpreters.py", line 39, in get_info
    info = run_and_get_interpreter_info(name, executable)
  File "/home/bernat/.local/lib/python3.7/site-packages/tox/interpreters.py", line 69, in run_and_get_interpreter_info
    return InterpreterInfo(name, executable, **result)

```

**Comment by gaborbernat** [comment]
Fixed in master.
