### ISSUE TITLE
Cannot specify deps from requirements file with isolated build

### ISSUE THREAD

**Issue by lkollar** [tox-dev/tox#1085]
When using `isolated_build = true` with an external requirements file in the `deps` section tox fails at the `get-build-requires` stage with an exception.

The problem seems to be that tox is trying to parse the file names as a package dependency.

Relevant exception trace:

```
  Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/local/lib/python3.7/site-packages/tox/session.py", line 41, in cmdline
    main(args)
  File "/usr/local/lib/python3.7/site-packages/tox/session.py", line 48, in main
    retcode = build_session(config).runcommand()
  File "/usr/local/lib/python3.7/site-packages/tox/session.py", line 449, in runcommand
    return self.subcommand_test()
  File "/usr/local/lib/python3.7/site-packages/tox/session.py", line 553, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/tox/package.py", line 20, in tox_package
    session.package = get_package(session)
  File "/usr/local/lib/python3.7/site-packages/tox/package.py", line 38, in get_package
    path = build_package(config, report, session)
  File "/usr/local/lib/python3.7/site-packages/tox/package.py", line 58, in build_package
    return build_isolated(config, report, session)
  File "/usr/local/lib/python3.7/site-packages/tox/package.py", line 118, in build_isolated
    base_build_deps = {pkg_resources.Requirement(r.name).key for r in package_venv.envconfig.deps}
  File "/usr/local/lib/python3.7/site-packages/tox/package.py", line 118, in <setcomp>
    base_build_deps = {pkg_resources.Requirement(r.name).key for r in package_venv.envconfig.deps}
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2954, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-rrequir'"
```
OS: MacOS 10.13.6 and RHEL 6.8

Reproducer `tox.ini`:

```
[tox]
envlist = py37
isolated_build = true

[testenv]
deps = -rrequirements.txt
```

**Comment by gaborbernat** [comment]
You're doing something wrong here. https://www.python.org/dev/peps/pep-0517/ does not allow specifying build dependencies via the requirements.txt file. Specify all dependencies explicitly via ``PEP-440``.

As for bypassing the ``testenv`` inheritance append:

```ini
[testenv:.package]
 # no additional dependencies besides PEP 517
deps =
```
