### ISSUE TITLE
testsuite fails with Python 2.7 in test_parallel, test_parallel_live, and test_parallel_error_report

### ISSUE THREAD

**Issue by mcepl** [tox-dev/tox#1188]
Thanks for submitting an issue!

If submitting a BUG please provide:

- [x] Minimal reproducible example or detailed description, assign "bug"
- [x] OS and `pip list` output

When running:
```bash
export LANG=en_US.UTF-8
LANG=en_US.UTF-8
export PYTHONDONTWRITEBYTECODE=1
PYTHONDONTWRITEBYTECODE=1
export PATH=/home/abuild/rpmbuild/BUILDROOT/python-tox-3.7.0-0.x86_64/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin
PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-tox-3.7.0-0.x86_64/usr/lib/python2.7/site-packages
py.test-2.7 -v -k 'not network'
```
I get three abovementioned tests failing.
```
[   50s] =================================== FAILURES ===================================
[   50s] ________________________________ test_parallel _________________________________
[   50s] 
[   50s] cmd = <function run at 0x7f00e4867578>
[   50s] initproj = <function initproj_ at 0x7f00e4867320>
[   50s] 
[   50s]     def test_parallel(cmd, initproj):
[   50s]         initproj(
[   50s]             "pkg123-0.7",
[   50s]             filedefs={
[   50s]                 "tox.ini": """
[   50s]                 [tox]
[   50s]                 envlist = a, b
[   50s]                 isolated_build = true
[   50s]                 [testenv]
[   50s]                 commands=python -c "import sys; print(sys.executable)"
[   50s]                 [testenv:b]
[   50s]                 depends = a
[   50s]             """,
[   50s]                 "pyproject.toml": """
[   50s]                 [build-system]
[   50s]                 requires = ["setuptools >= 35.0.2"]
[   50s]                 build-backend = 'setuptools.build_meta'
[   50s]                             """,
[   50s]             },
[   50s]         )
[   50s]         result = cmd("--parallel", "all")
[   50s] >       assert result.ret == 0, "{}{}{}".format(result.err, os.linesep, result.out)
[   50s] E       AssertionError: 
[   50s] E         .package create: /tmp/pytest-of-abuild/pytest-19/test_parallel0/pkg123/.tox/.package
[   50s] E         .package installdeps: setuptools >= 35.0.2
[   50s] E         WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
[   50s] E         \r\x1b[K\r\u280b [0] \r\x1b[K\u2716 FAIL a in 0.018 second
[   50s] E         
[KFailed a under process 21265, stdout:
[   50s] E         
[   50s] E         stderr:
[   50s] E         /usr/bin/python2: No module named tox
[   50s] E         \r\x1b[K\u2716 FAIL b in 0.018 second
[   50s] E         Failed b under process 21267, stdout:
[   50s] E         
[   50s] E         stderr:
[   50s] E         /usr/bin/python2: No module named tox
[   50s] E         ___________________________________ summary ____________________________________
[   50s] E         ERROR:   a: parallel child exit code 1
[   50s] E         ERROR:   b: parallel child exit code 1
[   50s] E         
[   50s] E       assert 1 == 0
[   50s] E        +  where 1 = <[UnicodeEncodeError("'ascii' codec can't encode character u'\u280b' in position 293: ordinal not in range(128)") raised in repr()] RunResult object at 0x7f00e5383638>.ret
[   50s] 
[   50s] cmd        = <function run at 0x7f00e4867578>
[   50s] initproj   = <function initproj_ at 0x7f00e4867320>
[   50s] result     = <[UnicodeEncodeError("'ascii' codec can't encode character u'\u280b' in position 293: ordinal not in range(128)") raised in repr()] RunResult object at 0x7f00e5383638>
[   50s] 
[   50s] /home/abuild/rpmbuild/BUILD/tox-3.7.0/tests/unit/session/test_parallel.py:27: AssertionError
[   50s] ______________________________ test_parallel_live ______________________________
[   50s] 
[   50s] cmd = <function run at 0x7f00e4867aa0>
[   50s] initproj = <function initproj_ at 0x7f00e53c42a8>
[   50s] 
[   50s]     def test_parallel_live(cmd, initproj):
[   50s]         initproj(
[   50s]             "pkg123-0.7",
[   50s]             filedefs={
[   50s]                 "tox.ini": """
[   50s]                 [tox]
[   50s]                 isolated_build = true
[   50s]                 envlist = a, b
[   50s]                 [testenv]
[   50s]                 commands=python -c "import sys; print(sys.executable)"
[   50s]             """,
[   50s]                 "pyproject.toml": """
[   50s]                 [build-system]
[   50s]                 requires = ["setuptools >= 35.0.2"]
[   50s]                 build-backend = 'setuptools.build_meta'
[   50s]                             """,
[   50s]             },
[   50s]         )
[   50s]         result = cmd("--parallel", "all", "--parallel-live")
[   50s] >       assert result.ret == 0, "{}{}{}".format(result.err, os.linesep, result.out)
[   50s] E       AssertionError: /usr/bin/python2: No module named tox
[   50s] E         /usr/bin/python2: No module named tox
[   50s] E         
[   50s] E         .package create: /tmp/pytest-of-abuild/pytest-19/test_parallel_live0/pkg123/.tox/.package
[   50s] E         .package installdeps: setuptools >= 35.0.2
[   50s] E         WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
[   50s] E         \u2716 FAIL a in 0.022 second
[   50s] E         \u2716 FAIL b in 0.022 second
[   50s] E         ___________________________________ summary ____________________________________
[   50s] E         ERROR:   a: parallel child exit code 1
[   50s] E         ERROR:   b: parallel child exit code 1
[   50s] E         
[   50s] E       assert 1 == 0
[   50s] E        +  where 1 = <[UnicodeEncodeError("'ascii' codec can't encode character u'\u2716' in position 309: ordinal not in range(128)") raised in repr()] RunResult object at 0x7f00e54f7998>.ret
[   50s] 
[   50s] cmd        = <function run at 0x7f00e4867aa0>
[   50s] initproj   = <function initproj_ at 0x7f00e53c42a8>
[   50s] result     = <[UnicodeEncodeError("'ascii' codec can't encode character u'\u2716' in position 309: ordinal not in range(128)") raised in repr()] RunResult object at 0x7f00e54f7998>
[   50s] 
[   50s] /home/abuild/rpmbuild/BUILD/tox-3.7.0/tests/unit/session/test_parallel.py:49: AssertionError
[   50s] __________________________ test_parallel_error_report __________________________
[   50s] 
[   50s] cmd = <function run at 0x7f00e48671b8>
[   50s] initproj = <function initproj_ at 0x7f00e53c45f0>
[   50s] 
[   50s]     def test_parallel_error_report(cmd, initproj):
[   50s]         initproj(
[   50s]             "pkg123-0.7",
[   50s]             filedefs={
[   50s]                 "tox.ini": """
[   50s]                 [tox]
[   50s]                 isolated_build = true
[   50s]                 envlist = a
[   50s]                 [testenv]
[   50s]                 commands=python -c "import sys, os; sys.stderr.write(str(12345) + os.linesep);\
[   50s]                  raise SystemExit(17)"
[   50s]             """,
[   50s]                 "pyproject.toml": """
[   50s]                 [build-system]
[   50s]                 requires = ["setuptools >= 35.0.2"]
[   50s]                 build-backend = 'setuptools.build_meta'
[   50s]                             """,
[   50s]             },
[   50s]         )
[   50s]         result = cmd("-p", "all")
[   50s]         msg = "{}{}{}".format(result.err, os.linesep, result.out)
[   50s]         assert result.ret == 1, msg
[   50s]         # we print output
[   50s] >       assert "(exited with code 17)" in result.out, msg
[   50s] E       AssertionError: 
[   50s] E         .package create: /tmp/pytest-of-abuild/pytest-19/test_parallel_error_report0/pkg123/.tox/.package
[   50s] E         .package installdeps: setuptools >= 35.0.2
[   50s] E         WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
[   50s] E         \r\x1b[K\r\u280b [0] \r\x1b[K\u2716 FAIL a in 0.018 second
[   50s] E         
[KFailed a under process 21384, stdout:
[   50s] E         
[   50s] E         stderr:
[   50s] E         /usr/bin/python2: No module named tox
[   50s] E         ___________________________________ summary ____________________________________
[   50s] E         ERROR:   a: parallel child exit code 1
[   50s] E         
[   50s] E       assert '(exited with code 17)' in '.package create: /tmp/pytest-of-abuild/pytest-19/test_parallel_error_report0/pkg123/.tox/.package\n.package installdep..._________________________________ summary ____________________________________\nERROR:   a: parallel child exit code 1\n'
[   50s] E        +  where '.package create: /tmp/pytest-of-abuild/pytest-19/test_parallel_error_report0/pkg123/.tox/.package\n.package installdep..._________________________________ summary ____________________________________\nERROR:   a: parallel child exit code 1\n' = <[UnicodeEncodeError("'ascii' codec can't encode character u'\u280b' in position 298: ordinal not in range(128)") raised in repr()] RunResult object at 0x7f00e539fe18>.out
[   50s] 
[   50s] cmd        = <function run at 0x7f00e48671b8>
[   50s] initproj   = <function initproj_ at 0x7f00e53c45f0>
[   50s] msg        = '
[   50s] .package create: /tmp/pytest-of-abuild/pytest-19/test_parallel_error_report0/pkg123/.tox/.package
[   50s] .package installde..._________________________________ summary ____________________________________
[   50s] ERROR:   a: parallel child exit code 1
[   50s] '
[   50s] result     = <[UnicodeEncodeError("'ascii' codec can't encode character u'\u280b' in position 298: ordinal not in range(128)") raised in repr()] RunResult object at 0x7f00e539fe18>
[   50s] 
[   50s] /home/abuild/rpmbuild/BUILD/tox-3.7.0/tests/unit/session/test_parallel.py:100: AssertionError
[   50s] =========================== short test summary info ============================
[   50s] FAIL tests/unit/session/test_parallel.py::test_parallel
[   50s] FAIL tests/unit/session/test_parallel.py::test_parallel_live
[   50s] FAIL tests/unit/session/test_parallel.py::test_parallel_error_report
[   50s] SKIP [1] tests/unit/test_interpreters.py:28: non posix test
[   50s] SKIP [1] tests/integration/test_jython_env_create.py:5: needs jython and dev cut of virtualenv
[   50s] ======== 3 failed, 425 passed, 2 skipped, 4 deselected in 44.17 seconds ========
```
This is on openSUSE/Tumbleweed with all necessary dependency and logged information available in 
[log.txt](https://github.com/tox-dev/tox/files/2956969/log.txt).

I don't understand how it is possible that tox cannot find itself, especially when ``PYTHONPATH`` is set to its installation directory.

**Comment by gaborbernat** [comment]
Hi, do you have a docker image to replicate this?

**Comment by gaborbernat** [comment]
The log does not tell me enough sadly 😢 so I would need to debug locally to understand how this is possible for what I need to replicate it locally 🤔

**Comment by gaborbernat** [comment]
@mcepl so if no Docker image maybe a vagrant one? 😄 Ideally setup with your build stuff, so I can play around and try to understand what's the issue.

**Comment by mcepl** [comment]
Get a plain openSUSE/Tumbleweed image and then run:
```sh
$ zypper ref
$ zypper in -y osc
$ mkdir build && cd build
$ osc co devel:languages:python python-tox
$ cd devel\:languages\:python/python-tox
$ osc build
```
Does it work? You can play about the exact call of ``pytest`` in the section starting with the keyword ``%check``.

**Comment by gaborbernat** [comment]
Installing an OS and creating a machine is a kinda hard entry point for myself (yeah time constraints), hence why requesting some pre-build one (e.g. docker/vagrant).

**Comment by mcepl** [comment]
Sure, but I thought you can just use openSUSE/Tumbleweed Docker image and run bash in it, right?

**Comment by gaborbernat** [comment]
This was my first question if you have such one. I see one here https://hub.docker.com/r/opensuse/tumbleweed I think 👍

**Comment by mcepl** [comment]
> This was my first question if you have such one. I see one here https://hub.docker.com/r/opensuse/tumbleweed I think +1

Oh I see. I understood whether I had something prepared complete with the build and testing. Of course, there is the official openSUSE/Tumbleweed image on Docker Hub.

**Comment by gaborbernat** [comment]
@mcepl can you please try again with tox 3.8.0? Thanks!

**Comment by mcepl** [comment]
Hmm:
```
[    3s] + /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
[    3s] Traceback (most recent call last):
[    3s]   File "setup.py", line 18, in <module>
[    3s]     package_dir={"": "src"},
[    3s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
[    3s]     _install_setup_requires(attrs)
[    3s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
[    3s]     dist.parse_config_files(ignore_option_errors=True)
[    3s]   File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
[    3s]     self._parse_config_files(filenames=filenames)
[    3s]   File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 599, in _parse_config_files
[    3s]     (parser.read_file if six.PY3 else parser.readfp)(reader)
[    3s]   File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
[    3s]     self._read(fp, filename)
[    3s]   File "/usr/lib64/python2.7/ConfigParser.py", line 479, in _read
[    3s]     line = fp.readline()
[    3s]   File "/usr/lib64/python2.7/encodings/ascii.py", line 26, in decode
[    3s]     return codecs.ascii_decode(input, self.errors)[0]
[    3s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 345: ordinal not in range(128)
[    3s] error: Bad exit status from /var/tmp/rpm-tmp.Aevlpy (%build)
[    3s] 
[    3s] 
[    3s] RPM build errors:
[    3s]     Bad exit status from /var/tmp/rpm-tmp.Aevlpy (%build)
[    3s] 
[    3s] stitny failed "build python-tox.spec" at Thu Mar 28 14:17:18 UTC 2019.
[    3s]
```
???

**Comment by gaborbernat** [comment]
3.8.1?😁I meant

**Comment by mcepl** [comment]
> 3.8.1?grinI meant

Of course.

**Comment by gaborbernat** [comment]
Hmm what pip version do you have?

**Comment by mcepl** [comment]
```sh
abuild@stitny:~> python2 -mpip --version
pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
````

**Comment by gaborbernat** [comment]
What are you trying to achieve? We don't support the ``setup.py build`` command and expect PEP-518 invocations instead 🤔

**Comment by gaborbernat** [comment]
As per above closing this for now.
