### ISSUE TITLE
[BUG] AttributeError: 'VirtualEnv' object has no attribute 'session'

### ISSUE THREAD

**Issue by uilianries** [tox-dev/tox#1221]
related issue: #1219 

Hi!

I'm running my CI tests as usual, but they have started to fail since some minutes ago:

Tox version: 3.8.1

```
  py37-conan-latest: commands succeeded
  congratulations :)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/session/__init__.py", line 42, in cmdline
    main(args)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/session/__init__.py", line 63, in main
    retcode = session.runcommand()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/session/__init__.py", line 187, in runcommand
    return self.subcommand_test()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/session/__init__.py", line 215, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/session/commands/run/sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/venv.py", line 584, in setupenv
    status = self.update(action=action)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox/venv.py", line 242, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/tox_venv/hooks.py", line 99, in tox_testenv_create
    venv.session.make_emptydir(venv.path)
AttributeError: 'VirtualEnv' object has no attribute 'session'
```
Full log: https://travis-ci.org/conan-io/conan-package-tools/jobs/512519960#L593

My tox.ini:
```
[tox]
skipsdist = True

envlist =
    py{27,37}-conan-{latest,dev}

[testenv]
deps =
    -rcpt/requirements_test.txt
    tabulate
    conan-latest: conan
    conan-dev: https://github.com/conan-io/conan/archive/develop.tar.gz

setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONPATH = {toxinidir}:{env:PYTHONPATH:}
    CONAN_TEST_SUITE=1

commands =
    nosetests --with-coverage --cover-package=cpt --cover-html {posargs:cpt.test}
```

**Comment by gaborbernat** [comment]
this belongs to tox-venv, https://github.com/tox-dev/tox-venv/issues/29, working on a fix

**Comment by uilianries** [comment]
Sorry for opening here! Thanks for your answer :+1:

**Comment by drdavella** [comment]
Just wanted to comment here that there is no need to be sorry about opening this issue. This is in fact a bug in `tox`, but the developers are electing to fix the issues downstream, which is helpful. See https://github.com/tox-dev/tox/issues/1219#issuecomment-477637804 for additional discussion.

**Comment by drdavella** [comment]
It is likely that many other plugins will be affected by this issue as well, so opening the issue here is quite helpful.

**Comment by cjerdonek** [comment]
> It is likely that many other plugins will be affected by this issue as well, so opening the issue here is quite helpful.

The issue I filed for this was filed on tox's tracker before both of yours, but mine was moved to the other repo: https://github.com/tox-dev/tox-venv/issues/29

I also thought it should have been left in its original location for a similar reason (better to create a new issue than move it): https://github.com/tox-dev/tox-venv/issues/29#issuecomment-477559246
