### ISSUE TITLE
[BUG] Isolated build doesn't get proper setuptools dependency

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#1251]
I stopped understanding what's going on. It's similar to what I mentioned yesterday, but here the whole env is up-to-date. It's reproducible only under Travis CI currently: https://travis-ci.com/sanitizers/octomachinery/jobs/190156114

Basically, it seems like the isolated build env is hitting older setuptools during env provisioning. And it's not even system-site-packages in this case. Oh, and I'm not even sure whether it's tox's bug, or pip's.

```ini
[tox]
envlist = python
minversion = 3.8.6
isolated_build = true
```

```toml
[build-system]
requires = [
  "setuptools >= 40.9.0",
  "setuptools_scm >= 1.15.0",
  "setuptools_scm_git_archive >= 1.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
```

```python-traceback
$ tox --notest
.package create: /home/travis/build/sanitizers/octomachinery/.tox/.package
.package installdeps: setuptools >= 40.9.0, setuptools_scm >= 1.15.0, setuptools_scm_git_archive >= 1.0, wheel
build-docs create: /home/travis/build/sanitizers/octomachinery/.tox/build-docs
build-docs inst: /home/travis/build/sanitizers/octomachinery/.tox/.tmp/package/1/octomachinery-0.0.12.dev9+gc51926b.tar.gz
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/sanitizers/octomachinery/.tox/build-docs/log/build-docs-1.log
================================== log start ===================================
Processing ./.tox/.tmp/package/1/octomachinery-0.0.12.dev9+gc51926b.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/python/3.7.1/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-xuvadu25/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-xuvadu25/
=================================== log end ====================================
___________________________________ summary ____________________________________
ERROR:   build-docs: InvocationError for command /home/travis/build/sanitizers/octomachinery/.tox/build-docs/bin/python -m pip install --exists-action w '/home/travis/build/sanitizers/octomachinery/.tox/.tmp/package/1/octomachinery-0.0.12.dev9+gc51926b.tar.gz[docs]' (exited with code 1)
The command "tox --notest" failed and exited with 1 during .
```

**Comment by webknjaz** [comment]
Oh wait,
I've added
```ini
requires =
    setuptools >= 40.9.0
    pip >= 19.0.3
```
and it worked (https://github.com/sanitizers/octomachinery/commit/9a7157fe5d6b9079811dfc3e07ad00ea3613a9b1)

But it's still weird... Should we keep it open?

**Comment by gaborbernat** [comment]
Hehe, that's without isolated build then 👍

**Comment by gaborbernat** [comment]
@webknjaz can you please submit the output of tox -rvve with the failing case 👍

**Comment by webknjaz** [comment]
I'll try

**Comment by webknjaz** [comment]
Triggered it: https://travis-ci.com/sanitizers/octomachinery/jobs/190175604. Expect logs in a few minutes.

**Comment by webknjaz** [comment]
oh, I missed `r`, but it's probably fine since it's travis. and it sets TOXENV correctly anyway.

**Comment by gaborbernat** [comment]
seems a build issue, what's the pip version in pre-commit env? the tox packaging success, seems pip tries to install via python setup.py interface rather than the pep 517 hook. Not a tox issue though for sure.

**Comment by webknjaz** [comment]
@gaborbernat isn't it Pip installed in the virtualenv by tox? I assume adding `pip --version` to `commands` won't work because it fails earlier. Is using `requires` the recommended way of dealing with it now?

**Comment by webknjaz** [comment]
Oh, you were right, It appears that venv was created with `pip==10.0.1`
```
[...]
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
[...]
```

And just setting
```ini
requires =
    pip >= 19.0.3
```
helps
