### ISSUE TITLE
[BUG] Tox failed with OSError: Command /share/CACHEDEV1_DAT...lstack/bin/python2.7 - setuptools pip wheel failed with error code 1

### ISSUE THREAD

**Issue by viraj1899** [tox-dev/tox#1253]
Trying to configure and run kuryr-libnetwork tool on my setup. Where i dont have  yum install , apt-get install doesn't work . The only way is to download package is the source and install it.

pip/curl/wget is working fine.

I am trying to run some test suite name **fullstack** using **tox** but tox is failing with error 
**OSError: Command /share/CACHEDEV1_DAT...lstack/bin/python2.7 - setuptools pip wheel failed with error code 1**

**Environment Details:**
1>Base python as python 2.7 and installed python 3.5
2>tox --version
3.8.4 imported from /usr/local/ceph/lib/python2.7/site-packages/tox/__init__.pyc
tox -e fullstack
3> [/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork] # pip --version
pip 19.0.3 from /usr/local/ceph/lib/python2.7/site-packages/pip (python 2.7)
[/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork] # virtualenv --version
1.11.6
4> Python Dev package(python devtools) already installed 

tox -e fullstack
fullstack create: /share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/.tox/fullstack
ERROR: invocation failed (exit code 1), logfile: /share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/.tox/fullstack/log/fullstack-0.log
============================================================================== log start ===============================================================================
  No LICENSE.txt / LICENSE found in source
New python executable in /share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/.tox/fullstack/bin/python2.7
Also creating executable in /share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/.tox/fullstack/bin/python
Command /share/CACHEDEV1_DAT...lstack/bin/python2.7 -m pip config list had error code 1
Installing setuptools, pip, wheel...

 Complete output from command /share/CACHEDEV1_DAT...lstack/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
ImportError: cannot import name main
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/src/lib/python3.5/site-packages/virtualenv.py", line 2567, in <module>
    main()
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/src/lib/python3.5/site-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/src/lib/python3.5/site-packages/virtualenv.py", line 1088, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/src/lib/python3.5/site-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/src/lib/python3.5/site-packages/virtualenv.py", line 1025, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/src/lib/python3.5/site-packages/virtualenv.py", line 886, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /share/CACHEDEV1_DAT...lstack/bin/python2.7 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /usr/local/bin/python2.7

=============================================================================== log end ================================================================================
ERROR: InvocationError for command /share/CACHEDEV1_DATA/.qpkg/Python3/src/bin/python3.5 -m virtualenv --python /usr/local/bin/python2.7 fullstack (exited with code 1)
_______________________________________________________________________________ summary ________________________________________________________________________________
ERROR:   fullstack: InvocationError for command /share/CACHEDEV1_DATA/.qpkg/Python3/src/bin/python3.5 -m virtualenv --python /usr/local/bin/python2.7 fullstack (exited with code 1)

**Comment by gaborbernat** [comment]
This is a virtualenv bug as I see. Can you provide a list of all installed packages (alongside tox)?

**Comment by viraj1899** [comment]
Hi @gaborbernat i have manually installed  devtools,pathlib,Scrapy,tox  etc . 

Will provide indepth list of packages installed.

Between while running tox -e fullstack, below dependencies are failing. 
List of dependencies are getting installed from 
https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/queens
 
```
[/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/kuryr_libnetwork/tests] # tox -e fullstack
fullstack create: /share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/.tox/fullstack
fullstack installdeps: -r/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/requirements.txt, -r/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/test-requirements.txt
ERROR: invocation failed (exit code 1), logfile: /share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork/.tox/fullstack/log/fullstack-1.log
============================================================================== log start ===============================================================================
Ignoring jsbeautifier: markers 'python_version == "3.4"' don't match your environment
Ignoring hyperframe: markers 'python_version == "3.4"' don't match your environment
Ignoring cssutils: markers 'python_version == "3.4"' don't match your environment
Ignoring kaitaistruct: markers 'python_version == "3.4"' don't match your environment
Ignoring zVMCloudConnector: markers 'python_version == "2.7"' don't match your environment
Ignoring zVMCloudConnector: markers 'python_version == "3.4"' don't match your environment
Ignoring zVMCloudConnector: markers 'python_version == "3.6"' don't match your environment
Ignoring unicodecsv: markers 'python_version == "2.7"' don't match your environment
Ignoring pathlib: markers 'python_version == "2.7"' don't match your environment
Ignoring tornado: markers 'python_version == "3.4"' don't match your environment
Ignoring backports.ssl-match-hostname: markers 'python_version == "2.7"' don't match your environment
Ignoring ruamel.yaml: markers 'python_version == "3.4"' don't match your environment
Ignoring html2text: markers 'python_version == "3.4"' don't match your environment
Ignoring funcsigs: markers 'python_version == "2.7"' don't match your environment
Ignoring dnspython3: markers 'python_version == "3.4"' don't match your environment
Ignoring hpack: markers 'python_version == "3.4"' don't match your environment
Ignoring brotlipy: markers 'python_version == "3.4"' don't match your environment
 
```

**Comment by gaborbernat** [comment]
``virtualenv===15.1.0`` is probably the faulty one, not being compatible with pip you're using (latest?)

**Comment by viraj1899** [comment]
@gaborbernat Yup using the latest pip . Do i need to downgrade virtualenv ? if yes then which version is compatible.
pip --version
pip 19.0.3 from /usr/local/ceph/lib/python2.7/site-packages/pip (python 2.7)

virtualenv --version
1.11.6

**Comment by viraj1899** [comment]
@gaborbernat Even using latest version facing the issue 
[/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork] # virtualenv --version
16.4.3
[/share/CACHEDEV1_DATA/.qpkg/QKuryr/rootfs/opt/kuryr-libnetwork] # pip --version
pip 19.0.3 from /usr/local/ceph/lib/python2.7/site-packages/pip (python 2.7)

**Comment by viraj1899** [comment]
@gaborbernat Still facing the same issue, please find below package installed

Package                       Version
----------------------------- -----------
alabaster                     0.7.12
alembic                       1.0.8
amqp                          2.4.2
aniso8601                     6.0.0
appdirs                       1.4.3
asn1crypto                    0.24.0
AST                           0.0.2
attrs                         19.1.0
Automat                       0.7.0
automaton                     1.16.0
Babel                         2.5.3
backports.functools-lru-cache 1.5
bcrypt                        3.1.6
beautifulsoup4                4.7.1
boto                          2.48.0
cachetools                    3.1.0
castellan                     1.2.2
ceph-detect-init              1.0.1
ceph-disk                     1.0.0
ceph-volume                   1.0.0
cephfs                        2.0.0
certifi                       2018.10.15
cffi                          1.12.2
chardet                       3.0.4
cinder                        9.0.1.dev2
Click                         7.0
cliff                         2.14.1
cmd2                          0.8.9
constantly                    15.1.0
contextlib2                   0.5.5
cpopen                        1.4
cryptography                  2.6.1
Cython                        0.24
debtcollector                 1.21.0
decorator                     4.4.0
dmidecode                     0.8.1
dnspython                     1.16.0
docutils                      0.14
dogpile.cache                 0.7.1
enum-compat                   0.0.2
enum34                        1.1.6
eventlet                      0.24.1
extras                        1.0.0
fasteners                     0.14.1
fixtures                      3.0.0
Flask                         0.12.4
Flask-RESTful                 0.3.6
flask-restful-swagger-2       0.35
funcsigs                      1.0.2
functools32                   3.2.3.post2
futures                       3.2.0
futurist                      1.8.1
gfapi                         1.1
google-api-python-client      1.7.8
google-auth                   1.6.3
google-auth-httplib2          0.0.3
greenlet                      0.4.15
grpcio                        1.15.0
httplib2                      0.12.1
hyperlink                     19.0.0
idna                          2.7
imagesize                     1.1.0
incremental                   17.5.0
ioprocess                     0.15.1
ipaddress                     1.0.22
iso8601                       0.1.12
itsdangerous                  1.1.0
Jinja2                        2.10
jmespath                      0.9.4
jsonpatch                     1.23
jsonpointer                   2.0
jsonschema                    2.6.0
keystoneauth1                 3.13.1
keystonemiddleware            6.0.0
kombu                         4.5.0
kuryr-lib                     0.9.0
libvirt-python                5.1.0
linecache2                    1.0.0
logutils                      0.3.5
lxml                          4.3.3
M2Crypto                      0.25.1
Mako                          1.0.8
MarkupSafe                    1.1.1
monotonic                     1.5
msgpack                       0.6.1
munch                         2.3.2
netaddr                       0.7.18
netifaces                     0.10.9
networkx                      2.2
neutron                       9.4.1
neutron-lib                   1.20.0
nose                          1.3.7
oauth2client                  4.1.3
openstacksdk                  0.27.0
os-brick                      2.8.1
os-client-config              1.32.0
os-service-types              1.6.0
os-traits                     0.11.0
os-win                        4.2.0
osc-lib                       1.12.1
oslo.cache                    1.33.2
oslo.concurrency              3.29.1
oslo.config                   6.8.1
oslo.context                  2.22.1
oslo.db                       4.45.0
oslo.i18n                     3.19.0
oslo.log                      3.42.3
oslo.messaging                6.4.1
oslo.middleware               3.37.1
oslo.policy                   2.1.1
oslo.privsep                  1.32.1
oslo.reports                  1.29.2
oslo.rootwrap                 5.15.2
oslo.serialization            2.28.2
oslo.service                  1.38.0
oslo.upgradecheck             0.2.1
oslo.utils                    3.40.3
oslo.versionedobjects         1.35.1
oslo.vmware                   2.32.2
osprofiler                    2.6.0
ovs                           2.10.0
paramiko                      2.4.2
Paste                         3.0.8
PasteDeploy                   1.5.2
pbr                           3.1.1
pecan                         1.3.3
pexpect                       4.0.1
pip                           19.0.3
prettytable                   0.7.2
psutil                        5.6.1
pthreading                    0.1.4
ptyprocess                    0.5
pyasn1                        0.4.5
pyasn1-modules                0.2.4
pycadf                        2.9.0
pycparser                     2.19
pycrypto                      2.6.1
pycurl                        7.43.0
PyDispatcher                  2.0.5
pydot                         1.4.1
Pygments                      2.3.1
PyHamcrest                    1.9.0
pyinotify                     0.9.6
PyMySQL                       0.9.3
PyNaCl                        1.3.0
pyOpenSSL                     19.0.0
pyparsing                     2.3.1
pyparted                      3.10.7
pyperclip                     1.7.0
pyroute2                      0.5.5
pyrpm                         0.3
pysqlite                      2.8.3
python-barbicanclient         4.8.1
python-cinderclient           4.1.0
python-dateutil               2.8.0
python-designateclient        2.11.0
python-dmidecode              3.12.2
python-editor                 1.0.4
python-glanceclient           2.16.0
python-keystoneclient         3.19.0
python-mimeparse              1.6.0
python-neutronclient          6.12.0
python-novaclient             13.0.0
python-swiftclient            3.7.0
pytz                          2017.3
pyudev                        0.21.0
PyYAML                        3.12
rados                         2.0.0
rbd                           2.0.0
repoze.lru                    0.7
requests                      2.20.1
requestsexceptions            1.4.0
retrying                      1.3.3
rfc3986                       1.2.0
rgw                           2.0.0
Routes                        2.4.1
rpm                           0.0.2
rsa                           4.0
rtslib-fb                     2.1.69
ryu                           4.31
sanlock-python                3.6.0
service-identity              18.1.0
setuptools                    28.6.0
simplejson                    3.16.0
singledispatch                3.4.0.3
six                           1.11.0
snowballstemmer               1.2.1
sortedcontainers              2.1.0
sosreport                     3.2.0a1
soupsieve                     1.9
Sphinx                        1.4.8
SQLAlchemy                    1.0.19
sqlalchemy-migrate            0.12.0
sqlparse                      0.3.0
statsd                        3.3.0
stevedore                     1.30.1
subprocess32                  3.5.3
suds-jurko                    0.6
taskflow                      3.4.0
Tempita                       0.5.2
tenacity                      5.0.3
testresources                 2.0.1
testscenarios                 0.5.0
testtools                     2.3.0
tinyrpc                       1.0.0
tooz                          1.64.2
traceback2                    1.4.0
typing                        3.6.2
unicodecsv                    0.14.1
unittest2                     1.1.0
uritemplate                   3.0.0
urllib3                       1.24.1
vine                          1.3.0
virtualenv                    1.11.6
voluptuous                    0.10.5
waitress                      1.2.1
warlock                       1.3.0
wcwidth                       0.1.7
weakrefmethod                 1.0.3
WebOb                         1.7.4
WebTest                       2.0.33
Werkzeug                      0.15.1
wget                          3.2
wrapt                         1.11.1
yappi                         1.0
zope.interface                4.6.0
[/] #
