### ISSUE TITLE
[BUG] race condition while creating log?

### ISSUE THREAD

**Issue by glyph** [tox-dev/tox#1256]
Saw this once when running `tox -p auto` but could not reproduce on subsequent runs.

```
Traceback (most recent call last):
  File ".../.local/venvs/tox/lib/python3.6/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
FileExistsError: [Errno 17] File exists: '.../Projects/.../.tox/log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.local/venvs/tox/lib/python3.6/site-packages/tox/__main__.py", line 4, in <module>
    tox.cmdline()
  File ".../.local/venvs/tox/lib/python3.6/site-packages/tox/session/__init__.py", line 43, in cmdline
    main(args)
  File ".../.local/venvs/tox/lib/python3.6/site-packages/tox/session/__init__.py", line 65, in main
    ensure_empty_dir(config.logdir)
  File ".../.local/venvs/tox/lib/python3.6/site-packages/tox/util/path.py", line 10, in ensure_empty_dir
    path.ensure(dir=1)
  File ".../.local/venvs/tox/lib/python3.6/site-packages/py/_path/local.py", line 535, in ensure
    return p._ensuredirs()
  File ".../.local/venvs/tox/lib/python3.6/site-packages/py/_path/local.py", line 520, in _ensuredirs
    self.mkdir()
  File ".../.local/venvs/tox/lib/python3.6/site-packages/py/_path/local.py", line 470, in mkdir
    py.error.checked_call(os.mkdir, fspath(p))
  File ".../.local/venvs/tox/lib/python3.6/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))

py.error.EEXIST: [File exists]: mkdir('.../Projects/.../.tox/log',)
```

**Comment by mgedmin** [comment]
I just got this error from `tox -p auto -e coverage,coverage3`.

<details>

```
tox -p auto -e coverage,coverage3 -- -p
⠹ [2] coverage | coverage3Traceback (most recent call last):
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
FileExistsError: [Errno 17] File exists: '/home/mg/src/pyspacewar/.tox/log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/tox/__main__.py", line 4, in <module>
    tox.cmdline()
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/tox/session/__init__.py", line 42, in cmdline
    main(args)
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/tox/session/__init__.py", line 60, in main
    ensure_empty_dir(config.logdir)
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/tox/util/path.py", line 10, in ensure_empty_dir
    path.ensure(dir=1)
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/py/_path/local.py", line 530, in ensure
    return p._ensuredirs()
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/py/_path/local.py", line 515, in _ensuredirs
    self.mkdir()
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/py/_path/local.py", line 465, in mkdir
    py.error.checked_call(os.mkdir, fspath(p))
  File "/home/mg/.local/venvs/tox/lib/python3.6/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EEXIST: [File exists]: mkdir('/home/mg/src/pyspacewar/.tox/log',)
ERROR: invocation failed (exit code 1), logfile: /home/mg/src/pyspacewar/.tox/coverage/log/coverage-222.log
================================================================ log start =================================================================
action: coverage, msg: parallel coverage
cwd: /home/mg/src/pyspacewar
cmd: /home/mg/.local/venvs/tox/bin/python3 /home/mg/.local/venvs/tox/lib/python3.6/site-packages/tox/__main__.py -p auto -e coverage,coverage3 -- -p

================================================================= log end ==================================================================
✖ FAIL coverage in 0.274 second
✔ OK coverage3 in 2.5620000000000003 seconds
_________________________________________________________________ summary __________________________________________________________________
ERROR:   coverage: parallel child exit code 1
  coverage3: commands succeeded
```

</details>

**Comment by mgedmin** [comment]
It seems bad that multiple parallel workers are trying to use the same log directory (.tox/log)?  Or at least they should not be all trying to clean it.

AFAICS config.logdir is used only in Session.newaction(), which in turn is used only in the legacy make_sdist(), which is executed before the parallel workers get created.

This uncovers another bug: the parallel workers wipe out any logs created by the package build action done by the parent `tox` process!

**Comment by mgedmin** [comment]
A quick workaround might be to adjust `run_parallel` to pass a different `--log-dir` to each worker process.

**Comment by gaborbernat** [comment]
This has been fixed by tox 4 :+1: As no longer runs in subprocesses but rather in threads.
