### ISSUE TITLE
tox_get_python_executable result is no longer used to create virtualenvs

### ISSUE THREAD

**Issue by AWhetter** [tox-dev/tox#1300]
Before tox 3.8.0, the value returned by a `tox_get_python_executable` hook was the executable that would be used to create the virtualenv. Since 3.8.0, this executable is used to get some executable information but what creates the virtualenv is what exists in `sys.executable` (https://github.com/tox-dev/tox/blob/666f6cd38c5e587620d2d4e8bc9697056010a014/src/tox/helper/get_version.py#L7).

In our use case we need the wrapper script that we return from the hook to be what creates the virtualenv, and not the underlying Python binary, because direct use of that binary relies on an environment that our wrapper script sets up.

```
using tox.ini: /home/asw/dev/amazepackage/tox.ini (pid 42122)                    
  removing /home/asw/dev/amazepackage/.tox/log                                      
using tox-3.8.0 from /usr/lib/python2.7/site-packages/tox/__init__.pyc (pid 42122)
skipping sdist step                                                                 
secretpy27 start: getenv /home/asw/dev/amazepackage/.tox/secretpy27                 
secretpy27 cannot reuse: -r flag                                                    
secretpy27 create: /home/asw/dev/amazepackage/.tox/secretpy27                       
setting PATH=/home/asw/dev/amazepackage/.tox/secretpy27/bin:/usr/bin                
[42255] /home/asw/dev/amazepackage/.tox$ /usr/bin/python -m virtualenv --always-copy --python /secret_environment/bin/python2.7 secretpy27
Running virtualenv with interpreter /secret_environment/bin/python2.7               
Traceback (most recent call last):                                                  
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 32, in <module>       
    import subprocess                                                               
  File "/secret_environment/lib/python2.7/subprocess.py", line 427, in <module>  
    import select                                                                   
ImportError: /secret_environment/lib/python2.7/lib-dynload/select.so: undefined symbol: _PyInt_AsInt
ERROR: invocation failed (exit code 1)                                              
ERROR: InvocationError for command /usr/bin/python -m virtualenv --always-copy --python /secret_environment/bin/python2.7 secretpy27 (exited with code 1)
secretpy27 finish: getenv /home/asw/dev/amazepackage/.tox/secretpy27 after 0.84 seconds
___________________________________________________________________________________________ summary ___________________________________________________________________________________________ERROR:   secretpy27: InvocationError for command /usr/bin/python -m virtualenv --always-copy --python /secret_environment/bin/python2.7 secretpy27 (exited with code 1)
```

In the above log, tox .3.7.0 would use the return value of `tox_get_python_executable`, instead of `/secret_environment/bin/python2.7`.

**Comment by gaborbernat** [comment]
@AWhetter feel free to put in a PR to fix this 👌
