### ISSUE TITLE
Tox runenvreport failing. Output is None after my commands passed.

### ISSUE THREAD

**Issue by clickthisnick** [tox-dev/tox#1332]
I can't reproduce this reliably unfortunately. 

Using tox to run pylint. Pylint succeeds but tox fails.

The problem stems from output is None in the `tox_runenvreport`:
https://github.com/tox-dev/tox/blob/7237c9d84bc2fe25a324a1488b34f497d86aac0c/src/tox/venv.py#L755

tox.ini
```
[testenv:unittestdeps]
deps =
    requests==2.20.0
    mock==2.0.0
    pytest==3.10.1
    pytest-aiohttp==0.3.0
    pytest-cov==2.6.0
    pytest-mock==1.10.0
    pytest-structlog==0.1

[testenv:pylint]
basepython = python3.6
envdir = {toxinidir}/.tox
passenv = https_proxy http_proxy no_proxy
install_command = pip install --trusted-host company-proxy  --index-url=http://company-proxy/ {opts} {packages}
commands = {basepython} -m pylint --rcfile={toxinidir}/.pylintrc {posargs:{toxinidir}/src {toxinidir}/tests} --output-format=colorized
deps =
    {[testenv:unittestdeps]deps}
    pylint==1.9.4
```

tox output
```
+ tox -q -e pylint
___________________________________ summary ____________________________________
  pylint: commands succeeded
  congratulations :)
Traceback (most recent call last):
  File "/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/lib/python2.7/site-packages/tox/session/__init__.py", line 42, in cmdline
    main(args)
  File "/usr/lib/python2.7/site-packages/tox/session/__init__.py", line 66, in main
    exit_code = session.runcommand()
  File "/usr/lib/python2.7/site-packages/tox/session/__init__.py", line 190, in runcommand
    return self.subcommand_test()
  File "/usr/lib/python2.7/site-packages/tox/session/__init__.py", line 218, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/usr/lib/python2.7/site-packages/tox/session/commands/run/sequential.py", line 20, in run_sequential
    runenvreport(venv, config)
  File "/usr/lib/python2.7/site-packages/tox/session/commands/run/sequential.py", line 60, in runenvreport
    packages = config.pluginmanager.hook.tox_runenvreport(venv=venv, action=action)
  File "/usr/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/site-packages/tox/venv.py", line 745, in tox_runenvreport
    output = output.split("\n\n")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
script returned exit code 1
```

Perhaps its because tox is installed in python2.7 but I'm using basepython 3.6?

I was wondering if it would be ok for me to just change this code:
https://github.com/tox-dev/tox/blob/7237c9d84bc2fe25a324a1488b34f497d86aac0c/src/tox/venv.py#L755

To:
```python
if output:
  # the output contains a mime-header, skip it
  output = output.split("\n\n")[-1]
  packages = output.strip().split("\n")
else:
  packages = 'Tox output was None'
  
return packages  # Return non-None to indicate plugin has completed
```

**Comment by clickthisnick** [comment]
Funny enough if I remove the `-q` from tox command I can never reproduce this error.

**Comment by clickthisnick** [comment]
Seems like removing `envdir = {toxinidir}/.tox` fixed it.

This was running on a CI machine where other tox commands were running as well.
Maybe something went haywire with multiple tox processes running at same time.

Going to close unless can reproduce it later.
