### ISSUE TITLE
python3.7 problem on azure pipelines

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#1337]
https://dev.azure.com/toxdev/tox/_build/results?buildId=1879&view=logs&j=9ae52fd2-8967-5276-eca4-50facaa10db8

sqlite is missing in py3.7 atm. I am tempted to wait this out, if there is a quick fix from microsoft (they have been notified already).

```text
1Starting: run tox test environment
2==============================================================================
3Task         : Command Line
4Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
5Version      : 2.148.0
6Author       : Microsoft Corporation
7Help         : https://go.microsoft.com/fwlink/?LinkID=613735
8==============================================================================
9Generating script.
10Script contents:
11/opt/hostedtoolcache/Python/3.7.3/x64/python -m tox
12========================== Starting Command Output ===========================
13in/bash --noprofile --norc /home/vsts/work/_temp/560cb363-2b35-44f9-87d6-35ddd81f878e.sh
14fix_lint installed: aspy.yaml==1.3.0,cfgv==2.0.0,identify==1.4.3,importlib-metadata==0.17,nodeenv==1.3.3,pre-commit==1.16.1,PyYAML==5.1,six==1.12.0,toml==0.10.0,virtualenv==16.6.0,zipp==0.5.1
15fix_lint run-test-pre: PYTHONHASHSEED='264368492'
16fix_lint run-test: commands[0] | pre-commit run --all-files --show-diff-on-failure
17Traceback (most recent call last):
18  File "/home/vsts/work/1/s/.tox/fix_lint/bin/pre-commit", line 6, in <module>
19    from pre_commit.main import main
20  File "/home/vsts/work/1/s/.tox/fix_lint/lib/python3.7/site-packages/pre_commit/main.py", line 12, in <module>
21    from pre_commit.commands.autoupdate import autoupdate
22  File "/home/vsts/work/1/s/.tox/fix_lint/lib/python3.7/site-packages/pre_commit/commands/autoupdate.py", line 14, in <module>
23    from pre_commit.clientlib import CONFIG_SCHEMA
24  File "/home/vsts/work/1/s/.tox/fix_lint/lib/python3.7/site-packages/pre_commit/clientlib.py", line 14, in <module>
25    from pre_commit.error_handler import FatalError
26  File "/home/vsts/work/1/s/.tox/fix_lint/lib/python3.7/site-packages/pre_commit/error_handler.py", line 13, in <module>
27    from pre_commit.store import Store
28  File "/home/vsts/work/1/s/.tox/fix_lint/lib/python3.7/site-packages/pre_commit/store.py", line 7, in <module>
29    import sqlite3
30  File "/opt/hostedtoolcache/Python/3.7.3/x64/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
31    from sqlite3.dbapi2 import *
32  File "/opt/hostedtoolcache/Python/3.7.3/x64/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
33    from _sqlite3 import *
34ModuleNotFoundError: No module named '_sqlite3'
35ERROR: InvocationError for command /home/vsts/work/1/s/.tox/fix_lint/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 1)
36___________________________________ summary ____________________________________
37ERROR:   fix_lint: commands failed
38##[error]Bash exited with code '1'.
```

**Comment by gaborbernat** [comment]
We already discussed this inside https://github.com/tox-dev/tox/pull/1336#issuecomment-499163215, nothing to do than wait https://github.com/microsoft/azure-pipelines-image-generation/issues/996. The only alternative would be to switch to 3.6, which I would rather not due.

**Comment by obestwalter** [comment]
I tried this as a quick fix, by simply asking for it, but that didn't work, will revert that now.

**Comment by gaborbernat** [comment]
You can amend the CI script within PRs 🤔 no need to push on master and revert, for future reference 👍 .

**Comment by obestwalter** [comment]
Sure - I just didn't have a PR open at that time and master is red. I hoped to be able to fix that with a small change. Doesn't seem to be that easy :(
