### ISSUE TITLE
tox -l: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#1343]
```console
% mkdir /tmp/test
% cd /tmp/test
% touch tox.ini
% tox -l
Traceback (most recent call last):
  File "…/Vcs/otree-core-private/.venv/bin/tox", line 11, in <module>
    load_entry_point('tox', 'console_scripts', 'tox')()
  File "…/Vcs/tox/src/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "…/Vcs/tox/src/tox/session/__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "…/Vcs/tox/src/tox/session/__init__.py", line 187, in runcommand
    self.showenvs(all_envs=False, description=show_description)
  File "…/Vcs/tox/src/tox/session/__init__.py", line 291, in showenvs
    show_envs(self.config, all_envs=all_envs, description=description)
  File "…/Vcs/tox/src/tox/session/commands/show_env.py", line 14, in show_envs
    max_length = max(len(env) for env in (default + extra))
ValueError: max() arg is an empty sequence
```

Fix:
```diff
diff --git i/src/tox/session/commands/show_env.py w/src/tox/session/commands/show_env.py
index ae05c84..a6d16f0 100644
--- i/src/tox/session/commands/show_env.py
+++ w/src/tox/session/commands/show_env.py
@@ -11,6 +11,9 @@ def show_envs(config, all_envs=False, description=False):
 
     if description and default:
         report.line("default environments:")
+    envs = default + extra
+    if not envs:
+        return
     max_length = max(len(env) for env in (default + extra))
 
     def report_env(e):
```

tox 3.12.1, but also on master.

**Comment by pletnes** [comment]
I found the same bug.
