### ISSUE TITLE
Travis/Tox failure w/ Requirement.parse('pluggy<1,>=0.12.0'), {'tox'})

### ISSUE THREAD

**Issue by stephenrauch** [tox-dev/tox#1358]
Seeing a failure on [travis](https://travis-ci.org/stephenrauch/pycel/jobs/552439414).

Was able to work around with:
```
tox < 3.13.0
```

```
$ tox
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pluggy 0.8.0 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pluggy<1,>=0.12.0'), {'tox'})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tox/config/__init__.py", line 254, in parseconfig
    pm = get_plugin_manager(plugins)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tox/config/__init__.py", line 73, in get_plugin_manager
    pm.load_setuptools_entrypoints("tox")
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 273, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'travis' could not be loaded: (pluggy 0.8.0 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pluggy<1,>=0.12.0'), {'tox'})!
The command "tox" exited with 1.

**Comment by gaborbernat** [comment]
Do please pip install tox --force-reinstall -U

**Comment by gaborbernat** [comment]
As the error says tox dependencies are met. if anything it's a pip issue 😃
