### ISSUE TITLE
warn_ungrouped_named_tokens_in_collection warning from pyparsing 2.4.1

### ISSUE THREAD

**Issue by jnrbsn** [tox-dev/tox#1375]
`tox` now causes a `warn_ungrouped_named_tokens_in_collection` warning from the [latest version of pyparsing](https://github.com/pyparsing/pyparsing/blob/master/CHANGES), which appears to have been released yesterday. I get the warning when running _any_ `tox` command.

```
[~] $ mkdir tox_test
[~] $ cd tox_test/
[~/tox_test] $ virtualenv venv
New python executable in /home/jnrbsn/tox_test/venv/bin/python
Installing setuptools, pip, wheel...
done.
[~/tox_test] $ . venv/bin/activate
(venv) [~/tox_test] $ python --version
Python 2.7.16+
(venv) [~/tox_test] $ pip install tox
...
(venv) [~/tox_test] $ tox --version
/home/jnrbsn/tox_test/venv/local/lib/python2.7/site-packages/packaging/requirements.py:57: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
  VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
/home/jnrbsn/tox_test/venv/local/lib/python2.7/site-packages/packaging/requirements.py:60: UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'marker' on And expression collides with '_original_end' on contained expression
  MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
3.13.2 imported from /home/jnrbsn/tox_test/venv/local/lib/python2.7/site-packages/tox/__init__.pyc
(venv) [~/tox_test] $ pip freeze -l | grep pyparsing
pyparsing==2.4.1
(venv) [~/tox_test] $ pip install -U pyparsing==2.4.0
...
(venv) [~/tox_test] $ tox --version
3.13.2 imported from /home/jnrbsn/tox_test/venv/local/lib/python2.7/site-packages/tox/__init__.pyc
```

**Comment by asottile** [comment]
This is a bug in `packaging`, not `tox`:

```
$ .tox/py27/bin/python -Werror -c 'import packaging.requirements'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tox/.tox/py27/local/lib/python2.7/site-packages/packaging/requirements.py", line 57, in <module>
    VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
  File "/tmp/tox/.tox/py27/local/lib/python2.7/site-packages/pyparsing.py", line 2401, in __call__
    return self._setResultsName(name)
  File "/tmp/tox/.tox/py27/local/lib/python2.7/site-packages/pyparsing.py", line 3942, in _setResultsName
    stacklevel=3)
UserWarning: warn_ungrouped_named_tokens_in_collection: setting results name 'specifier' on And expression collides with '_original_end' on contained expression
```

**Comment by asottile** [comment]
https://github.com/pypa/packaging/issues/170 is the upstream issue
