### ISSUE TITLE
Invalid Syntax : def _collate

### ISSUE THREAD

**Issue by VedaAnnayappa** [tox-dev/tox#1414]
I have installed tox by following instruction provided in https://tox.readthedocs.io/en/latest/install.html

post running tox command I am getting systax error
`

root@jupiter-vm975:~/tox# tox -rvv
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 7, in <module>
    from tox import cmdline
  File "/usr/local/lib/python2.7/dist-packages/tox/__init__.py", line 9, in <module>
    import pluggy
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/local/lib/python2.7/dist-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/local/lib/python2.7/dist-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

`

**Comment by asottile** [comment]
`more-itertools` has dropped support for python2.x -- you'll need to downgrade to a version which still supports python2

If you use a newer version of `pip` when installing `tox` it should avoid installing the incompatible version of `more-itertools`

**Comment by gaborbernat** [comment]
Sigh, does more itertools have the good metadata to mark it python 3 only?

**Comment by asottile** [comment]
yep! https://github.com/erikrose/more-itertools/blob/0d97c55616fb9563be69fdeeda13bf4038834b7c/setup.py#L32

**Comment by asottile** [comment]
(and they've had `python_requires` since their 6.x release which dropped support)
