### ISSUE TITLE
tox 3.14.0 uses more_itertools which is only Python 3. 

### ISSUE THREAD

**Issue by kierun** [tox-dev/tox#1430]
I need to run tox on 2.7 (yes, I know but it's still supported for a few more months) and I am getting this:

```
tox -rvv
Traceback (most recent call last):
  File "/usr/bin/tox", line 7, in <module>
    from tox import cmdline
  File "/usr/lib/python2.7/site-packages/tox/__init__.py", line 9, in <module>
    import pluggy
  File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 11, in <module>
    import importlib_metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax
```

**Comment by kierun** [comment]
[I did not see this issue.](https://github.com/tox-dev/tox/issues/1406)

Closing this one. My apologies for the noise.
