### ISSUE TITLE
tox fails to detect platform in install_command

### ISSUE THREAD

**Issue by mosi-kha** [tox-dev/tox#1464]
hi 
```
[testenv:test]
platform = win: win32
install_command = win: python -m pip install {packages} {toxinidir}\third_packages\Shapely-1.6.4.post2-cp37-cp37m-win_amd64.whl
```

```

when use `win: ` in `install_command` tox raise `IndexError`
full trackback:
`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2.4\helpers\pycharm\_jb_tox_runner.py", line 103, in <module>
    config = tox_config.parseconfig(args=sys.argv[1:])
  File "D:\Projects\python\cheetagp\biziou-backend\env\lib\site-packages\tox\config\__init__.py", line 273, in parseconfig
    ParseIni(config, config_file, content)
  File "D:\Projects\python\cheetagp\biziou-backend\env\lib\site-packages\tox\config\__init__.py", line 1178, in __init__
    for key, (exc, trace) in failures.items()
tox.exception.ConfigError: ConfigError: test failed with list index out of range at Traceback (most recent call last):
  File "D:\Projects\python\cheetagp\biziou-backend\env\lib\site-packages\tox\config\__init__.py", line 1150, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "D:\Projects\python\cheetagp\biziou-backend\env\lib\site-packages\tox\config\__init__.py", line 1302, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "D:\Projects\python\cheetagp\biziou-backend\env\lib\site-packages\tox\config\__init__.py", line 1559, in getargv
    return self.getargvlist(name, default, replace=replace)[0]
IndexError: list index out of range`

```

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).
