### ISSUE TITLE
Install tox==3.14.2 on python 3.5 fails

### ISSUE THREAD

**Issue by luiscoms** [tox-dev/tox#1479]
We are installing on docker image https://hub.docker.com/repository/docker/rbsdev/s2i-python-35

When we ran **pip install tox**

```bash
$ docker run --rm -it rbsdev/s2i-python-35 pip install tox
Collecting tox
  Downloading https://files.pythonhosted.org/packages/a7/64/73ee95a48a69fb40f9ce415cdeda09c0c2721da483aae0687884f3cb0586/tox-3.14.2-py2.py3-none-any.whl (80kB)
Exception:
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2795, in _dep_map
    return self.__dep_map
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2652, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.5/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/opt/app-root/lib/python3.5/site-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/opt/app-root/lib/python3.5/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/opt/app-root/lib/python3.5/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/opt/app-root/lib/python3.5/site-packages/pip/req/req_set.py", line 561, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2774, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2797, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2830, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2827, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/opt/app-root/lib/python3.5/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined
You are using pip version 7.1.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

When we ran **pip install 'tox<3.14.2'**

```bash
$ docker run --rm -it rbsdev/s2i-python-35 bash -c "pip install 'tox<3.14.2'"
...
Successfully installed ...
```

**Comment by gaborbernat** [comment]
** You are using pip version 7.1.2, however version 19.3.1 is available. ** 

Please upgrade your pip to something newer and will work. pips old as that don't support environment markers we're using.
