### ISSUE TITLE
docker-compose throws "docker.errors.DockerException: Credentials store error:" when running script via Tox Command

### ISSUE THREAD

**Issue by BenStuart** [tox-dev/tox#1486]
Hi,

I have a bash script that builds a docker image of my project using your typical dockerfile and docker-compose.

When running the script outside of tox, i.e terminal (without sudo) the script is successful.

Running the command in tox (with sudo) works. Running the script without sudo the script crashes. Running the script in tox as sudo isn't practically really.

I turned `docker compose --verbose` on to get some more details. A note to make is I am running tox using `pipenv run tox`.

Below is the verbose details 

```
py38 run-test-pre: commands[0] | /home/dev/Projects/xxx/docker/docker_build.sh
compose.config.config.find: Using configuration files: ./build.yml
docker.auth.find_config_file: Trying paths: ['/home/dev/.docker/config.json', '/home/dev/.dockercfg']
docker.auth.find_config_file: Found file at path: /home/dev/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Auth data for {0} is absent. Client might be using a credentials store instead.
docker.auth.load_config: Found 'HttpHeaders' section
docker.auth.load_config: Found 'credsStore' section
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/version HTTP/1.1" 200 535
compose.cli.command.get_client: docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15+
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: Version=18.09.7, MinAPIVersion=1.12, KernelVersion=5.0.0-37-generic, Platform={u'Name': u''}, ApiVersion=1.39, Arch=amd64, GoVersion=go1.10.1, Os=linux, BuildTime=2019-08-14T19:41:23.000000000+00:00, GitCommit=2d0083d, Components=[{u'Version': u'18.09.7', u'Details': {u'GoVersion': u'go1.10.1', u'MinAPIVersion': u'1.12', u'KernelVersion': u'5.0.0-37-generic', u'ApiVersion': u'1.39', u'Arch': u'amd64', u'Os': u'linux', u'BuildTime': u'2019-08-14T19:41:23.000000000+00:00', u'Experimental': u'false', u'GitCommit': u'2d0083d'}, u'Name': u'Engine'}]
compose.service.build: Building xxx
compose.cli.verbose_proxy.proxy_callable: docker build <- (tag=u'xxx:latest', network_mode=None, shmsize=None, target=None, path='/home/dev/Projects/tsicorepythonservice', labels=None, stream=True, rm=True, cache_from=None, forcerm=False, buildargs={}, nocache=False, pull=False, dockerfile='docker/Dockerfile')
docker.api.build._set_auth_headers: Looking for auth config
docker.auth.resolve_authconfig: Using credentials store "secretservice"
docker.auth._resolve_authconfig_credstore: Looking for auth entry for u'yyy'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 249, in build
    build_args=build_args)
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 343, in build
    service.build(no_cache, pull, force_rm, build_args)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 923, in build
    shmsize=parse_bytes(build_opts.get('shm_size')) if build_opts.get('shm_size') else None,
  File "/usr/lib/python2.7/dist-packages/compose/cli/verbose_proxy.py", line 55, in proxy_callable
    result = getattr(self.obj, call_name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docker/api/build.py", line 238, in build
    self._set_auth_headers(headers)
  File "/usr/lib/python2.7/dist-packages/docker/api/build.py", line 285, in _set_auth_headers
    self._auth_configs, registry
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 97, in resolve_authconfig
    authconfig, registry, store_name
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
    'Credentials store error: {0}'.format(repr(e))
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-secretservice exited with "Cannot autolaunch D-Bus without X11 $DISPLAY".',)
ERROR: InvocationError for command /home/dev/Projects/xxx/docker/docker_build.sh (exited with code 1)
py38 docker: remove '2ef41307f1' (forced)
```

**Comment by BenStuart** [comment]
An update: I've renamed my .docker/config.json to old_config.json. So it no longer makes an attempt.

**Comment by BenStuart** [comment]
Resolved by passing in every environmental var from the host via `passenv=` and halving them until finding `DBUS_SESSION_BUS_ADDRESS` If anyone knows why this is needed please share.

**Comment by asottile** [comment]
`docker` uses some variables to access your secret storage (in this case `secret-service`), you'll need to allow those with `passenv`

by default, `tox` blanks the environment except for a select few variables which are necessary for `python` itself to work
