### ISSUE TITLE
Immediately forwarding Ctrl+C to child processes considered harmful

### ISSUE THREAD

**Issue by stefanholek** [tox-dev/tox#1497]
I have a test runner which install unittests's [signal handlers](https://docs.python.org/3/library/unittest.html#signal-handling). When hitting Ctrl+C in tox, the test runner sometimes receives a SIGINT while in the process of shutting down. This seemed wrong, and I traced it down to tox unconditionally forwarding any received SIGINT. The situation however is that _all_ foreground processes receive the SIGINT, not just tox, and when tox forwards it the test runner receives the SIGINT twice. My solution is to make tox wait for processes to go away on their own before starting to send signals.

Anyway, here is my patch (which no longer applies after #1493, but you get the idea):

```diff
diff --git a/src/tox/action.py b/src/tox/action.py
index 10707b4..9f826a0 100644
--- a/src/tox/action.py
+++ b/src/tox/action.py
@@ -18,6 +18,7 @@ from tox.reporter import Verbosity
 from tox.util.lock import get_unique_file
 from tox.util.stdlib import is_main_thread
 
+WAIT_SUICIDE = 0.5
 WAIT_INTERRUPT = 0.3
 WAIT_TERMINATE = 0.2
 
@@ -177,7 +178,7 @@ class Action(object):
     def handle_interrupt(self, process):
         """A three level stop mechanism for children - INT -> TERM -> KILL"""
         msg = "from {} {{}} pid {}".format(os.getpid(), process.pid)
-        if process.poll() is None:
+        if self._wait(process, WAIT_SUICIDE) is None:
             self.info("KeyboardInterrupt", msg.format("SIGINT"))
             process.send_signal(signal.CTRL_C_EVENT if sys.platform == "win32" else signal.SIGINT)
             if self._wait(process, WAIT_INTERRUPT) is None:
@@ -193,7 +194,7 @@ class Action(object):
         if sys.version_info >= (3, 3):
             # python 3 has timeout feature built-in
             try:
-                process.communicate(timeout=WAIT_INTERRUPT)
+                process.communicate(timeout=timeout)
             except subprocess.TimeoutExpired:
                 pass
         else:
```

**Comment by stefanholek** [comment]
I have looked further into this and it appears that in response to Marius' freak accident with the zope-testrunner (#1172) the code was changed from process.wait() to basically [process.murder()](https://github.com/tox-dev/tox/pull/1186/files#diff-57c0f90ac19d5a79d6495ab22fab6539L142).

That's quite radical IMO and prone to issues like the above. I guess the only reason it did not come up earlier is that few test runners actually have to perform any cleanups.

I am happy to turn this into a PR à la #1493 but would appreciate some feedback first.

**Comment by blueyed** [comment]
I think the patch makes sense - just tried it again after having upvoted it before already.
Needs adjustments after #1493 however.

My use case is running pytest in tox, where it often looks like this then (and often much worse/longer):

```
testing/test_config.py ............^C
=================================================================================== short test summary info ====================================================================================

SKIPPED [1] testing/test_capture.py:1395: only py3.6+ on windows
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/_pytest/mark/structures.py:386: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
================================================================================ 194 passed, 1 skipped in 3.65s ================================================================================
ERROR: got KeyboardInterrupt signal
Traceback (most recent call last):
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/cmdline.py", line 703, in do_run
    runner.run()
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/execfile.py", line 247, in run
    exec(code, main_mod.__dict__)
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/pytest/__main__.py", line 8, in <module>
    raise SystemExit(pytest.main())
SystemExit: ExitCode.INTERRUPTED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tox…/Vcs/pytest/py38-coverage/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/cmdline.py", line 827, in main
    status = CoverageScript().command_line(argv)
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/cmdline.py", line 555, in command_line
    return self.do_run(options, args)
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/cmdline.py", line 710, in do_run
    self.coverage.save()
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/control.py", line 642, in save
    data = self.get_data()
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/control.py", line 696, in get_data
    if self._collector and self._collector.flush_data():
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/collector.py", line 423, in flush_data
    self.covdata.add_arcs(self.mapped_file_dict(self.data))
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/sqldata.py", line 477, in add_arcs
    con.executemany(
  File "/tmp/tox…/Vcs/pytest/py38-coverage/lib/python3.8/site-packages/coverage/sqldata.py", line 1089, in executemany
    return self.con.executemany(sql, data)
KeyboardInterrupt
___________________________________________________________________________________________ summary ____________________________________________________________________________________________
ERROR:   py38-coverage: keyboardinterrupt
```

**Comment by gaborbernat** [comment]
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).
