### ISSUE TITLE
Virtualenv 20.0.0 breaks tox 

### ISSUE THREAD

**Issue by yelsherbini** [tox-dev/tox#1516]
While updating dependencies virtualenv got updated to version 20.0.0. After the update running tox returns the following error 

```
ROR: invocation failed (exit code 1), logfile: /Users/***/Documents/playground/tox_test/.tox/python/log/python-0.log
==================================================================================== log start =====================================================================================
RuntimeError: failed to query /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/python with code 8 err: 'Exec format error'

===================================================================================== log end ======================================================================================
ERROR: InvocationError for command /Users/***/.virtualenvs/test_tox_virtualenv/bin/python3.7 -m virtualenv --no-download --python /Users/***/.virtualenvs/test_tox_virtualenv/bin/python3.7 python (exited with code 1)
_____________________________________________________________________________________ summary ______________________________________________________________________________________
ERROR:   python: InvocationError for command /Users/***/.virtualenvs/test_tox_virtualenv/bin/python3.7 -m virtualenv --no-download --python /Users/***/.virtualenvs/test_tox_virtualenv/bin/python3.7 python (exited with code 1)
```

To reproduce:
```
pip install tox
echo '[tox]\nskipsdist = true' > tox.ini
tox
```

**Comment by gaborbernat** [comment]
This is upstream bug https://github.com/pypa/virtualenv/issues/1545, please report the requested information there.

**Comment by yelsherbini** [comment]
But until it is fixed on virtualenv's side, wouldn't it be better to freeze the dependency to virtualenv 16? Currently any fresh new install or dependency update of tox will be broken.

**Comment by gaborbernat** [comment]
It's likely virtualenv will fix this before tox release gets out.

**Comment by gaborbernat** [comment]
@yelsherbini can you please provide the requested information? How did you install tox?

**Comment by smitt04** [comment]
This shouldn't be closed as this is a current problem. If you just run `pip install tox` this is an issue as it installs the latest version of `virtualenv` which has the bug.

**Comment by gaborbernat** [comment]
@smitt04 if you want to help please provide information on https://github.com/pypa/virtualenv/issues/1545

PS. We can leave this open, but the actionable item, for now, is on the virtualenv side.

**Comment by smitt04** [comment]
I understand it is an issue in `virtualenv` but as a workaround, you can pin virtualenv in your requirements.txt

```
virtualenv==16.0.0
```

**Comment by javierpena** [comment]
Would it be possible to update tox's requirement for six to match the version required by virtualenv 20 (>= 1.12.0)?

It could be argued that it's not strictly needed by tox, but pip does not properly handle the transitive dependency (https://github.com/pypa/pip/issues/988), so we are in a catch-22 situation until either side provides a fix.

**Comment by postrational** [comment]
When running `tox` I'm getting the following error:
```
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/util/path/_sync.py", line 7, in <module>
    from six import PY2, PY3, ensure_text
ImportError: cannot import name 'ensure_text'
```

##### Minimal reproducible example

Builld the following Dockerfile:

```dockerfile
FROM ubuntu:18.04

RUN apt-get update

RUN apt-get install -y \
  python3 \
  python3-pip \
  python3-dev

RUN pip3 install -U pip
RUN pip3 install -U tox
RUN pip list
# The following is a command tox would normally call:
RUN /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 .package
```

###### `pip list` of the environment where virtualenv is installed into if not using the zipapp

```
Package             Version
------------------- -------
appdirs             1.4.3
asn1crypto          0.24.0
cryptography        2.1.4
distlib             0.3.0
filelock            3.0.12
idna                2.6
importlib-metadata  1.5.0
importlib-resources 1.0.2
keyring             10.6.0
keyrings.alt        3.0
packaging           20.1
pip                 20.0.2
pluggy              0.13.1
py                  1.8.1
pycrypto            2.6.1
pygobject           3.26.1
pyparsing           2.4.6
pyxdg               0.25
SecretStorage       2.3.1
setuptools          39.0.1
six                 1.11.0
toml                0.10.0
tox                 3.14.3
virtualenv          20.0.3
wheel               0.30.0
zipp                2.2.0
```

##### Output

```
Step 7/7 : RUN /usr/bin/python3 -m virtualenv -vvv --with-traceback --no-download --python /usr/bin/python3 .package
 ---> Running in e03940f2d861
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/run/__init__.py", line 5, in <module>
    from ..config.cli.parser import VirtualEnvConfigParser
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/config/cli/parser.py", line 6, in <module>
    from ..ini import IniConfig
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/config/ini.py", line 8, in <module>
    from virtualenv.dirs import default_config_dir
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/dirs.py", line 5, in <module>
    from virtualenv.util.lock import ReentrantFileLock
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/util/lock.py", line 11, in <module>
    from virtualenv.util.path import Path
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/util/path/__init__.py", line 5, in <module>
    from ._sync import copy, copytree, ensure_dir, link, symlink
  File "/usr/local/lib/python3.6/dist-packages/virtualenv/util/path/_sync.py", line 7, in <module>
    from six import PY2, PY3, ensure_text
ImportError: cannot import name 'ensure_text'
```
