### ISSUE TITLE
Broken environments result when venv is used and default pip is old

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#1524]
In pypa/setuptools#2000, I discovered an emergent issue where because the default pip for venv is 9.0.1 and because `tox-pip-version` isn't yet installed, the bootstrap environment (`.tox/.tox`; is there a better name for it?) gets installed improperly because one of the dependencies (zipp) has a requirement to be installed as a wheel (which doesn't happen on PyPy) or with pip 10 or later or with setuptools 42 or later. As far as I can tell, there's no way to ensure that pip is upgraded in the bootstrap environment before installing the bootstrap requirements. Even having tox-pip-version installed in advance does not work around the issue. This dockerfile replicates the issue:

```
FROM ubuntu:xenial

RUN apt update
RUN apt install -y curl libexpat1 bzip2
RUN curl -sSf --retry 5 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/pypy3.tar.bz2 -o - | tar xj --directory /
ENV PATH="/opt/python/pypy3/bin:${PATH}"

RUN python -m pip install -U pip setuptools wheel
RUN python -m pip install -U tox tox-venv tox-pip-version

RUN echo '[tox]\n\
skipsdist = true\n\
requires = \n\
  requests\n\
\n\
[testenv]\n\
pip_version = pip\n\
' > tox.ini

CMD tox
```

Here's the output:

```
draft $ docker run -it $(docker build -q .)
.tox create: //.tox/.tox
.tox installdeps: requests, tox >= 3.14.4
Traceback (most recent call last):
  File "/opt/python/pypy3/lib-python/3/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/python/pypy3/lib-python/3/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/python/pypy3/lib-python/3/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "//.tox/.tox/site-packages/tox/__init__.py", line 9, in <module>
    import pluggy
  File "//.tox/.tox/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "//.tox/.tox/site-packages/pluggy/manager.py", line 11, in <module>
    import importlib_metadata
  File "//.tox/.tox/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ModuleNotFoundError: No module named 'zipp'
```

**Comment by gaborbernat** [comment]
This issue would not manifest without tox-venv so I'll close this. If anything the issue belongs under tox-venv.

**Comment by jaraco** [comment]
Maybe consider moving this issue there?

**Comment by gaborbernat** [comment]
I don't own that project, so you'd want to reach out to the maintainers.
