### ISSUE TITLE
Confusing InterpreterNotFound error with isolated_build=True

### ISSUE THREAD

**Issue by astrojuanlu** [tox-dev/tox#1548]
I was reviewing my tox configuration for a project using flit, and I saw I had `skipsdist = True`, which [according to the documentation should be set to True "when using tox for an application, instead of a library"](https://tox.readthedocs.io/en/latest/config.html#conf-skipsdist). Therefore I removed that line to use the default `skipsdist = False`, and this error appeared:

```
$ tox -e py38
.package create: /home/juanlu/Personal/poliastro/poliastro/.tox/.package
ERROR: InterpreterNotFound: 
Traceback (most recent call last):
  File "/home/juanlu/.pyenv/versions/poliastro38/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 194, in runcommand
    return self.subcommand_test()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 210, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/__init__.py", line 16, in tox_package
    session.package, session.dist = get_package(session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/__init__.py", line 40, in acquire_package
    path = build_package(config, session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/builder/__init__.py", line 9, in build_package
    return build(config, session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/builder/isolated.py", line 31, in build
    raise package_venv.status
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 596, in setupenv
    status = self.update(action=action)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 254, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 666, in tox_testenv_create
    config_interpreter = venv.getsupportedinterpreter()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 295, in getsupportedinterpreter
    return self.envconfig.getsupportedinterpreter()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/config/__init__.py", line 979, in getsupportedinterpreter
    raise tox.exception.InterpreterNotFound(self.basepython)
tox.exception.InterpreterNotFound: InterpreterNotFound: 
```

Inserting a `breakpoint()` shows that, at that stage, `self.basepython = ""`.

After a bit of Googling and trial-and-error, I arrived to https://tox.readthedocs.io/en/latest/example/package.html#flit and found the `[tox:.package]` section. I added it, and I keep getting the same error.

This is the current `tox.ini` configuration I'm testing:

<details>

```
[tox]
description = list of environments againts tox runs the tests
envlist =
    clean
    check
    docs
    py36
    py37
    py38{,-online}
    pypy
    pypy3
    coverage
    py38_slow
    py38_images
isolated_build = True

[tox:.package]
# See https://tox.readthedocs.io/en/latest/example/package.html#flit
basepython = python3

[testenv]
whitelist_externals=
    /bin/bash
    /usr/bin/bash
basepython =
    pypy: pypy
    pypy3: pypy3
    py36: python3.6
    py37: python3.7
    py38: python3.8
    {py38_images,py38_slow}: python3.8
    {clean,check,reformat,coverage,docs}: python3
setenv =
    PYTHONUNBUFFERED=yes
passenv =
    *
deps =
    flit >=2,<3
    pygments
commands =
    # TODO: Warning because poliastro does not have test and doc extras
    flit install --deps develop --extras=dev,cesium
    !online: pytest -vv -m "not slow and not mpl_image_compare" {posargs:--mypy -vv}
    online: pytest -vv -m "not slow and not mpl_image_compare" --remote-data=any {posargs:--mypy -vv}


[testenv:coverage]
description = measures code coverage
commands =
    flit install --symlink --deps develop --extras=dev,cesium
    pytest --cov {posargs:--cov-report=term-missing}

[testenv:py38_images]
commands =
    flit install
    pytest -m "mpl_image_compare" --mpl {posargs:-vv}

[testenv:py38_slow]
commands =
    flit install --deps develop --extras=dev,cesium
    pytest -m "slow" -vv {posargs:-vv}


[testenv:check]
description = this environments checks for flake8, black, isort and poliastro code style
deps =
	black
	docutils
	isort
	flake8
	mypy
	pygments
skip_install = true
commands =
    flake8 src
    isort --check-only --diff --recursive --project poliastro --section-default THIRDPARTY src tests
    black --check src tests
    mypy --ignore-missing-imports --check-untyped-defs --no-strict-optional src


[testenv:reformat]
description = reformats the code using black and isort
deps =
	black
	isort
skip_install = true
commands =
    isort --recursive --project poliastro --section-default THIRDPARTY src tests
    black src tests


[testenv:docs]
description = invoke sphinx-build to build the HTML docs
extras =  docs
whitelist_externals = sphinx-build
commands = 
    bash -ec "sudo apt install pandoc texlive texlive-latex-extra texlive-fonts-recommended dvipng graphviz cm-super-minimal"
    pip install .[dev,cesium]
    pip install https://github.com/Juanlu001/sphinx_rtd_theme/archive/avoid-require-redefinition.zip
    sphinx-build -d "{toxworkdir}/docs_doctree" docs/source "{toxworkdir}/docs_out" --color -vW -bhtml

[testenv:clean]
commands = coverage erase
skip_install = true
deps = coverage
```
</details>

And this is the output of `tox -e py38 -vv`:

<details>

```
(poliastro38) juanlu@ephyra:~/Personal/poliastro/poliastro$ tox -e py38 -vv
using tox.ini: /home/juanlu/Personal/poliastro/poliastro/tox.ini (pid 31038)
  removing /home/juanlu/Personal/poliastro/poliastro/.tox/log
using tox-3.14.6 from /home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/__init__.py (pid 31038)
.package start: getenv /home/juanlu/Personal/poliastro/poliastro/.tox/.package
.package cannot reuse: no previous config /home/juanlu/Personal/poliastro/poliastro/.tox/.package/.tox-config1
.package create: /home/juanlu/Personal/poliastro/poliastro/.tox/.package
.package uses None
ERROR: InterpreterNotFound: 
.package finish: getenv /home/juanlu/Personal/poliastro/poliastro/.tox/.package after 0.00 seconds
Traceback (most recent call last):
  File "/home/juanlu/.pyenv/versions/poliastro38/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 194, in runcommand
    return self.subcommand_test()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/session/__init__.py", line 210, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/__init__.py", line 16, in tox_package
    session.package, session.dist = get_package(session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/__init__.py", line 40, in acquire_package
    path = build_package(config, session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/builder/__init__.py", line 9, in build_package
    return build(config, session)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/package/builder/isolated.py", line 31, in build
    raise package_venv.status
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 596, in setupenv
    status = self.update(action=action)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 254, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 666, in tox_testenv_create
    config_interpreter = venv.getsupportedinterpreter()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/venv.py", line 295, in getsupportedinterpreter
    return self.envconfig.getsupportedinterpreter()
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/tox/config/__init__.py", line 979, in getsupportedinterpreter
    raise tox.exception.InterpreterNotFound(self.basepython)
tox.exception.InterpreterNotFound: InterpreterNotFound:
```
</details>

Finally, these are the relevant package versions I'm using:

```
$ pip list | grep -e tox -e virtualenv -e flit -e pip
flit                          2.2.0              
flit-core                     2.2.0              
pip                           20.0.2             
tox                           3.14.6             
virtualenv                    20.0.15           
```

**Comment by astrojuanlu** [comment]
Sorry, I hit the wrong button. See my edits above.

**Comment by gaborbernat** [comment]
This could a weird interaction between using markers in the base ``testenv``, can you try with:

```
basepython =
    pypy: pypy
    pypy3: pypy3
    py36: python3.6
    py37: python3.7
    py38: python3.8
    {py38_images,py38_slow}: python3.8
    {clean,check,reformat,coverage,docs}: python3
   .package: python3
```
And remove the ``[tox:.package]`` section.

**Comment by astrojuanlu** [comment]
Thanks for the quick response @gaborbernat, doing as you said fixed the issue and `tox -e py38` is running like normal now!
