### ISSUE TITLE
skipsdist factor: true raises exception

### ISSUE THREAD

**Issue by altendky** [tox-dev/tox#1567]
I am trying to come up with a clean way to use an existing wheelhouse/`dist/` as the source for installing the local project (#1566).  While failing to find a tidy way to do that I ran across this exception.  Once the exception is addressed (WIP PR incoming) it still doesn't work as you would expect a factor to.

```bash
 ~/r/t/tmp   master ●  cat tox.ini
[tox]
skipsdist = factor: true
```
```bash
 ~/r/t/tmp   master ●  tox -rvv py38
using tox.ini: /home/altendky/repos/tox/tmp/tox.ini (pid 22383)
Traceback (most recent call last):
  File "/home/altendky/.pyenv/versions/3.8.2/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 269, in parseconfig
    ParseIni(config, config_file, content)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1162, in __init__
    config.skipsdist = reader.getbool("skipsdist", all_develop)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1503, in getbool
    s = self.getstring(name, default, replace=replace)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1544, in getstring
    x = self._apply_factors(x)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1570, in _apply_factors
    return "\n".join(filter(None, map(factor_line, lines)))
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1563, in factor_line
    if any(
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1564, in <genexpr>
    included <= self.factors and not any(x in self.factors for x in excluded)
TypeError: '<=' not supported between instances of 'set' and 'tuple'
```
```bash
 ✘  ~/r/t/tmp   master ●  tox -rvv py38-factor
using tox.ini: /home/altendky/repos/tox/tmp/tox.ini (pid 22518)
Traceback (most recent call last):
  File "/home/altendky/.pyenv/versions/3.8.2/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 269, in parseconfig
    ParseIni(config, config_file, content)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1162, in __init__
    config.skipsdist = reader.getbool("skipsdist", all_develop)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1503, in getbool
    s = self.getstring(name, default, replace=replace)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1544, in getstring
    x = self._apply_factors(x)
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1570, in _apply_factors
    return "\n".join(filter(None, map(factor_line, lines)))
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1563, in factor_line
    if any(
  File "/home/altendky/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 1564, in <genexpr>
    included <= self.factors and not any(x in self.factors for x in excluded)
TypeError: '<=' not supported between instances of 'set' and 'tuple'
```

**Comment by gaborbernat** [comment]
``skipsdist`` is a global option so you cannot change it per tox environment, for what factors are designed for.

**Comment by gaborbernat** [comment]
The best we could due here is to raise a more descriptive exception, but I'm not convinced looking at the extra code this is worth at the moment considering we don't plan to support this behaviour.
