### ISSUE TITLE
tox crashes with UnicodeEncodeError when read/write to log

### ISSUE THREAD

**Issue by Zoynels** [tox-dev/tox#1582]
I have problem when some files has non ansii symbols in filenames, but as I understand in appear if something write to `.tox\log\` in Windows with non-ansii symbols.

Example:
tox.ini:
```ini
[tox]
basepython = python3.5
[testenv]
commands = python -c 'print("Привет1")'
```

not work with `setup.py`:
```python
from setuptools import setup
setup()
print("Привет2")
```

[toxxx.zip](https://github.com/tox-dev/tox/files/4639997/toxxx.zip)

Problem appear after write to log `Привет2`:

```
Traceback (most recent call last):
  File "h:\programming\python\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "h:\programming\python\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "h:\Programming\Python\Miniconda3\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "h:\programming\python\miniconda3\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "h:\programming\python\miniconda3\lib\site-packages\tox\session\__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "h:\programming\python\miniconda3\lib\site-packages\tox\session\__init__.py", line 194, in runcommand
    return self.subcommand_test()
  File "h:\programming\python\miniconda3\lib\site-packages\tox\session\__init__.py", line 210, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "h:\programming\python\miniconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "h:\programming\python\miniconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "h:\programming\python\miniconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "h:\programming\python\miniconda3\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "h:\programming\python\miniconda3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "h:\programming\python\miniconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "h:\programming\python\miniconda3\lib\site-packages\tox\package\__init__.py", line 16, in tox_package
    session.package, session.dist = get_package(session)
  File "h:\programming\python\miniconda3\lib\site-packages\tox\package\__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "h:\programming\python\miniconda3\lib\site-packages\tox\package\__init__.py", line 40, in acquire_package
    path = build_package(config, session)
  File "h:\programming\python\miniconda3\lib\site-packages\tox\package\builder\__init__.py", line 7, in build_package
    return make_sdist(config, session)
  File "h:\programming\python\miniconda3\lib\site-packages\tox\package\builder\legacy.py", line 36, in make_sdist
    build_log = action.popen(
  File "h:\programming\python\miniconda3\lib\site-packages\tox\action.py", line 118, in popen
    lines = out_path.read_text("UTF-8").split("\n")
  File "h:\programming\python\miniconda3\lib\site-packages\py\_path\common.py", line 171, in read_text
    return f.read()
  File "h:\programming\python\miniconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 1850: invalid continuation byte
```

**Comment by gaborbernat** [comment]
```
❯ tox4
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: get_requires_for_build_sdist> python /home/bernat/git/tox/.tox/dev/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/bernat/git/tox/.tox/dev/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/bernat/git/tox/.tox/dev/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/magic/.tox/4/.pkg/dist/UNKNOWN-0.0.0.tar.gz
py: commands[0]> python -c 'print("Привет1")'
Привет1
.pkg: _exit> python /home/bernat/git/tox/.tox/dev/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: OK (1.84=setup[1.82]+cmd[0.02] seconds)
  congratulations :) (1.87 seconds)
```

Fixed via tox 4.
