### ISSUE TITLE
Tox fails creating a py39 env

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#1589]
Hi,

I am running Ubuntu 18.04 with @asottile's deadsnake ppa.

I cannot create any py39 env with tox.

e.g.
```
git clone git@github.com:jugmac00/Products.ZopeTree.git

cd Pr...

tox -e=py39
....
...
Collecting coverage>=4.4 (from pytest-cov)
  Using cached https://files.pythonhosted.org/packages/fe/4d/3d892bdd21acba6c9e9bec6dc93fbe619883a0967c62f976122f2c6366f3/coverage-5.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools.depends import Require
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mg66s373/coverage/
WARNING: You are using pip version 19.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: invocation failed (exit code 1)
ERROR: could not install deps [pytest, pytest-cov]; v = InvocationError('/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python -m pip install pytest pytest-cov', 1)
py39 finish: getenv /home/jugmac00/Projects/Products.ZopeTree/.tox/py39 after 4.52 seconds
___________________________________________________________________ summary ___________________________________________________________________
ERROR:   py39: could not install deps [pytest, pytest-cov]; v = InvocationError('/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python -m pip install pytest pytest-cov', 1)
cleanup /home/jugmac00/Projects/Products.ZopeTree/.tox/.tmp/package/1/Products.ZopeTree-2.0.2.dev0.zip
```

This happens with all projects... so there is something fundamentally broken (on my machine).

I tracked the problem down to cpython deprecating HTMLParser unescape
https://bugs.python.org/issue19688

setuptools was using this, but did some changes in 41.1.0 
> * #1788: Changed compatibility fallback logic for ``html.unescape`` to avoid accessing ``HTMLParser.unescape`` when not necessary. ``HTMLParser.unescape`` is deprecated and will be removed in Python 3.9.

So I'd guess somehow an old version of setuptools is used by tox? How would I update setuptools as the dependencies are installed via tox` "deps" option, not via pip.

Thank you very much for looking into this! And keep up the fantastic work!

```
❯ tox -rvv -e=py39
using tox.ini: /home/jugmac00/Projects/Products.ZopeTree/tox.ini (pid 24790)
using tox-3.15.1 from /home/jugmac00/.local/pipx/venvs/tox/lib/python3.6/site-packages/tox/__init__.py (pid 24790)
GLOB start: packaging 
GLOB sdist-make: /home/jugmac00/Projects/Products.ZopeTree/setup.py
[24802] /home/jugmac00/Projects/Products.ZopeTree$ /home/jugmac00/.local/pipx/venvs/tox/bin/python setup.py sdist --formats=zip --dist-dir /home/jugmac00/Projects/Products.ZopeTree/.tox/dist >.tox/log/GLOB-0.log
running sdist
running egg_info
writing src/Products.ZopeTree.egg-info/PKG-INFO
writing dependency_links to src/Products.ZopeTree.egg-info/dependency_links.txt
writing namespace_packages to src/Products.ZopeTree.egg-info/namespace_packages.txt
writing requirements to src/Products.ZopeTree.egg-info/requires.txt
writing top-level names to src/Products.ZopeTree.egg-info/top_level.txt
reading manifest file 'src/Products.ZopeTree.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
warning: no files found matching 'LICENSE'
warning: no files found matching '*.rst'
writing manifest file 'src/Products.ZopeTree.egg-info/SOURCES.txt'
running check
creating Products.ZopeTree-2.0.2.dev0
creating Products.ZopeTree-2.0.2.dev0/examples
creating Products.ZopeTree-2.0.2.dev0/src
creating Products.ZopeTree-2.0.2.dev0/src/Products
creating Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
creating Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree
creating Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/tests
copying files to Products.ZopeTree-2.0.2.dev0...
copying .flake8 -> Products.ZopeTree-2.0.2.dev0
copying .pre-commit-config.yaml -> Products.ZopeTree-2.0.2.dev0
copying .travis.yml -> Products.ZopeTree-2.0.2.dev0
copying CHANGES.txt -> Products.ZopeTree-2.0.2.dev0
copying LICENSE.txt -> Products.ZopeTree-2.0.2.dev0
copying MANIFEST.in -> Products.ZopeTree-2.0.2.dev0
copying README.md -> Products.ZopeTree-2.0.2.dev0
copying __init__.py -> Products.ZopeTree-2.0.2.dev0
copying pyproject.toml -> Products.ZopeTree-2.0.2.dev0
copying setup.py -> Products.ZopeTree-2.0.2.dev0
copying tox.ini -> Products.ZopeTree-2.0.2.dev0
copying examples/tree.pt -> Products.ZopeTree-2.0.2.dev0/examples
copying examples/tree_menu.pt -> Products.ZopeTree-2.0.2.dev0/examples
copying src/Products/__init__.py -> Products.ZopeTree-2.0.2.dev0/src/Products
copying src/Products.ZopeTree.egg-info/PKG-INFO -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products.ZopeTree.egg-info/SOURCES.txt -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products.ZopeTree.egg-info/dependency_links.txt -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products.ZopeTree.egg-info/namespace_packages.txt -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products.ZopeTree.egg-info/not-zip-safe -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products.ZopeTree.egg-info/requires.txt -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products.ZopeTree.egg-info/top_level.txt -> Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info
copying src/Products/ZopeTree/IZopeTree.py -> Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree
copying src/Products/ZopeTree/TreeObjectWrapper.py -> Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree
copying src/Products/ZopeTree/ZopeTree.py -> Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree
copying src/Products/ZopeTree/__init__.py -> Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree
copying src/Products/ZopeTree/tests/test_ZopeTree.py -> Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/tests
Writing Products.ZopeTree-2.0.2.dev0/setup.cfg
creating /home/jugmac00/Projects/Products.ZopeTree/.tox/dist
creating '/home/jugmac00/Projects/Products.ZopeTree/.tox/dist/Products.ZopeTree-2.0.2.dev0.zip' and adding 'Products.ZopeTree-2.0.2.dev0' to it
adding 'Products.ZopeTree-2.0.2.dev0'
adding 'Products.ZopeTree-2.0.2.dev0/examples'
adding 'Products.ZopeTree-2.0.2.dev0/src'
adding 'Products.ZopeTree-2.0.2.dev0/.flake8'
adding 'Products.ZopeTree-2.0.2.dev0/PKG-INFO'
adding 'Products.ZopeTree-2.0.2.dev0/tox.ini'
adding 'Products.ZopeTree-2.0.2.dev0/pyproject.toml'
adding 'Products.ZopeTree-2.0.2.dev0/.travis.yml'
adding 'Products.ZopeTree-2.0.2.dev0/LICENSE.txt'
adding 'Products.ZopeTree-2.0.2.dev0/MANIFEST.in'
adding 'Products.ZopeTree-2.0.2.dev0/setup.py'
adding 'Products.ZopeTree-2.0.2.dev0/CHANGES.txt'
adding 'Products.ZopeTree-2.0.2.dev0/.pre-commit-config.yaml'
adding 'Products.ZopeTree-2.0.2.dev0/__init__.py'
adding 'Products.ZopeTree-2.0.2.dev0/setup.cfg'
adding 'Products.ZopeTree-2.0.2.dev0/README.md'
adding 'Products.ZopeTree-2.0.2.dev0/examples/tree.pt'
adding 'Products.ZopeTree-2.0.2.dev0/examples/tree_menu.pt'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/namespace_packages.txt'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/SOURCES.txt'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/PKG-INFO'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/dependency_links.txt'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/requires.txt'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/not-zip-safe'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products.ZopeTree.egg-info/top_level.txt'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/__init__.py'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/tests'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/ZopeTree.py'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/TreeObjectWrapper.py'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/IZopeTree.py'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/__init__.py'
adding 'Products.ZopeTree-2.0.2.dev0/src/Products/ZopeTree/tests/test_ZopeTree.py'
removing 'Products.ZopeTree-2.0.2.dev0' (and everything under it)

GLOB finish: packaging  after 0.18 seconds
copying new sdistfile to '/home/jugmac00/.tox/distshare/Products.ZopeTree-2.0.2.dev0.zip'
package .tmp/package/1/Products.ZopeTree-2.0.2.dev0.zip links to dist/Products.ZopeTree-2.0.2.dev0.zip (/home/jugmac00/Projects/Products.ZopeTree/.tox)
py39 start: getenv /home/jugmac00/Projects/Products.ZopeTree/.tox/py39
py39 cannot reuse: -r flag
py39 create: /home/jugmac00/Projects/Products.ZopeTree/.tox/py39
python3.9 (/usr/bin/python3.9) is {'executable': '/usr/bin/python3.9', 'name': 'python', 'version_info': [3, 9, 0, 'beta', 1], 'version': '3.9.0b1 (default, May 19 2020, 02:39:13) \n[GCC 7.5.0]', 'is_64': True, 'sysplatform': 'linux'}
py39 uses /usr/bin/python3.9
setting PATH=/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[24806] /home/jugmac00/Projects/Products.ZopeTree/.tox$ /home/jugmac00/.local/pipx/venvs/tox/bin/python -m virtualenv --no-download --python /usr/bin/python3.9 py39
Running virtualenv with interpreter /usr/bin/python3.9
Using base prefix '/usr'
New python executable in /home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python3.9
Also creating executable in /home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python
Installing setuptools, pip, wheel...
done.
py39 installdeps: pytest, pytest-cov
setting PATH=/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[24814] /home/jugmac00/Projects/Products.ZopeTree$ /home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python -m pip install pytest pytest-cov
Collecting pytest
  Using cached https://files.pythonhosted.org/packages/6c/f9/9f2b6c672c8f8bb87a4c1bd52c1b57213627b035305aad745d015b2a62ae/pytest-5.4.2-py3-none-any.whl
Collecting pytest-cov
  Using cached https://files.pythonhosted.org/packages/b4/4d/56896f913ea61f0ba504c912bdd748f11e45ef14d5d40975bc8322dccfa0/pytest_cov-2.9.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest)
  Using cached https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl
Collecting packaging (from pytest)
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest)
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting wcwidth (from pytest)
  Using cached https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest)
  Using cached https://files.pythonhosted.org/packages/06/b1/2dcadc4861c505a807d5c6d88928450fe5afcf352f205432572a10d74657/more_itertools-8.3.0-py3-none-any.whl
Collecting coverage>=4.4 (from pytest-cov)
  Using cached https://files.pythonhosted.org/packages/fe/4d/3d892bdd21acba6c9e9bec6dc93fbe619883a0967c62f976122f2c6366f3/coverage-5.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools.depends import Require
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mg66s373/coverage/
WARNING: You are using pip version 19.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: invocation failed (exit code 1)
ERROR: could not install deps [pytest, pytest-cov]; v = InvocationError('/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python -m pip install pytest pytest-cov', 1)
py39 finish: getenv /home/jugmac00/Projects/Products.ZopeTree/.tox/py39 after 4.52 seconds
___________________________________________________________________ summary ___________________________________________________________________
ERROR:   py39: could not install deps [pytest, pytest-cov]; v = InvocationError('/home/jugmac00/Projects/Products.ZopeTree/.tox/py39/bin/python -m pip install pytest pytest-cov', 1)
cleanup /home/jugmac00/Projects/Products.ZopeTree/.tox/.tmp/package/1/Products.ZopeTree-2.0.2.dev0.zip
```

**Comment by asottile** [comment]
if you upgrade the version of `virtualenv` adjacent to `tox` you'll end up with a new-enough `setuptools` in the resulting environment

fwiw it's working for me on another project:

```console
$ tox -e py39
...
======================== 728 passed, 7 xfailed in 2.56s ========================
py39 run-test: commands[2] | coverage report --fail-under 100
Name    Stmts   Miss Branch BrPart  Cover   Missing
---------------------------------------------------
---------------------------------------------------
TOTAL    1964      0    785      0   100%

33 files skipped due to complete coverage.
py39 run-test: commands[3] | pre-commit install
pre-commit installed at .git/hooks/pre-commit
___________________________________ summary ____________________________________
  py39: commands succeeded
  congratulations :)
```

```console
$ ~/opt/venv/bin/pip freeze -l | grep -E '^(tox|virtualenv)'
tox==3.14.6
virtualenv==20.0.20
```

**Comment by jugmac00** [comment]
Thank you very much. Works like a charm.

Can you give me a hint why trying to update `setuptools` did not work for me? Why virtualenv?

**Comment by rpkilby** [comment]
tox 3.10 changed how it creates virtualenvs. From the changelog:

> Virtual environments created now no longer upgrade pip/wheel/setuptools to the latest version. Instead the start packages after virtualenv creation now is whatever virtualenv has bundled in. This allows faster virtualenv creation and builds that are easier to reproduce.

So, virtualenv is installing its bundled version of setuptools, not the version that's present in your environment.
