### ISSUE TITLE
tox throws an exception when Python regedit entry has an InstallPath with no ExecutablePath and no default value

### ISSUE THREAD

**Issue by sylvaus** [tox-dev/tox#1592]
It seems that the current code in `load_exe` in `pep514.py` cannot handle the case when the Python regedit entry has an InstallPath with no ExecutablePath and no default value.

```python
def load_exe(hive_name, company, company_key, tag):
    key_path = "{}/{}/{}".format(hive_name, company, tag)
    try:
        with winreg.OpenKeyEx(company_key, r"{}\InstallPath".format(tag)) as ip_key:
            with ip_key:
                exe = get_value(ip_key, "ExecutablePath")
                if exe is None:
                    ip = get_value(ip_key, None)
                    if ip is None:
                        msg(key_path, "no ExecutablePath or default for it")
                        # Adding the following code seems to solve the issue: return None, None
                    else:
                        exe = os.path.join(ip, "python.exe")
                if os.path.exists(exe): # <-- fails here because exe was None and ip was None
                    args = get_value(ip_key, "ExecutableArguments")
                    return exe, args
                else:
                    msg(key_path, "exe does not exists {}".format(exe))
    except OSError:
        msg("{}/{}".format(key_path, "InstallPath"), "missing")
    return None, None
```

Environment to reproduce:
![image](https://user-images.githubusercontent.com/20885444/83366533-b6b86a00-a37d-11ea-8075-235b471c92d7.png)

tox.ini
```
[tox]
envlist = py27,py35,py36,py37py38

[testenv]
deps = pytest
commands = pytest {posargs}
```

traceback:
```
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Github\appify\venv\Scripts\tox.exe\__main__.py", line 9, in <module>
  File "d:\github\appify\venv\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "d:\github\appify\venv\lib\site-packages\tox\session\__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "d:\github\appify\venv\lib\site-packages\tox\session\__init__.py", line 194, in runcommand
    return self.subcommand_test()
  File "d:\github\appify\venv\lib\site-packages\tox\session\__init__.py", line 222, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "d:\github\appify\venv\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "d:\github\appify\venv\lib\site-packages\tox\venv.py", line 597, in setupenv
    status = self.update(action=action)
  File "d:\github\appify\venv\lib\site-packages\tox\venv.py", line 254, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "d:\github\appify\venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "d:\github\appify\venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "d:\github\appify\venv\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "d:\github\appify\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "d:\github\appify\venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "d:\github\appify\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "d:\github\appify\venv\lib\site-packages\tox\venv.py", line 667, in tox_testenv_create
    config_interpreter = venv.getsupportedinterpreter()
  File "d:\github\appify\venv\lib\site-packages\tox\venv.py", line 295, in getsupportedinterpreter
    return self.envconfig.getsupportedinterpreter()
  File "d:\github\appify\venv\lib\site-packages\tox\config\__init__.py", line 990, in getsupportedinterpreter
    info = self.config.interpreters.get_info(envconfig=self)
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\__init__.py", line 33, in get_info
    executable = self.get_executable(envconfig)
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\__init__.py", line 27, in get_executable
    exe = self.hook.tox_get_python_executable(envconfig=envconfig)
  File "d:\github\appify\venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "d:\github\appify\venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "d:\github\appify\venv\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "d:\github\appify\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "d:\github\appify\venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "d:\github\appify\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\__init__.py", line 19, in tox_get_python_executable
    py_exe = locate_via_pep514(spec)
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\__init__.py", line 45, in locate_via_pep514
    _PY_AVAILABLE.extend(pep514.discover_pythons())
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\pep514.py", line 49, in discover_pythons
    for spec in process_set(hive, hive_name, key, flags, default_arch):
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\pep514.py", line 59, in process_set
    for spec in process_company(hive_name, company, root_key, default_arch):
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\pep514.py", line 68, in process_company
    for spec in process_tag(hive_name, company, company_key, tag, default_arch):
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\pep514.py", line 78, in process_tag
    exe, args = load_exe(hive_name, company, company_key, tag)
  File "d:\github\appify\venv\lib\site-packages\tox\interpreters\windows\pep514.py", line 97, in load_exe
    if os.path.exists(exe):
  File "D:\Program Files (x86)\Python37\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

**Comment by gaborbernat** [comment]
This logic now moved to virtualenv, so if the issue still exists please open it within virtualenv.
