### ISSUE TITLE
Default envdir usage error

### ISSUE THREAD

**Issue by ofek** [tox-dev/tox#1593]
How does one set a default `envdir`? In https://github.com/DataDog/integrations-core/pull/6789 we're trying to speed up CI but it is failing with:

```
ERROR: venv 'style' in /home/vsts/work/1/s/active_directory would delete project
ERROR: ConfigError: envdir must not equal toxinidir
```

Essentially we want something like the following (which does not work):

```
[testenv]
envdir =
    !py{27,38}: {toxworkdir}/{envname}
    py27: {toxworkdir}/py27
    py38: {toxworkdir}/py38
```

That gives an exception:

```
Traceback (most recent call last):
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_error.py", line 66, in checked_call
    return func(*args, **kwargs)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\ofek\\Desktop\\code\\integrations-core\\disk\\.tox\\py27\nC:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\Scripts\tox.exe\__main__.py", line 9, in <module>
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\session\__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\session\__init__.py", line 192, in runcommand
    return self.subcommand_test()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\session\__init__.py", line 220, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\venv.py", line 594, in setupenv
    status = self.update(action=action)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\venv.py", line 252, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\tox\venv.py", line 678, in tox_testenv_create
    base_path.ensure(dir=1)
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_path\local.py", line 535, in ensure
    return p._ensuredirs()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_path\local.py", line 517, in _ensuredirs
    parent._ensuredirs()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_path\local.py", line 517, in _ensuredirs
    parent._ensuredirs()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_path\local.py", line 517, in _ensuredirs
    parent._ensuredirs()
  [Previous line repeated 4 more times]
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_path\local.py", line 520, in _ensuredirs
    self.mkdir()
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_path\local.py", line 470, in mkdir
    py.error.checked_call(os.mkdir, fspath(p))
  File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\py\_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOTDIR: [Not a directory]: mkdir('C:\\Users\\ofek\\Desktop\\code\\integrations-core\\disk\\.tox\\py27\nC:',)
```

If this is a real bug, we also have a plugin where we can do any workaround if you tell us how 😄 https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/plugin/tox.py

@gaborbernat

**Comment by gaborbernat** [comment]
Need to check, but it could just be that markers are not supported. How much of a speedup does this actually offer? Assuming the dependencies are wheels this should be very low. 🤔

**Comment by ofek** [comment]
It seems ~5-8% speed up

**Comment by ofek** [comment]
We have a workaround for now https://github.com/DataDog/integrations-core/pull/6789/commits/020a7ea02b866ae2787186411241ef9b02616dda

**Comment by gaborbernat** [comment]
@ofek Does it worth it for 5-8%? 😊 (we should still fix the error, but this is, for now, an unsupported behaviour, so it's more a feature request than bug request)

**Comment by ofek** [comment]
@gaborbernat Time is literal money in this case, so yup haha

Sure, sounds like a feature request

**Comment by gaborbernat** [comment]
Seems you have a fix for version 3, as for version 4 I think should work; if it does not please post a reproducible repo and we can take a look.
