### ISSUE TITLE
`{temp_dir}` does not work

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/tox#1608]
```python-traceback
Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 192, in _
run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/__main__.py", line 4, in <module>
    tox.cmdline()
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 274, in parseconfig
    ParseIni(config, config_file, content)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1193, in __init__
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: docs failed with ConfigError: substitution key 'temp_dir' not found at Traceback (most recent call last):
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1169, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1317, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1586, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1796, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1832, in processcommand
    new_word = reader._replace(word)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1643, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1679, in do_replace
    expanded = substitute_once(value)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1677, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1724, in _replace_match
    return self._replace_substitution(match)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1759, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File ".../.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1753, in _substitute_from_other_section
    raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
tox.exception.ConfigError: ConfigError: substitution key 'temp_dir' not found
```

Ref: https://github.com/tox-dev/tox/pull/1032/files#r446709505

**Comment by gaborbernat** [comment]
This is not meant as public.
