### ISSUE TITLE
Paths in requires longer than 63 characters don't work anymore

### ISSUE THREAD

**Issue by konstin** [tox-dev/tox#1634]
With tox 3.12.1, I could use the following pyproject.toml and tox.ini:

```toml
[build-system]
requires = ["/some/absolute/path/maturin-0.8.3-py3-none-manylinux1_x86_64.whl"]
build-backend = "maturin"
```

```ini
[tox]
envlist = py36,py37
isolated_build = True

[testenv]
deps = pytest
commands = pytest
```

With tox 3.18.1 however this fails with `pyparsing.exceptions.ParseException: Expected W:(abcd...), found '/'  (at char 0), (line:1, col:1)`.  It appears that the error occurs with all paths that are at least 64 characters long.

```
using tox.ini: /home/konsti/maturin/test-crates/a/tox.ini (pid 29012)
  removing /home/konsti/maturin/test-crates/a/.tox/log
using tox-3.18.1 from /home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/__init__.py (pid 29012)
/home/konsti/maturin/.venv/bin/python (/home/konsti/maturin/.venv/bin/python) is {'executable': '/home/konsti/maturin/.venv/bin/python', 'implementation': 'CPython', 'version_info': [3, 7, 7, 'final', 0], 'version': '3.7.7 (default, May  6 2020, 22:02:39) \n[GCC 7.5.0]', 'is_64': True, 'sysplatform': 'linux', 'extra_version_info': None}
.package uses /home/konsti/maturin/.venv/bin/python
.package start: getenv /home/konsti/maturin/test-crates/a/.tox/.package
.package cannot reuse: -r flag
.package recreate: /home/konsti/maturin/test-crates/a/.tox/.package
  removing /home/konsti/maturin/test-crates/a/.tox/.package
setting PATH=/home/konsti/maturin/test-crates/a/.tox/.package/bin:/home/konsti/maturin/.venv/bin:/home/konsti/.pyenv/shims:/home/konsti/.pyenv/bin:/home/konsti/Verschiedenes/swift-2.2/usr/bin:/home/konsti/.poetry/bin:/home/konsti/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/konsti/.cargo/bin:/home/konsti/.local/bin:/home/konsti/.poetry/bin
[29016] /home/konsti/maturin/test-crates/a/.tox$ /home/konsti/maturin/.venv/bin/python -m virtualenv --no-download --python /home/konsti/maturin/.venv/bin/python .package
created virtual environment CPython3.7.7.final.0-64 in 157ms
  creator CPython3Posix(dest=/home/konsti/maturin/test-crates/a/.tox/.package, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/konsti/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
.package installdeps: /home/konsti/maturin/target/wheels/maturin-0.8.3-py3-none-manylinux1_x86_64.whl
setting PATH=/home/konsti/maturin/test-crates/a/.tox/.package/bin:/home/konsti/maturin/.venv/bin:/home/konsti/.pyenv/shims:/home/konsti/.pyenv/bin:/home/konsti/Verschiedenes/swift-2.2/usr/bin:/home/konsti/.poetry/bin:/home/konsti/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/konsti/.cargo/bin:/home/konsti/.local/bin:/home/konsti/.poetry/bin
[29023] /home/konsti/maturin/test-crates/a$ /home/konsti/maturin/test-crates/a/.tox/.package/bin/python -m pip install /home/konsti/maturin/target/wheels/maturin-0.8.3-py3-none-manylinux1_x86_64.whl
Processing /home/konsti/maturin/target/wheels/maturin-0.8.3-py3-none-manylinux1_x86_64.whl
Collecting toml~=0.10.0
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Installing collected packages: toml, maturin
Successfully installed maturin-0.8.3 toml-0.10.1
WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
You should consider upgrading via the '/home/konsti/maturin/test-crates/a/.tox/.package/bin/python -m pip install --upgrade pip' command.
.package finish: getenv /home/konsti/maturin/test-crates/a/.tox/.package after 1.96 seconds
.package start: finishvenv 
write config to /home/konsti/maturin/test-crates/a/.tox/.package/.tox-config1 as '81ca95aa3edb3dcad3a273f93058c29f4381ac52e718637f5c61d1331b0f57f9 /home/konsti/maturin/.venv/bin/python\n3.18.1 0 0 0\nb0c78ab65502fa0f75963f645dd4dab3a5145a7219869ee5a9a9814229ca12b7 /home/konsti/maturin/target/wheels/maturin-0.8.3-py3-none-manylinux1_x86_64.whl'
.package finish: finishvenv  after 0.09 seconds
.package start: get-build-requires /home/konsti/maturin/test-crates/a/.tox/.package
setting PATH=/home/konsti/maturin/test-crates/a/.tox/.package/bin:/home/konsti/maturin/.venv/bin:/home/konsti/.pyenv/shims:/home/konsti/.pyenv/bin:/home/konsti/Verschiedenes/swift-2.2/usr/bin:/home/konsti/.poetry/bin:/home/konsti/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/konsti/.cargo/bin:/home/konsti/.local/bin:/home/konsti/.poetry/bin
[29030] /home/konsti/maturin/test-crates/a$ /home/konsti/maturin/test-crates/a/.tox/.package/bin/python /home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/helper/build_requires.py maturin '' >.tox/.package/log/.package-0.log
.package finish: get-build-requires /home/konsti/maturin/test-crates/a/.tox/.package after 0.05 seconds
Traceback (most recent call last):
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pyparsing/core.py", line 821, in parseString
    raise exc
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pyparsing/core.py", line 2265, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.exceptions.ParseException: Expected W:(abcd...), found '/'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/konsti/maturin/.venv/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/session/__init__.py", line 196, in runcommand
    return self.subcommand_test()
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/session/__init__.py", line 212, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/package/__init__.py", line 16, in tox_package
    session.package, session.dist = get_package(session)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/package/__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/package/__init__.py", line 40, in acquire_package
    path = build_package(config, session)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/package/builder/__init__.py", line 9, in build_package
    return build(config, session)
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/package/builder/isolated.py", line 36, in build
    canonicalize_name(Requirement(r.name).name) for r in package_venv.envconfig.deps
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/tox/package/builder/isolated.py", line 36, in <setcomp>
    canonicalize_name(Requirement(r.name).name) for r in package_venv.envconfig.deps
  File "/home/konsti/maturin/.venv/lib/python3.7/site-packages/packaging/requirements.py", line 102, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
packaging.requirements.InvalidRequirement: Parse error at "'/home/ko'": Expected W:(abcd...)
```

NB: To reproduce, you don't even need a wheel in that place, just a `pyproject.toml` and a `tox.ini` are sufficient.

**Comment by gaborbernat** [comment]
@konstin this has been discoussed elsewhere, but absolute paths are not supported within requires. It would go against the spirit of PEP-518. The goal with PEP-518 is that you're able to setup the development environment in another machine, if the path is an absolute path, there's no guarantee it will exist on other machines too.

**Comment by konstin** [comment]
The issue is not one of absolute paths - both absolute and relative paths work, they are only required to be shorted than 64 characters.

My intention not to publish that tox.ini, but to test tox compatibility of maturin before publishing a new release. Is there a way to locally test a PEP 517 backend without using paths in `requires`? With pip for example I can use `--find-links`, but I couldn't find an equivalent option for tox.

**Comment by gaborbernat** [comment]
@konstin tox translates all commands to pip, so you can just set ``--find-links`` within your tox ini for https://tox.readthedocs.io/en/latest/config.html#conf-install_command

**Comment by gaborbernat** [comment]
So looking at the code the issue is not per se on tox side, the packaging library refuses to parse paths anymore, maybe one of the recent releases does this now https://pypi.org/project/packaging/#history

**Comment by gaborbernat** [comment]
Looking at https://github.com/pypa/packaging/commit/eb0243865079c7c2179730da93130447556ea020 seems the format for specifying absolute URLs is different then what you specified. Per PEP-508 absolute paths may be specified as:

```
name @ file:///absolute/path
```

https://www.python.org/dev/peps/pep-0508/. Other formats are undefined, so may or may not work.
