### ISSUE TITLE
Cannot run tox on MSYS2 (MINGW64)

### ISSUE THREAD

**Issue by eine** [tox-dev/tox#1648]
When trying to use tox on MSYS2 (MINGW64), I am getting several errors.

Executing locally:

```
# tox -rvv
using tox.ini: T:/tox/tox.ini (pid 24268)
  removing T:/tox/.tox/log
c:/msys64/mingw64/bin/python3.exe (c:/msys64/mingw64/bin/python3.exe) is {'executable': 'c:/msys64/mingw64/bin/python3.exe', 'implementation': 'CPython', 'version_info': [3, 8, 5, 'final', 0], 'version': '3.8.5 (default, Jul 21 2020, 11:59:41)  [GCC 10.1.0 64 bit (AMD64)]', 'is_64': True, 'sysplatform': 'win32', 'extra_version_info': None}
.package uses c:/msys64/mingw64/bin/python3.exe
py38 uses c:/msys64/mingw64/bin/python3.exe
PEP-514 violation in Windows Registry at HKEY_CURRENT_USER/PythonCore/2.7 error: exe does not exists C:\Users\eine\.platformio\python27\python.exe
dev uses c:/msys64/mingw64/bin/python3.exe
pypy uses None
pypy3 uses None
python2.7 (C:/msys64/usr/bin/python2.7.EXE) is {'executable': '/usr/bin/python2.7', 'version_info': [2, 7, 18, 'final', 0], 'implementation': 'CPython', 'sysplatform': 'msys', 'version': '2.7.18 (default, Apr 20 2020, 16:05:03) \n[GCC 9.3.0]', 'is_64': True, 'extra_version_info': None}
py27 uses /usr/bin/python2.7
python (C:/msys64/mingw64/bin/python.EXE) is {'executable': 'C:/msys64/mingw64/bin/python.EXE', 'implementation': 'CPython', 'version_info': [3, 8, 5, 'final', 0], 'version': '3.8.5 (default, Jul 21 2020, 11:59:41)  [GCC 10.1.0 64 bit (AMD64)]', 'is_64': True, 'sysplatform': 'win32', 'extra_version_info': None}
py36 uses None
py37 uses None
py35 uses None
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/msys64/mingw64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/msys64/mingw64/bin/tox.exe/__main__.py", line 7, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/session/__init__.py", line 65, in main
    config = load_config(args)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/session/__init__.py", line 81, in load_config
    config = parseconfig(args)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 275, in parseconfig
    ParseIni(config, config_file, content)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1215, in __init__
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: py27 failed with [WinError 2] The system cannot find the file specified at Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/interpreters/__init__.py", line 38, in get_info        
    return self.executable2info[executable]
KeyError: '/usr/bin/python2.7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1191, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1339, in make_envconfig      
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1608, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1818, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1854, in processcommand      
    new_word = reader._replace(word)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1665, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1701, in do_replace
    expanded = substitute_once(value)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1699, in substitute_once     
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1746, in _replace_match      
    return self._replace_substitution(match)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1783, in _replace_substitution
    val = val()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1016, in get_envsitepackagesdir
    x = self.config.interpreters.get_sitepackagesdir(info=self.python_info, envdir=self.envdir)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/config/__init__.py", line 1022, in python_info
    return self.config.interpreters.get_info(envconfig=self)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/interpreters/__init__.py", line 40, in get_info        
    info = run_and_get_interpreter_info(name, executable)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/interpreters/__init__.py", line 60, in run_and_get_interpreter_info
    result = get_python_info(str(executable))
  File "C:/msys64/mingw64/lib/python3.8/site-packages/tox/interpreters/via_path.py", line 62, in get_python_info 
    proc = subprocess.Popen(
  File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

In a GitHub Actions workflow:

```
Installing collected packages: toml, pluggy, py, filelock, distlib, virtualenv, tox
ERROR: Cannot uninstall 'distlib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Trying VUnit/vunit locally:

```
WARNING: test command found but not installed in testenv
  cmd: C:/msys64/mingw64/bin/python.EXE
  env: T:/vunit/vunit/.tox/py38-unit
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above!
```

However, the same tox config files seem to work on a different Python environment. See:

- https://github.com/eine/tox/commit/6ca445d80aff5a4247dcac2b4a7fa27ab67a349d
- https://github.com/eine/tox/actions/runs/199554488
- https://github.com/eine/vunit/actions/runs/199555508

/cc @lazka @LarsAsplund

**Comment by lazka** [comment]
For the first error my guess would be that installing a mingw python2 might help. (I've never used tox, so not sure)

**Comment by eine** [comment]
@lazka, if executed with `-e py38` (to avoid missing envs), the error is the second one commented above:

```
 ERROR: Cannot uninstall 'distlib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

- https://github.com/eine/tox/runs/967998417?check_suite_focus=true#step:4:28
- https://github.com/eine/tox/commit/aa184acd236fee6dc76155fabe7a153cc66a4954

**Comment by gaborbernat** [comment]
That error comes from pip, and as such you probably want to report it there. It could be a Github Actions setup issue.

**Comment by eine** [comment]
@gaborbernat, what about the local execution which produces the following?

```
WARNING: test command found but not installed in testenv
  cmd: C:/msys64/mingw64/bin/python.EXE
  env: T:/vunit/vunit/.tox/py38-unit
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above!
```

**Comment by eine** [comment]
After fixing the pip/distlib issue in MSYS2, the same error about test/testenv is produced See https://github.com/msys2/MINGW-packages/issues/7014#issuecomment-697098281.

**Comment by gaborbernat** [comment]
That error seems to point that creating the virtual environment failed, because you're using the system python executable instead of the virtual one. What version of virtualenv do you have besides tox?

**Comment by eine** [comment]
The reported version of virtualenv is 20.0.31. See https://github.com/eine/tox/runs/1158452793?check_suite_focus=true#step:4:39 and https://github.com/eine/tox/runs/1158452765?check_suite_focus=true#step:4:16. However, as discussed in MINGW-packages, it seems to be fundamentally broken and it might need to be specifically packaged for MSYS2. Unfortunately, I'm lacking knowledge for understanding the details. Thanks for your help anyway. I'll try to follow up in MSYS2.
