### ISSUE TITLE
{packages}, {opts} and {posargs} in substititions in wrong context has lots of odd backtraces

### ISSUE THREAD

**Issue by jayvdb** [tox-dev/tox#1695]
Using `{packages}`, `{opts}`, and `{posargs}` incorrectly in tox.ini causes all sorts of varied backtraces.

From memory this has always been a backtrace, but I have noticed tox is starting to avoid backtraces, replacing them with error messages.

It is unlikely that someone might accidentally hit these, as they will have found these magic variables from the docs.  The docs fairly clearly indicate that `{packages}` and `{opts}` is restricted to `install_command`.   The docs for `{posargs}` less clearly limit it to `commands`, `commands_pre` and `commands_post`.

To be honest, `posargs` and `packages` could be valid substitution values more generally throughout the testenv config, although some limitations may be needed for `packages` to avoid cyclic substitutions (but the existing cyclic substitution error message nicely catches most scenarios so there may be nothing to worry about here).

In any case, this is a very low priority.  However I have also noticed that there are no tests about misusing these, and I found it difficult to cause a failure when I tried adding `{packages}` or `{opts}` to `test_env_variables_added_to_pcall`.  The mocking there appears to be skipping the relevant expansion.  This is because they in a special case in `config/__init__.py` (`if sub_value in ("opts", "packages"):`) which prevents them blowing up early.  I suspect that special case should be moved closer to the `install_command` logic so that the error messages are more consistent.

**Comment by jayvdb** [comment]
I have what I think is a nice enhancement for `{packages}` and `{opts}`, to add least make them fail in a consistent way no matter where it appears.  `{opts}` is more complicated.

**Comment by jayvdb** [comment]
wrt `{posargs}`, an example oddity is

```ini
[testenv]
setenv =
  POSARGS_VAR = {posargs:default}
commands =
  echo {env:POSARGS_VAR}
```

result:

```py
Traceback (most recent call last):
  File "/usr/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/usr/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/usr/lib/python3.8/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File "/usr/lib/python3.8/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 269, in parseconfig
    ParseIni(config, config_file, content)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1181, in __init__
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: No support for the posargs substitution type at Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 362, in get
    return self.resolved[name]
KeyError: 'POSARGS_VAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1157, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1305, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1574, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1784, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1820, in processcommand
    new_word = reader._replace(word)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1631, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1667, in do_replace
    expanded = substitute_once(value)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1665, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1703, in _replace_match
    return self._replace_env(match)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1719, in _replace_env
    value = self.reader.get_environ_value(key)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1499, in get_environ_value
    return self._setenv.get(name)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 372, in get
    self.resolved[name] = res = self.reader._replace(val)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1631, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1667, in do_replace
    expanded = substitute_once(value)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1665, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/usr/lib/python3.8/site-packages/tox/config/__init__.py", line 1709, in _replace_match
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: No support for the posargs substitution type
```
