### ISSUE TITLE
tox.exception.ConfigError: ConfigError: substitution key 'print $1' not found

### ISSUE THREAD

**Issue by jonathan-s** [tox-dev/tox#1748]
I believe this to be a bug. 

It occurs when I run the command -> `bash -c "kill -s HUP $(ps | grep manage.py | grep -v grep | awk '{print $1}')"`

The full traceback. You can also view it here: https://travis-ci.com/github/jonathan-s/django-sockpuppet/jobs/445459062

```
Traceback (most recent call last):

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/__main__.py", line 4, in <module>

    tox.cmdline()

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/session/__init__.py", line 44, in cmdline

    main(args)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/session/__init__.py", line 65, in main

    config = load_config(args)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/session/__init__.py", line 81, in load_config

    config = parseconfig(args)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 278, in parseconfig

    ParseIni(config, config_file, content)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1252, in __init__

    for key, (exc, trace) in failures.items()

tox.exception.ConfigError: ConfigError: py36-django-30-cypress failed with ConfigError: substitution key 'print $1' not found at Traceback (most recent call last):

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1225, in run

    results[name] = cur_self.make_envconfig(name, section, subs, config)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1379, in make_envconfig

    res = meth(env_attr.name, env_attr.default, replace=replace)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1659, in getargvlist

    return _ArgvlistReader.getargvlist(self, s, replace=replace)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1872, in getargvlist

    commands.append(cls.processcommand(reader, current_command, replace))

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1909, in processcommand

    new_word = reader._replace(word)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1716, in _replace

    replaced = Replacer(self, crossonly=crossonly).do_replace(value)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1752, in do_replace

    expanded = substitute_once(value)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1750, in substitute_once

    return self.RE_ITEM_REF.sub(self._replace_match, x)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1797, in _replace_match

    return self._replace_substitution(match)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1835, in _replace_substitution

    val = self._substitute_from_other_section(sub_key)

  File "/home/travis/build/jonathan-s/django-sockpuppet/.tox/.tox/lib/python3.6/site-packages/tox/config/__init__.py", line 1829, in _substitute_from_other_section

    raise tox.exception.ConfigError("substitution key {!r} not found".format(key))

tox.exception.ConfigError: ConfigError: substitution key 'print $1' not found
```

**Comment by jonathan-s** [comment]
Could solve this with escaping `{` to `\{`
