### ISSUE TITLE
tox4: py36 UnicodeDecodeError

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#1783]
Error only happens on tox4/py36 - no failure on tox3 or other environments.

```
git clone git@github.com:romanlv/trml2pdf.git
cd trml2pdf/

❯ tox4 -e py36
py36: install_deps trml2pdf> .tox4/py36/bin/python -I -m pip install -r /tmp/trml2pdf/trml2pdf/requirements-3nn9lobl.txt
.package: install_requires trml2pdf> .tox4/.package/bin/python -I -m pip install wheel 'setuptools>=40.8.0'
.package: get_requires_for_build_sdist trml2pdf> python /home/jugmac00/opt/tox4/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.package: prepare_metadata_for_build_wheel trml2pdf> python /home/jugmac00/opt/tox4/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
py36: install_package_deps trml2pdf> .tox4/py36/bin/python -I -m pip install 'six>=1.9.0' 'reportlab>=3.2.0'
.package: build_sdist trml2pdf> python /home/jugmac00/opt/tox4/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
py36: install_package trml2pdf> .tox4/py36/bin/python -I -m pip install --no-deps --force-reinstall /tmp/trml2pdf/.tox4/.package/dist/trml2pdf-0.5.0.tar.gz
py36: commands[0] trml2pdf> python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing trml2pdf.egg-info/PKG-INFO
writing dependency_links to trml2pdf.egg-info/dependency_links.txt
writing entry points to trml2pdf.egg-info/entry_points.txt
writing requirements to trml2pdf.egg-info/requires.txt
writing top-level names to trml2pdf.egg-info/top_level.txt
reading manifest file 'trml2pdf.egg-info/SOURCES.txt'
writing manifest file 'trml2pdf.egg-info/SOURCES.txt'
running build_ext
test_error_mode (tests.test_keepinframe_tag.TestKeepInFrame)
Tests that a LayoutError is raised if the onOverflow ... ok
test_run_all (tests.test_examples.TestExamples) ... ERROR

======================================================================
ERROR: test_run_all (tests.test_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/trml2pdf/tests/test_examples.py", line 23, in test_run_all
    self._run_all_examples()
  File "/tmp/trml2pdf/tests/test_examples.py", line 33, in _run_all_examples
    output = trml2pdf.parseString(f.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 189: ordinal not in range(128)

----------------------------------------------------------------------
Ran 2 tests in 0.074s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=2 errors=1 failures=0>
running: ex7.rml
running: ex9.rml
running: devis.rml
running: ex_keepinframe.rml
running: aie.rml
running: ex4.rml
running: ex3.rml
running: ex_unicode.rml
error: Test failed: <unittest.runner.TextTestResult run=2 errors=1 failures=0>
py36: exit 1 (0.40 seconds) /tmp/trml2pdf> python setup.py test
.package: _exit trml2pdf> python /home/jugmac00/opt/tox4/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
py36: FAIL ✖ in 5.17 seconds
  py36: FAIL code 1 (5.16=setup[4.76]+cmd[0.40] seconds)
  evaluation failed :( (5.19 seconds)
```

**Comment by gaborbernat** [comment]
Can you check with the rewrite branch, I think https://github.com/tox-dev/tox/pull/1798 fixed it? It passes for me now.

**Comment by jugmac00** [comment]
Works! Thank you!
