### ISSUE TITLE
tox4: support legacy constraint specification

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1788]
Lack of space between command and argument seams to be the issue. The config below, while valid in tox3, makes tox4 choke:

```
deps =
  -r{toxinidir}/docs/requirements.in
  -c{toxinidir}/docs/requirements.txt
```

Output:
```
$ tox4 -e docs                                                                                                                  [10:45:55]
docs: internal error
Traceback (most recent call last):
  File "/Users/ssbarnea/.local/pipx/venvs/tox/lib/python3.9/site-packages/tox/session/cmd/run/single.py", line 41, in _evaluate
    tox_env.ensure_setup(recreate=recreate)
  File "/Users/ssbarnea/.local/pipx/venvs/tox/lib/python3.9/site-packages/tox/tox_env/api.py", line 169, in ensure_setup
    self.setup()
  File "/Users/ssbarnea/.local/pipx/venvs/tox/lib/python3.9/site-packages/tox/tox_env/python/runner.py", line 44, in setup
    self.install_deps()
  File "/Users/ssbarnea/.local/pipx/venvs/tox/lib/python3.9/site-packages/tox/tox_env/python/runner.py", line 68, in install_deps
    requirement_file_content = requirements_file.validate_and_expand()
  File "/Users/ssbarnea/.local/pipx/venvs/tox/lib/python3.9/site-packages/tox/tox_env/python/req_file.py", line 105, in validate_and_expand
    raise ValueError(line)
ValueError: -c/Users/ssbarnea/c/a/ansible-lint/docs/requirements.txt
docs: FAIL ✖ in 0.13 seconds
  docs: FAIL code 2 (0.13 seconds)
  evaluation failed :( (0.20 seconds)
FAIL: 2
```

**Comment by gaborbernat** [comment]
Does it work as expected if you add the space? tox 4 here is more lenient because now allows full `requirements.txt` support, but seems the special-cased `-c` from tox 3 has been missed, needs one more line here https://github.com/tox-dev/tox/blob/rewrite/src/tox/tox_env/python/req_file.py#L62

**Comment by ssbarnea** [comment]
Not really, that is why I raised https://github.com/tox-dev/tox/issues/1789

**Comment by gaborbernat** [comment]
tox4.0.0a4 is out and addresses this request, please give it a try if you can https://tox.readthedocs.io/en/rewrite/changelog.html#v4-0-0a4-2021-01-16
