### ISSUE TITLE
tox4: ValueError when installing deps from requirements path containing spaces.

### ISSUE THREAD

**Issue by domdfcoding** [tox-dev/tox#1792]
In tox4, attempting to install deps from requirements.txt files where the full path contains spaces fails with a `ValueError`.

This is induced by setting the `deps` option under `[testenv]` to `-r {toxinidir}/tests/requirements.txt`, where `toxinidir` expands to a path containing spaces. The issue is not limited to `toxinidir`, as providing the full path fails too. 

The traceback is:

```python
Traceback (most recent call last):
  File "/home/domdf/Python/01 GitHub Repos/03 Libraries/wordle/venv/lib/python3.8/site-packages/tox/session/cmd/run/single.py", line 41, in _evaluate
    tox_env.ensure_setup(recreate=recreate)
  File "/home/domdf/Python/01 GitHub Repos/03 Libraries/wordle/venv/lib/python3.8/site-packages/tox/tox_env/api.py", line 169, in ensure_setup
    self.setup()
  File "/home/domdf/Python/01 GitHub Repos/03 Libraries/wordle/venv/lib/python3.8/site-packages/tox/tox_env/python/runner.py", line 44, in setup
    self.install_deps()
  File "/home/domdf/Python/01 GitHub Repos/03 Libraries/wordle/venv/lib/python3.8/site-packages/tox/tox_env/python/runner.py", line 68, in install_deps
    requirement_file_content = requirements_file.validate_and_expand()
  File "/home/domdf/Python/01 GitHub Repos/03 Libraries/wordle/venv/lib/python3.8/site-packages/tox/tox_env/python/req_file.py", line 94, in validate_and_expand
    raise ValueError(line)
ValueError: -r /home/domdf/Python/01 GitHub Repos/03 Libraries/wordle/tests/requirements.txt
py36: FAIL ✖ in 0.42 seconds
  py36: FAIL code 2 (0.42 seconds)
  evaluation failed :( (0.49 seconds)

```

This works fine in tox 3.

**Comment by gaborbernat** [comment]
tox4.0.0a4 is out and addresses this request, please give it a try if you can https://tox.readthedocs.io/en/rewrite/changelog.html#v4-0-0a4-2021-01-16
