### ISSUE TITLE
tox-3.21 regression: "Malformed substitution"

### ISSUE THREAD

**Issue by oberstet** [tox-dev/tox#1904]
tox 3.20 happily digests

```
setenv =
    XBR_DEBUG_TOKEN_ADDR        = {env:XBR_DEBUG_TOKEN_ADDR:0x0000000000000000000000000000000000000000}
``` 

tox 3.21 bails out with the exact same `tox.ini`:

```
(cpy391_4) oberstet@intel-nuci7:~/scm/s-things/thingcloud$ pip install -U "tox<3.21"
Requirement already satisfied: tox<3.21 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (3.19.0)
Collecting tox<3.21
  Using cached tox-3.20.1-py2.py3-none-any.whl (83 kB)
Requirement already satisfied: py>=1.4.17 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (1.10.0)
Requirement already satisfied: pluggy>=0.12.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (0.13.1)
Requirement already satisfied: packaging>=14 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (20.9)
Requirement already satisfied: virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (20.4.2)
Requirement already satisfied: six>=1.14.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (1.15.0)
Requirement already satisfied: filelock>=3.0.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (3.0.12)
Requirement already satisfied: toml>=0.9.4 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.21) (0.10.2)
Requirement already satisfied: pyparsing>=2.0.2 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from packaging>=14->tox<3.21) (2.4.7)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox<3.21) (1.4.4)
Requirement already satisfied: distlib<1,>=0.3.1 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox<3.21) (0.3.1)
Installing collected packages: tox
  Attempting uninstall: tox
    Found existing installation: tox 3.19.0
    Uninstalling tox-3.19.0:
      Successfully uninstalled tox-3.19.0
Successfully installed tox-3.20.1
(cpy391_4) oberstet@intel-nuci7:~/scm/s-things/thingcloud$ tox -l
sphinx
flake8
mypy
yapf
py39-pytest
pypy37-pytest
build
(cpy391_4) oberstet@intel-nuci7:~/scm/s-things/thingcloud$ pip install -U "tox<3.22"
Requirement already satisfied: tox<3.22 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (3.20.1)
Collecting tox<3.22
  Using cached tox-3.21.4-py2.py3-none-any.whl (84 kB)
Requirement already satisfied: six>=1.14.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (1.15.0)
Requirement already satisfied: py>=1.4.17 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (1.10.0)
Requirement already satisfied: packaging>=14 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (20.9)
Requirement already satisfied: pluggy>=0.12.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (0.13.1)
Requirement already satisfied: toml>=0.9.4 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (0.10.2)
Requirement already satisfied: virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (20.4.2)
Requirement already satisfied: filelock>=3.0.0 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from tox<3.22) (3.0.12)
Requirement already satisfied: pyparsing>=2.0.2 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from packaging>=14->tox<3.22) (2.4.7)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox<3.22) (1.4.4)
Requirement already satisfied: distlib<1,>=0.3.1 in /home/oberstet/cpy391_4/lib/python3.9/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox<3.22) (0.3.1)
Installing collected packages: tox
  Attempting uninstall: tox
    Found existing installation: tox 3.20.1
    Uninstalling tox-3.20.1:
      Successfully uninstalled tox-3.20.1
Successfully installed tox-3.21.4
(cpy391_4) oberstet@intel-nuci7:~/scm/s-things/thingcloud$ tox -l
Traceback (most recent call last):
  File "/home/oberstet/cpy391_4/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/session/__init__.py", line 65, in main
    config = load_config(args)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/session/__init__.py", line 81, in load_config
    config = parseconfig(args)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 280, in parseconfig
    ParseIni(config, config_file, content)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1276, in __init__
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: pypy37-pytest failed with ConfigError: Malformed substitution; no substitution type provided. If you were using `{}` for `os.pathsep`, please use `{:}`. at Traceback (most recent call last):
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1252, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1407, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1703, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace, name=name)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1967, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace, name=name))
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1993, in processcommand
    new_word = reader._replace(word, name=name)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1788, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1824, in do_replace
    expanded = substitute_once(value)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1822, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1875, in _replace_match
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: Malformed substitution; no substitution type provided. If you were using `{}` for `os.pathsep`, please use `{:}`.

py39-pytest failed with ConfigError: Malformed substitution; no substitution type provided. If you were using `{}` for `os.pathsep`, please use `{:}`. at Traceback (most recent call last):
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1252, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1407, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1703, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace, name=name)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1967, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace, name=name))
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1993, in processcommand
    new_word = reader._replace(word, name=name)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1788, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1824, in do_replace
    expanded = substitute_once(value)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1822, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1875, in _replace_match
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: Malformed substitution; no substitution type provided. If you were using `{}` for `os.pathsep`, please use `{:}`.

build failed with ConfigError: Malformed substitution; no substitution type provided. If you were using `{}` for `os.pathsep`, please use `{:}`. at Traceback (most recent call last):
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1252, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1407, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1703, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace, name=name)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1967, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace, name=name))
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1993, in processcommand
    new_word = reader._replace(word, name=name)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1788, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1824, in do_replace
    expanded = substitute_once(value)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1822, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/home/oberstet/cpy391_4/lib/python3.9/site-packages/tox/config/__init__.py", line 1875, in _replace_match
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: Malformed substitution; no substitution type provided. If you were using `{}` for `os.pathsep`, please use `{:}`.

(cpy391_4) oberstet@intel-nuci7:~/scm/s-things/thingcloud$ 
```

**Comment by gaborbernat** [comment]
@jayvdb can you take a look at this, I believe it's because of your changes 🤔

**Comment by jayvdb** [comment]
Will do
