### ISSUE TITLE
tox4: tox fails to parse tox.ini when a testenv contains `deps = .[test]`

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#1933]
This may be related to #1929 (or even a dupe), but this time the failure is caused by a configuration directly in the `tox.ini` file, not in a requirements file.

repo
https://github.com/plone/plone.event

error caused by
https://github.com/plone/plone.event/blob/dfbaaf6f1ac79603f59de6492c20f1c28ce6fcfb/tox.ini#L8

repro
```
❯ tox4 -rvv -e py38
ROOT: 154 D setup logging to DEBUG on pid 13625 [tox/report.py:211]
ROOT: 159 W remove tox env folder /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38 [tox/tox_env/api.py:202]
ROOT: 194 I find interpreter for spec PythonSpec(implementation=CPython, major=3, minor=8) [virtualenv/discovery/builtin.py:62]
ROOT: 195 I proposed PythonInfo(spec=CPython3.6.9.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]', encoding_fs_io=utf-8-UTF-8) [virtualenv/discovery/builtin.py:69]
ROOT: 195 D discover PATH[0]=/home/jugmac00/.cargo/bin [virtualenv/discovery/builtin.py:114]
ROOT: 196 D filesystem is case-sensitive [virtualenv/info.py:28]
ROOT: 196 D discover PATH[1]=/home/jugmac00/.local/bin [virtualenv/discovery/builtin.py:114]
ROOT: 196 D discover PATH[2]=/home/jugmac00/bin [virtualenv/discovery/builtin.py:114]
ROOT: 196 D discover PATH[3]=/usr/local/sbin [virtualenv/discovery/builtin.py:114]
ROOT: 196 D discover PATH[4]=/usr/local/bin [virtualenv/discovery/builtin.py:114]
ROOT: 197 D discover PATH[5]=/usr/sbin [virtualenv/discovery/builtin.py:114]
ROOT: 197 D discover PATH[6]=/usr/bin [virtualenv/discovery/builtin.py:114]
ROOT: 197 D Attempting to acquire lock 140519792202136 on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:270]
ROOT: 197 D Lock 140519792202136 acquired on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:274]
ROOT: 197 D got python info of /usr/bin/python3.8 from /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 198 D Attempting to release lock 140519792202136 on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:315]
ROOT: 198 D Lock 140519792202136 released on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:318]
ROOT: 198 I proposed PathPythonInfo(spec=CPython3.8.8.final.0-64, exe=/usr/bin/python3.8, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:69]
ROOT: 198 D accepted PathPythonInfo(spec=CPython3.8.8.final.0-64, exe=/usr/bin/python3.8, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:71]
ROOT: 228 I create virtual environment via CPython3Posix(dest=/home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38, clear=True, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:52]
ROOT: 228 D delete /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38 [virtualenv/create/creator.py:169]
ROOT: 228 D create folder /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin [virtualenv/util/path/_sync.py:25]
ROOT: 228 D create folder /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages [virtualenv/util/path/_sync.py:25]
ROOT: 228 D write /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 228 D     home = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     version_info = 3.8.8.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     virtualenv = 20.4.2 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D     base-executable = /usr/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 229 D symlink /usr/bin/python3.8 to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/python [virtualenv/util/path/_sync.py:44]
ROOT: 229 D create virtualenv import hook file /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:95]
ROOT: 229 D create /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:98]
ROOT: 230 D ============================== target debug ============================== [virtualenv/run/session.py:54]
ROOT: 230 D debug via /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/python /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:224]
ROOT: 230 D {
  "sys": {
    "executable": "/home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/python",
    "_base_executable": "/home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/python",
    "prefix": "/home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python38.zip",
      "/usr/lib/python3.8",
      "/usr/lib/python3.8/lib-dynload",
      "/home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]",
  "makefile_filename": "/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.8/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.8/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.8/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.8/json/__init__.py'>"
} [virtualenv/run/session.py:55]
ROOT: 259 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jugmac00/.local/share/virtualenv) [virtualenv/run/session.py:59]
py38: 262 D got embed update of distribution wheel from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/wheel.json [virtualenv/app_data/via_disk_folder.py:135]
py38: 262 D got embed update of distribution setuptools from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/setuptools.json [virtualenv/app_data/via_disk_folder.py:135]
py38: 262 D got embed update of distribution pip from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/pip.json [virtualenv/app_data/via_disk_folder.py:135]
py38: 265 D using periodically updated wheel /home/jugmac00/.local/share/virtualenv/wheel/house/setuptools-53.0.0-py3-none-any.whl [virtualenv/seed/wheels/periodic_update.py:53]
py38: 265 D install wheel from wheel /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/seed/wheels/embed/wheel-0.36.2-py2.py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py38: 265 D install pip from wheel /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py38: 265 D install setuptools from wheel /home/jugmac00/.local/share/virtualenv/wheel/house/setuptools-53.0.0-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py38: 265 D Attempting to acquire lock 140519764970800 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:270]
py38: 266 D Attempting to acquire lock 140519765108104 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:270]
py38: 266 D Attempting to acquire lock 140519765108440 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:270]
py38: 266 D Lock 140519764970800 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:274]
py38: 266 D Lock 140519765108104 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:274]
py38: 266 D Lock 140519765108440 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:274]
py38: 266 D Attempting to release lock 140519764970800 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:315]
py38: 267 D Attempting to release lock 140519765108104 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:315]
py38: 267 D Lock 140519764970800 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:318]
py38: 267 D Attempting to release lock 140519765108440 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:315]
py38: 267 D Lock 140519765108104 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:318]
py38: 267 D Lock 140519765108440 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:318]
py38: 267 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel-0.36.2.virtualenv to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/wheel-0.36.2.virtualenv [virtualenv/util/path/_sync.py:52]
py38: 267 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip-21.0.1.virtualenv to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/pip-21.0.1.virtualenv [virtualenv/util/path/_sync.py:52]
py38: 268 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/pkg_resources to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/pkg_resources [virtualenv/util/path/_sync.py:52]
py38: 268 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel-0.36.2.dist-info to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/wheel-0.36.2.dist-info [virtualenv/util/path/_sync.py:52]
py38: 268 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip-21.0.1.dist-info to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/pip-21.0.1.dist-info [virtualenv/util/path/_sync.py:52]
py38: 272 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/wheel [virtualenv/util/path/_sync.py:52]
py38: 272 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/pip [virtualenv/util/path/_sync.py:52]
py38: 278 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/distutils-precedence.pth to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:52]
py38: 278 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/_distutils_hack to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:52]
py38: 281 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/wheel3 to 755 [distlib/util.py:566]
py38: 281 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/wheel3.8 to 755 [distlib/util.py:566]
py38: 281 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/wheel to 755 [distlib/util.py:566]
py38: 281 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/setuptools to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/setuptools [virtualenv/util/path/_sync.py:52]
py38: 282 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/wheel-3.8 to 755 [distlib/util.py:566]
py38: 287 D generated console scripts wheel wheel-3.8 wheel3 wheel3.8 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
py38: 320 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/setuptools-53.0.0.dist-info to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/setuptools-53.0.0.dist-info [virtualenv/util/path/_sync.py:52]
py38: 322 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/setuptools-53.0.0.virtualenv to /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/lib/python3.8/site-packages/setuptools-53.0.0.virtualenv [virtualenv/util/path/_sync.py:52]
py38: 323 D generated console scripts  [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
py38: 345 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/pip-3.8 to 755 [distlib/util.py:566]
py38: 345 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/pip3 to 755 [distlib/util.py:566]
py38: 345 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/pip to 755 [distlib/util.py:566]
py38: 345 D changing mode of /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/bin/pip3.8 to 755 [distlib/util.py:566]
py38: 345 D generated console scripts pip pip3.8 pip-3.8 pip3 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
ROOT: 345 I add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [virtualenv/run/session.py:66]
ROOT: 346 D write /home/jugmac00/All/output_plone/plone/plone.event/.tox/4/py38/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 346 D     home = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 346 D     implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 346 D     version_info = 3.8.8.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 346 D     virtualenv = 20.4.2 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 347 D     include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 347 D     base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 347 D     base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 347 D     base-executable = /usr/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 349 E internal error [tox/session/cmd/run/single.py:53]
Traceback (most recent call last):
  File "/home/jugmac00/.local/lib/python3.6/site-packages/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/home/jugmac00/.local/lib/python3.6/site-packages/pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...), found '.'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/python/req_file.py", line 125, in _expand_non_flag
    req = Requirement(requirement)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/packaging/requirements.py", line 102, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
packaging.requirements.InvalidRequirement: Parse error at "'.[test]'": Expected W:(abcd...)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/session/cmd/run/single.py", line 41, in _evaluate
    tox_env.ensure_setup(recreate=recreate)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/api.py", line 179, in ensure_setup
    self.setup()
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/python/virtual_env/api.py", line 109, in setup
    super().setup()
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/python/api.py", line 162, in setup
    super().setup()
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/runner.py", line 81, in setup
    self.before_package_install()
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/python/runner.py", line 49, in before_package_install
    requirement_file_content = requirements_file.validate_and_expand()
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/python/req_file.py", line 115, in validate_and_expand
    self._expand_non_flag(at, ini_dir, line, result)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/tox_env/python/req_file.py", line 136, in _expand_non_flag
    raise ValueError(f"{at}: {line}") from exc
ValueError: 2: .[test]
  py38: FAIL code 2 (0.19 seconds)
  evaluation failed :( (0.22 seconds)
```

**Comment by gaborbernat** [comment]
I think this a subset of that: relative path with extras within ``requirements.txt``.

**Comment by jugmac00** [comment]
This one is unaffected by #1991 and remains open.

**Comment by jugmac00** [comment]
Works like a charm, thank you!
