### ISSUE TITLE
tox4: ValueError: No closing quotation (via shlex)

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#1944]
repo
https://github.com/plone/Products.isurlinportal

works with tox3

The problem seems to be this line in the tox.ini
`sed -ie "s#test-5.x.cfg#test-{env:PLONE_VERSION}.x.cfg#" {envdir}/buildout.cfg`

```
❯ tox4 -rvv -e 52-py38
ROOT: 156 D setup logging to DEBUG on pid 28776 [tox/report.py:211]
ROOT: 160 W remove tox env folder /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38 [tox/tox_env/api.py:202]
ROOT: 216 I find interpreter for spec PythonSpec(implementation=CPython, major=3, minor=8) [virtualenv/discovery/builtin.py:62]
ROOT: 216 I proposed PythonInfo(spec=CPython3.6.9.final.0-64, exe=/usr/bin/python3, platform=linux, version='3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]', encoding_fs_io=utf-8-UTF-8) [virtualenv/discovery/builtin.py:69]
ROOT: 217 D discover PATH[0]=/home/jugmac00/.cargo/bin [virtualenv/discovery/builtin.py:114]
ROOT: 218 D filesystem is case-sensitive [virtualenv/info.py:28]
ROOT: 219 D Attempting to acquire lock 139656277905192 on /home/jugmac00/.local/share/virtualenv/py_info/1/23b74721d84db1e4a489cb325282bd44e17fd008d88ce3debbefb934c35f1921.lock [filelock.py:270]
ROOT: 247 D Lock 139656277905192 acquired on /home/jugmac00/.local/share/virtualenv/py_info/1/23b74721d84db1e4a489cb325282bd44e17fd008d88ce3debbefb934c35f1921.lock [filelock.py:274]
ROOT: 247 D get interpreter info via cmd: /home/jugmac00/All/output_plone/plone/Products.isurlinportal/python /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/discovery/py_info.py [virtualenv/discovery/cached_py_info.py:91]
ROOT: 249 D Attempting to release lock 139656277905192 on /home/jugmac00/.local/share/virtualenv/py_info/1/23b74721d84db1e4a489cb325282bd44e17fd008d88ce3debbefb934c35f1921.lock [filelock.py:315]
ROOT: 250 D Lock 139656277905192 released on /home/jugmac00/.local/share/virtualenv/py_info/1/23b74721d84db1e4a489cb325282bd44e17fd008d88ce3debbefb934c35f1921.lock [filelock.py:318]
ROOT: 250 I failed to query /home/jugmac00/All/output_plone/plone/Products.isurlinportal/python with code 13 err: 'Permission denied' [virtualenv/discovery/cached_py_info.py:33]
ROOT: 250 D discover PATH[1]=/home/jugmac00/.local/bin [virtualenv/discovery/builtin.py:114]
ROOT: 250 D discover PATH[2]=/home/jugmac00/bin [virtualenv/discovery/builtin.py:114]
ROOT: 250 D discover PATH[3]=/usr/local/sbin [virtualenv/discovery/builtin.py:114]
ROOT: 251 D discover PATH[4]=/usr/local/bin [virtualenv/discovery/builtin.py:114]
ROOT: 251 D discover PATH[5]=/usr/sbin [virtualenv/discovery/builtin.py:114]
ROOT: 251 D discover PATH[6]=/usr/bin [virtualenv/discovery/builtin.py:114]
ROOT: 252 D Attempting to acquire lock 139656277904576 on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:270]
ROOT: 252 D Lock 139656277904576 acquired on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:274]
ROOT: 252 D got python info of /usr/bin/python3.8 from /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 253 D Attempting to release lock 139656277904576 on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:315]
ROOT: 253 D Lock 139656277904576 released on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:318]
ROOT: 253 I proposed PathPythonInfo(spec=CPython3.8.8.final.0-64, exe=/usr/bin/python3.8, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:69]
ROOT: 254 D accepted PathPythonInfo(spec=CPython3.8.8.final.0-64, exe=/usr/bin/python3.8, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:71]
ROOT: 289 I create virtual environment via CPython3Posix(dest=/home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38, clear=True, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:52]
ROOT: 289 D delete /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38 [virtualenv/create/creator.py:169]
ROOT: 290 D create folder /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin [virtualenv/util/path/_sync.py:25]
ROOT: 290 D create folder /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages [virtualenv/util/path/_sync.py:25]
ROOT: 290 D write /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 290 D 	home = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	version_info = 3.8.8.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	virtualenv = 20.4.2 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 290 D 	base-executable = /usr/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 291 D symlink /usr/bin/python3.8 to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/python [virtualenv/util/path/_sync.py:44]
ROOT: 291 D create virtualenv import hook file /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:95]
ROOT: 291 D create /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:98]
ROOT: 292 D ============================== target debug ============================== [virtualenv/run/session.py:54]
ROOT: 292 D debug via /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/python /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:224]
ROOT: 292 D {
  "sys": {
    "executable": "/home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/python",
    "_base_executable": "/home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/python",
    "prefix": "/home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python38.zip",
      "/usr/lib/python3.8",
      "/usr/lib/python3.8/lib-dynload",
      "/home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]",
  "makefile_filename": "/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.8/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.8/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.8/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.8/json/__init__.py'>"
} [virtualenv/run/session.py:55]
ROOT: 330 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jugmac00/.local/share/virtualenv) [virtualenv/run/session.py:59]
ROOT: 333 D got embed update of distribution setuptools from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/setuptools.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 336 D got embed update of distribution wheel from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/wheel.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 336 D using periodically updated wheel /home/jugmac00/.local/share/virtualenv/wheel/house/setuptools-53.0.0-py3-none-any.whl [virtualenv/seed/wheels/periodic_update.py:53]
ROOT: 336 D got embed update of distribution pip from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/pip.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 337 D install wheel from wheel /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/seed/wheels/embed/wheel-0.36.2-py2.py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
ROOT: 337 D install setuptools from wheel /home/jugmac00/.local/share/virtualenv/wheel/house/setuptools-53.0.0-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
ROOT: 337 D install pip from wheel /home/jugmac00/.local/lib/python3.6/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
ROOT: 338 D Attempting to acquire lock 139656250637560 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:270]
ROOT: 338 D Attempting to acquire lock 139656250637728 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:270]
ROOT: 338 D Lock 139656250637560 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:274]
ROOT: 338 D Lock 139656250637728 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:274]
ROOT: 338 D Attempting to acquire lock 139656250637784 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:270]
ROOT: 338 D Attempting to release lock 139656250637560 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:315]
ROOT: 339 D Lock 139656250637784 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:274]
ROOT: 339 D Attempting to release lock 139656250637728 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:315]
ROOT: 339 D Lock 139656250637560 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:318]
ROOT: 339 D Lock 139656250637728 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any.lock [filelock.py:318]
ROOT: 339 D Attempting to release lock 139656250637784 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:315]
ROOT: 339 D Lock 139656250637784 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:318]
ROOT: 339 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel-0.36.2.virtualenv to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/wheel-0.36.2.virtualenv [virtualenv/util/path/_sync.py:52]
ROOT: 339 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip-21.0.1.virtualenv to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/pip-21.0.1.virtualenv [virtualenv/util/path/_sync.py:52]
ROOT: 340 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/pkg_resources to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/pkg_resources [virtualenv/util/path/_sync.py:52]
ROOT: 340 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip-21.0.1.dist-info to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/pip-21.0.1.dist-info [virtualenv/util/path/_sync.py:52]
ROOT: 341 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel-0.36.2.dist-info to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/wheel-0.36.2.dist-info [virtualenv/util/path/_sync.py:52]
ROOT: 344 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/wheel [virtualenv/util/path/_sync.py:52]
ROOT: 345 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/pip [virtualenv/util/path/_sync.py:52]
ROOT: 349 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/distutils-precedence.pth to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:52]
ROOT: 350 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/_distutils_hack to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:52]
ROOT: 352 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/setuptools to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/setuptools [virtualenv/util/path/_sync.py:52]
ROOT: 352 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/wheel3.8 to 755 [distlib/util.py:566]
ROOT: 352 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/wheel-3.8 to 755 [distlib/util.py:566]
ROOT: 353 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/wheel3 to 755 [distlib/util.py:566]
ROOT: 353 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/wheel to 755 [distlib/util.py:566]
ROOT: 353 D generated console scripts wheel wheel3 wheel-3.8 wheel3.8 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
ROOT: 379 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/setuptools-53.0.0.dist-info to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/setuptools-53.0.0.dist-info [virtualenv/util/path/_sync.py:52]
ROOT: 381 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-53.0.0-py3-none-any/setuptools-53.0.0.virtualenv to /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/lib/python3.8/site-packages/setuptools-53.0.0.virtualenv [virtualenv/util/path/_sync.py:52]
ROOT: 382 D generated console scripts  [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
ROOT: 406 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/pip3 to 755 [distlib/util.py:566]
ROOT: 406 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/pip to 755 [distlib/util.py:566]
ROOT: 407 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/pip3.8 to 755 [distlib/util.py:566]
ROOT: 407 D changing mode of /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/bin/pip-3.8 to 755 [distlib/util.py:566]
ROOT: 407 D generated console scripts pip-3.8 pip3.8 pip pip3 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
ROOT: 407 I add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [virtualenv/run/session.py:66]
ROOT: 408 D write /home/jugmac00/All/output_plone/plone/Products.isurlinportal/.tox/4/52-py38/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 408 D 	home = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	version_info = 3.8.8.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	virtualenv = 20.4.2 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 408 D 	base-executable = /usr/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 411 W install_deps> python -I -m pip install setuptools==41.2.0 zc.buildout==2.13.3 [tox/tox_env/api.py:288]
Collecting setuptools==41.2.0
  Using cached setuptools-41.2.0-py2.py3-none-any.whl (576 kB)
Collecting zc.buildout==2.13.3
  Using cached zc.buildout-2.13.3-py2.py3-none-any.whl (153 kB)
Installing collected packages: setuptools, zc.buildout
  Attempting uninstall: setuptools
    Found existing installation: setuptools 53.0.0
    Uninstalling setuptools-53.0.0:
      Successfully uninstalled setuptools-53.0.0
Successfully installed setuptools-41.2.0 zc.buildout-2.13.3
ROOT: 2184 I exit 0 (1.77 seconds) /home/jugmac00/All/output_plone/plone/Products.isurlinportal> python -I -m pip install setuptools==41.2.0 zc.buildout==2.13.3 pid=28791 [tox/execute/api.py:200]
ROOT: 2187 E internal error [tox/session/cmd/run/single.py:53]
Traceback (most recent call last):
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/session/cmd/run/single.py", line 42, in _evaluate
    code, outcomes = run_commands(tox_env, no_test)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/session/cmd/run/single.py", line 72, in run_commands
    status_main = run_command_set(tox_env, "commands", chdir, ignore_errors, outcomes)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/session/cmd/run/single.py", line 83, in run_command_set
    command_set: List[Command] = tox_env.conf[key]
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/sets.py", line 86, in __getitem__
    return self.load(item)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/sets.py", line 97, in load
    return config_definition(self._conf, item, self.loaders, chain)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/of_type.py", line 99, in __call__
    value = loader.load(key, self.of_type, self.kwargs, conf, self.env_name, chain)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/loader/api.py", line 98, in load
    converted = self.to(prepared, of_type, kwargs)
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/loader/convert.py", line 27, in to
    return self._to_typing(raw, of_type, kwargs)  # type: ignore[return-value]
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/loader/convert.py", line 49, in _to_typing
    result = [self.to(i, entry_type, kwargs) for i in self.to_list(raw, entry_type)]
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/loader/convert.py", line 49, in <listcomp>
    result = [self.to(i, entry_type, kwargs) for i in self.to_list(raw, entry_type)]
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/loader/convert.py", line 33, in to
    return self.to_command(raw)  # type: ignore[return-value]
  File "/home/jugmac00/.local/lib/python3.6/site-packages/tox/config/loader/str_convert.py", line 68, in to_command
    args = list(splitter)
  File "/usr/lib/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.6/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
  52-py38: FAIL code 2 (2.03 seconds)
  evaluation failed :( (2.06 seconds)
```

**Comment by gaborbernat** [comment]
@jugmac00 I think this is one of those changes that are breaking but we're willing to accept it. In tox 4 you can add comments now at the end of any configuration value. You could do this before in some places but not others. Going ahead a unescaped comment character makes the rest of the line just a comment.So in this case the only thin that gets to the command manifestation is ``sed -ie "s`` which is an invalid shell expression and raises. For what it's worth I think that we should not raise and fallback to the unescaped value, which I'll add, but that will still make this repository broken in tox 4 :+1: They'll need to change the command to

```ini
sed -ie "s\#test-5.x.cfg#test-{env:PLONE_VERSION}.x.cfg\#" {envdir}/buildout.cfg
```

**Comment by mauritsvanrees** [comment]
> sed -ie "s\#test-5.x.cfg\#test-{env:PLONE_VERSION}.x.cfg\#" {envdir}/buildout.cfg

Should someone else run into this with a `sed` pattern, the given pattern seems okay on Linux, but fails on Mac:

```
sed: 1: "s\#test-5.x.cfg\#test-5 ...": substitute pattern can not be delimited by newline or backslash
```

I usually take a single slash as delimiter, as long as it does not conflict with the rest of the pattern, and then tox4 works for me:

```
sed -ie "s/test-5.x.cfg/test-{env:PLONE_VERSION}.x.cfg/" {envdir}/buildout.cfg
```
