### ISSUE TITLE
tox4: a possible quoting issue

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#1948]
**repo**
https://github.com/zopefoundation/zope.i18nmessageid

**tox3**
passes

**possible problem**
```
commands =
    zope-testrunner --test-path=src []
```

**from the docs**
>   --test-path TEST_PATH
                        Specify a path to be searched for tests, but not added
                        to the Python search path. This option can be used
                        multiple times to specify multiple search paths. The
                        path is usually specified by the test-runner script
                        itself, rather than by users of the script, although
                        it can be overridden

I am not sure what the empty brackets even mean. @jamadden /  @mgedmin, could you give us a hint?

When I remove the brackets, still run all tests, but then even tox4 does not break.

```
❯ tox4 -e py38
.pkg: get_requires_for_build_wheel> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
py38: install_package> python -I -m pip install --no-deps --force-reinstall /home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/.pkg/dist/zope.i18nmessageid-5.0.2.dev0.tar.gz
py38: commands[0]> zope-testrunner --test-path=src '[]'
Traceback (most recent call last):
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/bin/zope-testrunner", line 8, in <module>
    sys.exit(run())
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/lib/python3.8/site-packages/zope/testrunner/__init__.py", line 30, in run
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd,
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/lib/python3.8/site-packages/zope/testrunner/__init__.py", line 51, in run_internal
    runner.run()
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/lib/python3.8/site-packages/zope/testrunner/runner.py", line 179, in run
    feature.global_setup()
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/lib/python3.8/site-packages/zope/testrunner/find.py", line 518, in global_setup
    tests = find_tests(self.runner.options, self.runner.found_suites)
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/lib/python3.8/site-packages/zope/testrunner/find.py", line 169, in find_tests
    module_accept = build_filtering_func(options.module)
  File "/home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid/.tox/4/py38/lib/python3.8/site-packages/zope/testrunner/filter.py", line 107, in build_filtering_func
    store(re.compile(pattern).search)
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 549, in _parse
    raise source.error("unterminated character set",
re.error: unterminated character set at position 0
py38: exit 1 (0.16 seconds) /home/jugmac00/All/output_zope/zopefoundation/zope.i18nmessageid> zope-testrunner --test-path=src '[]' pid=18562
.pkg: _exit> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
  py38: FAIL code 1 (1.44=setup[1.28]+cmd[0.16] seconds)
  evaluation failed :( (1.47 seconds)
```

fun fact - this is by far the most common reason why tox 4 fails for Zope repositories.
https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/

**Comment by jamadden** [comment]
`[]` is the original way to spell "substitute with tox positional args", the equivalent of `{posargs}`, IIRC.

**Comment by jugmac00** [comment]
@gaborbernat Will you support this old way or should we replace it with `{posargs}`?

/em looking forward for the next application of https://github.com/asottile/all-repos - mass PRs :-D

**Comment by gaborbernat** [comment]
Will be fixed part of https://github.com/tox-dev/tox/issues/1928

**Comment by jugmac00** [comment]
Thanks! I completely missed that issue - I was searching for `tox4` in the issue list, and missed the `tox 4` ones :-/

This also means - no 143 pull requests to swap out the old for the new syntax.

Lucky you, if it would have been October, I'd requested 143/4 shirts from you (hacktoberfest) :-D
