### ISSUE TITLE
Tox-3.24: Python2 support broken

### ISSUE THREAD

**Issue by KonstantinShemyak** [tox-dev/tox#1967]
`setuptools` [dropped support for Python2 since version 45.0.0](https://github.com/pypa/setuptools/blob/v45.0.0/CHANGES.rst#v4500). At present, version of `setuptools` is [unbounded from above](https://github.com/tox-dev/tox/blob/543954b430bbc47869326267cc0a16dc0dcbd3d2/pyproject.toml#L3). When a later version is present, fresh install of `tox` fails to self-test:

```
$ tox -e py27
[...]
ERROR: invocation failed (exit code 1), logfile: /path/to/tox/.tox/py27/log/py27-7.log
[...]
================================================================== log start ==================================================================
Looking in indexes: https://pypi.python.org/simple
Processing ./.tox/.tmp/package/1/tox-3.23.1.dev2+g543954b.d20210310.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Users/konstantinshemyak/src/other/tox/.tox/py27/bin/python /Users/konstantinshemyak/src/other/tox/.tox/py27/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/4j/gxtcg7_j4mj7_j52f3glc6dh0000gn/T/pip-build-env-UQM0Qe/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple -- 'setuptools >= 40.0.4' 'setuptools_scm >= 2.0.0, <6' 'wheel >= 0.29.0'
       cwd: None
  Complete output (19 lines):
  Looking in indexes: https://pypi.python.org/simple
  Collecting setuptools>=40.0.4
    Using cached https://pypi.python.org/simple/%2Bf/818/1c4625cd58fa7/setuptools-53.1.0.tar.gz (2.1 MB)
      ERROR: Command errored out with exit status 1:
       command: /Users/konstantinshemyak/src/other/tox/.tox/py27/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4j/gxtcg7_j4mj7_j52f3glc6dh0000gn/T/pip-install-BUO3xA/setuptools/setup.py'"'"'; __file__='"'"'/private/var/folders/4j/gxtcg7_j4mj7_j52f3glc6dh0000gn/T/pip-install-BUO3xA/setuptools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4j/gxtcg7_j4mj7_j52f3glc6dh0000gn/T/pip-pip-egg-info-Txhz3D
           cwd: /private/var/folders/4j/gxtcg7_j4mj7_j52f3glc6dh0000gn/T/pip-install-BUO3xA/setuptools/
      Complete output (10 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "pkg_resources/__init__.py", line 1367
          raise SyntaxError(e) from e
                                  ^
      SyntaxError: invalid syntax
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/konstantinshemyak/src/other/tox/.tox/py27/bin/python /Users/konstantinshemyak/src/other/tox/.tox/py27/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/4j/gxtcg7_j4mj7_j52f3glc6dh0000gn/T/pip-build-env-UQM0Qe/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple -- 'setuptools >= 40.0.4' 'setuptools_scm >= 2.0.0, <6' 'wheel >= 0.29.0' Check the logs for full command output.

=================================================================== log end ===================================================================

```

**Comment by gaborbernat** [comment]
The issue here is not on the tox side. Your pip installer should understand the setuptools wheel tags+metadata and not install newer versions. What pip are you using?

**Comment by KonstantinShemyak** [comment]
@gaborbernat Thank you for so quick and correct diagnose of what turned out to be my local problem! (Pip repository was just not providing proper tags.)
