### ISSUE TITLE
tox -e deps does not work on Python 3.7 for tox version 3.23.0

### ISSUE THREAD

**Issue by Cheukting** [tox-dev/tox#1977]
When submitting a bug make sure you can reproduce it via ``tox -rvv`` and attach the output of that to the bug. Ideally, you should also submit a project that allows easily reproducing the bug. Thanks!

Python version: 3.7
tox version: 3.23.0
pip version: 21.0.1

Encounter the following when running: `deps run-test: commands[0] | pip-compile --quiet --upgrade --rebuild --output-file=requirements.txt requirements.in`

```
Traceback (most recent call last):
  File "/home/runner/work/terminusdb-client-python/terminusdb-client-python/.tox/deps/lib/python3.7/site-packages/pip/_vendor/pep517/meta.py", line 10, in <module>
    import importlib.metadata as imp_meta
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/terminusdb-client-python/terminusdb-client-python/.tox/deps/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/home/runner/work/terminusdb-client-python/terminusdb-client-python/.tox/deps/lib/python3.7/site-packages/piptools/scripts/compile.py", line 12, in <module>
    from pip._vendor.pep517 import meta
  File "/home/runner/work/terminusdb-client-python/terminusdb-client-python/.tox/deps/lib/python3.7/site-packages/pip/_vendor/pep517/meta.py", line 12, in <module>
    import importlib_metadata as imp_meta
ModuleNotFoundError: No module named 'importlib_metadata'
```

Guess it forget to install dependency importlib-metadata for Pyhton < 3.8

**Comment by jugmac00** [comment]
No problems with the pre-release version of `tox4` - just saying :-) Final release announced for probably begin of May.

This one is interesting...

```
Traceback (most recent call last):
  File "/home/runner/work/terminusdb-client-python/terminusdb-client-python/.tox/deps/lib/python3.7/site-packages/pip/_vendor/pep517/meta.py", line 10, in <module>
    import importlib.metadata as imp_meta
ModuleNotFoundError: No module named 'importlib.metadata'
```

The error seems to get triggered in the `pip` package itself - I am super curious why this would be a tox issue.

Though, `pip-compile` without `tox` works also for Python 3.7.

**Comment by Cheukting** [comment]
Yes it maybe... I still have no idea why my pipeline got broken recently so
I suspect Rox cause it has a new release but it seems I have the same
problem with the previous version so my bad. Please feel free to close the
issue.

**Comment by Cheukting** [comment]
This maybe it: https://github.com/jazzband/pip-tools/releases/tag/6.0.1 it's a patch from pip-tools, sorry for blaming tox. I love tox

**Comment by jugmac00** [comment]
Thanks for the heads-up!
