### ISSUE TITLE
tox4: constraints files via http(s) do not work

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2001]
## repro / contrived / minimal example

```
[testenv]
deps = 
    Zope
    -c https://zopefoundation.github.io/Zope/releases/4.5.5/requirements-full.txt
```

```
❯ tox4dev -e py38 -rvv
ROOT: 192 D setup logging to DEBUG on pid 13359 [tox/report.py:222]
ROOT: 196 W remove tox env folder /home/jugmac00/Projects/RestrictedPython/.tox/4/py38 [tox/tox_env/api.py:254]
ROOT: 237 I find interpreter for spec PythonSpec(implementation=CPython, major=3, minor=8) [virtualenv/discovery/builtin.py:62]
ROOT: 237 D discover exe for PythonInfo(spec=CPython3.8.8.final.0-64, exe=/home/jugmac00/Projects/tox/bleeding/bin/python, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) in /usr [virtualenv/discovery/py_info.py:372]
ROOT: 238 D filesystem is case-sensitive [virtualenv/info.py:28]
ROOT: 240 D Attempting to acquire lock 140257061046064 on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:270]
ROOT: 240 D Lock 140257061046064 acquired on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:274]
ROOT: 240 D got python info of /usr/bin/python3.8 from /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 241 D Attempting to release lock 140257061046064 on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:315]
ROOT: 241 D Lock 140257061046064 released on /home/jugmac00/.local/share/virtualenv/py_info/1/df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6.lock [filelock.py:318]
ROOT: 241 I proposed PythonInfo(spec=CPython3.8.8.final.0-64, system=/usr/bin/python3.8, exe=/home/jugmac00/Projects/tox/bleeding/bin/python, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:69]
ROOT: 242 D accepted PythonInfo(spec=CPython3.8.8.final.0-64, system=/usr/bin/python3.8, exe=/home/jugmac00/Projects/tox/bleeding/bin/python, platform=linux, version='3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:71]
ROOT: 292 I create virtual environment via CPython3Posix(dest=/home/jugmac00/Projects/RestrictedPython/.tox/4/py38, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:52]
ROOT: 292 D create folder /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin [virtualenv/util/path/_sync.py:25]
ROOT: 292 D create folder /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages [virtualenv/util/path/_sync.py:25]
ROOT: 293 D write /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 293 D     home = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     version_info = 3.8.8.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     virtualenv = 20.4.3 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D     base-executable = /usr/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 293 D symlink /usr/bin/python3.8 to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/python [virtualenv/util/path/_sync.py:44]
ROOT: 294 D create virtualenv import hook file /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:95]
ROOT: 294 D create /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:98]
ROOT: 295 D ============================== target debug ============================== [virtualenv/run/session.py:54]
ROOT: 295 D debug via /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/python /home/jugmac00/Projects/tox/bleeding/lib/python3.8/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:224]
ROOT: 295 D {
  "sys": {
    "executable": "/home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/python",
    "_base_executable": "/home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/python",
    "prefix": "/home/jugmac00/Projects/RestrictedPython/.tox/4/py38",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/jugmac00/Projects/RestrictedPython/.tox/4/py38",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python38.zip",
      "/usr/lib/python3.8",
      "/usr/lib/python3.8/lib-dynload",
      "/home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.8.8 (default, Feb 20 2021, 21:09:14) \n[GCC 7.5.0]",
  "makefile_filename": "/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.8/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.8/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.8/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.8/json/__init__.py'>"
} [virtualenv/run/session.py:55]
ROOT: 380 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jugmac00/.local/share/virtualenv) [virtualenv/run/session.py:59]
py38: 384 D got embed update of distribution pip from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/pip.json [virtualenv/app_data/via_disk_folder.py:135]
py38: 384 D got embed update of distribution setuptools from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/setuptools.json [virtualenv/app_data/via_disk_folder.py:135]
py38: 385 D got embed update of distribution wheel from /home/jugmac00/.local/share/virtualenv/wheel/3.8/embed/1/wheel.json [virtualenv/app_data/via_disk_folder.py:135]
py38: 390 D using periodically updated wheel /home/jugmac00/.local/share/virtualenv/wheel/house/setuptools-54.0.0-py3-none-any.whl [virtualenv/seed/wheels/periodic_update.py:53]
py38: 390 D install pip from wheel /home/jugmac00/Projects/tox/bleeding/lib/python3.8/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py38: 390 D install wheel from wheel /home/jugmac00/Projects/tox/bleeding/lib/python3.8/site-packages/virtualenv/seed/wheels/embed/wheel-0.36.2-py2.py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py38: 391 D install setuptools from wheel /home/jugmac00/.local/share/virtualenv/wheel/house/setuptools-54.0.0-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py38: 391 D Attempting to acquire lock 140257059143984 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any.lock [filelock.py:270]
py38: 392 D Attempting to acquire lock 140257059143744 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:270]
py38: 392 D Lock 140257059143984 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any.lock [filelock.py:274]
py38: 392 D Attempting to acquire lock 140257059144032 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:270]
py38: 392 D Lock 140257059143744 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:274]
py38: 393 D Attempting to release lock 140257059143984 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any.lock [filelock.py:315]
py38: 393 D Lock 140257059144032 acquired on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:274]
py38: 393 D Lock 140257059143984 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any.lock [filelock.py:318]
py38: 393 D Attempting to release lock 140257059144032 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:315]
py38: 393 D Attempting to release lock 140257059143744 on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:315]
py38: 394 D Lock 140257059144032 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any.lock [filelock.py:318]
py38: 394 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any/setuptools-54.0.0.dist-info to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/setuptools-54.0.0.dist-info [virtualenv/util/path/_sync.py:52]
py38: 394 D Lock 140257059143744 released on /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any.lock [filelock.py:318]
py38: 395 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip-21.0.1.virtualenv to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/pip-21.0.1.virtualenv [virtualenv/util/path/_sync.py:52]
py38: 395 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel-0.36.2.virtualenv to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/wheel-0.36.2.virtualenv [virtualenv/util/path/_sync.py:52]
py38: 397 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip-21.0.1.dist-info to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/pip-21.0.1.dist-info [virtualenv/util/path/_sync.py:52]
py38: 397 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel-0.36.2.dist-info to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/wheel-0.36.2.dist-info [virtualenv/util/path/_sync.py:52]
py38: 402 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.0.1-py3-none-any/pip to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/pip [virtualenv/util/path/_sync.py:52]
py38: 402 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.2-py2.py3-none-any/wheel to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/wheel [virtualenv/util/path/_sync.py:52]
py38: 403 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any/pkg_resources to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/pkg_resources [virtualenv/util/path/_sync.py:52]
py38: 413 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/wheel3.8 to 775 [distlib/util.py:566]
py38: 413 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/wheel-3.8 to 775 [distlib/util.py:566]
py38: 414 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/wheel3 to 775 [distlib/util.py:566]
py38: 415 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/wheel to 775 [distlib/util.py:566]
py38: 415 D generated console scripts wheel-3.8 wheel3 wheel wheel3.8 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
py38: 417 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any/distutils-precedence.pth to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:52]
py38: 418 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any/_distutils_hack to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:52]
py38: 419 D copy /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any/setuptools-54.0.0.virtualenv to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/setuptools-54.0.0.virtualenv [virtualenv/util/path/_sync.py:52]
py38: 420 D copy directory /home/jugmac00/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-54.0.0-py3-none-any/setuptools to /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/lib/python3.8/site-packages/setuptools [virtualenv/util/path/_sync.py:52]
py38: 468 D generated console scripts  [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
py38: 501 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/pip3.8 to 775 [distlib/util.py:566]
py38: 501 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/pip to 775 [distlib/util.py:566]
py38: 501 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/pip-3.8 to 775 [distlib/util.py:566]
py38: 501 D changing mode of /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/bin/pip3 to 775 [distlib/util.py:566]
py38: 502 D generated console scripts pip-3.8 pip pip3.8 pip3 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
ROOT: 502 I add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [virtualenv/run/session.py:64]
ROOT: 504 D write /home/jugmac00/Projects/RestrictedPython/.tox/4/py38/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 504 D     home = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 504 D     implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 504 D     version_info = 3.8.8.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 504 D     virtualenv = 20.4.3 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 505 D     include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 505 D     base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 505 D     base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
ROOT: 505 D     base-executable = /usr/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 519 E internal error [tox/session/cmd/run/single.py:54]
Traceback (most recent call last):
  File "/home/jugmac00/Projects/tox/src/tox/session/cmd/run/single.py", line 42, in _evaluate
    tox_env.setup(recreate=recreate)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/api.py", line 188, in setup
    self._setup_env()
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/runner.py", line 122, in _setup_env
    self.installer.install(requirements_file, PythonRun.__name__, "deps")
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/pip/pip_install.py", line 84, in install
    self._install_requirement_file(arguments, section, of_type)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/pip/pip_install.py", line 92, in _install_requirement_file
    result = arguments.validate_and_expand()
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/pip/req_file.py", line 171, in validate_and_expand
    self._expand_flag(ini_dir, line, result)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/pip/req_file.py", line 276, in _expand_flag
    raise ValueError(f"requirement file path {str(path)!r} does not exist")
ValueError: requirement file path '/home/jugmac00/Projects/RestrictedPython/https:/zopefoundation.github.io/Zope/releases/4.5.5/requirements-full.txt' does not exist
  py38: FAIL code 2 (0.32 seconds)
  evaluation failed :( (0.37 seconds)
```

I get possible the same errors no matter whether the constraints file is listed as deps or in a requirements.txt file which is read via `-rrequirements.txt` from deps.

**Comment by gaborbernat** [comment]
This will work once my requirements parse rewrite lands later this week https://www.github.com/gaborbernat/tox/tree/1929/src%2Ftox%2Ftox_env%2Fpython%2Fpip%2Freq%2Ffile.py

**Comment by gaborbernat** [comment]
This should work now on master.

**Comment by jugmac00** [comment]
Works like a charm on `s/master/rewrite/`.
