### ISSUE TITLE
[tox4] combination of `config` and `-r` throws KeyError/AttributeError

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2037]
`tox4dev` is a symlink to an editable installation of the git repo

used repository: tox

```
❯ tox4dev config -r
[testenv:fix]
type = VirtualEnvRunner
set_env =
  COVERAGE_FILE=/home/jugmac00/Projects/tox/.tox/4/.coverage.fix
  COVERAGE_PROCESS_START=/home/jugmac00/Projects/tox/setup.cfg
  PIP_DISABLE_PIP_VERSION_CHECK=1
base = testenv
runner = virtualenv
description = format the code base to adhere to our styles, and complain about what we cannot do automatically
depends = 
env_name = fix
env_dir = /home/jugmac00/Projects/tox/.tox/4/fix
env_tmp_dir = /home/jugmac00/Projects/tox/.tox/4/fix/tmp
platform = 
pass_env =
  CURL_CA_BUNDLE
  LANG
  LANGUAGE
  LD_LIBRARY_PATH
  PIP_*
  PROGRAMDATA
  PYTEST_*
  REQUESTS_CA_BUNDLE
  SSL_CERT_FILE
  TERM
  TMPDIR
  VIRTUALENV_*
  http_proxy
  https_proxy
  no_proxy
parallel_show_output = False
recreate = False
commands_pre = 
commands =
  pre-commit run --all-files --show-diff-on-failure --color=always
  python -c 'print(r"hint: run /home/jugmac00/Projects/tox/.tox/4/fix/bin/pre-commit install to add checks as pre-commit hook")'
commands_post = 
change_dir = /home/jugmac00/Projects/tox
ignore_errors = False
ignore_outcome = False
skip_install = True
package = skip
base_python = python3.9
env_site_packages_dir = /home/jugmac00/Projects/tox/.tox/4/fix/lib/python3.9/site-packages
env_bin_dir = /home/jugmac00/Projects/tox/.tox/4/fix/bin
env_python = /home/jugmac00/Projects/tox/.tox/4/fix/bin/python
deps = pre-commit>=2.2
system_site_packages = False
always_copy = False
download = False
Traceback (most recent call last):
  File "/home/jugmac00/Projects/tox/src/tox/config/main.py", line 106, in get_env
    return self._env_to_set[item]
KeyError: 'py310'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugmac00/bin/tox4dev", line 33, in <module>
    sys.exit(load_entry_point('tox', 'console_scripts', 'tox4')())
  File "/home/jugmac00/Projects/tox/src/tox/run.py", line 18, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/home/jugmac00/Projects/tox/src/tox/run.py", line 43, in main
    result = handler(state)
  File "/home/jugmac00/Projects/tox/src/tox/session/cmd/show_config.py", line 54, in show_config
    run_env = state.tox_env(name)
  File "/home/jugmac00/Projects/tox/src/tox/session/state.py", line 64, in tox_env
    self.conf.get_env(name)  # the lookup here will trigger register_config_set, which will build it
  File "/home/jugmac00/Projects/tox/src/tox/config/main.py", line 116, in get_env
    self.register_config_set(item, env)
  File "/home/jugmac00/Projects/tox/src/tox/session/state.py", line 76, in register_config_set
    self._build_run_env(config_set)
  File "/home/jugmac00/Projects/tox/src/tox/session/state.py", line 93, in _build_run_env
    self._build_package_env(env)
  File "/home/jugmac00/Projects/tox/src/tox/session/state.py", line 98, in _build_package_env
    package_tox_env = self._get_package_env(core_type, name)
  File "/home/jugmac00/Projects/tox/src/tox/session/state.py", line 116, in _get_package_env
    pkg_tox_env = package_type(pkg_conf, self.conf.core, self.options, journal, self.log_handler)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/virtual_env/package/api.py", line 80, in __init__
    VirtualEnv.__init__(self, conf, core, options, journal, log_handler)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/virtual_env/api.py", line 35, in __init__
    super().__init__(conf, core, options, journal, log_handler)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/python/api.py", line 53, in __init__
    super().__init__(conf, core, options, journal, log_handler)
  File "/home/jugmac00/Projects/tox/src/tox/tox_env/package.py", line 37, in __init__
    self.recreate_package = options.recreate and not options.no_recreate_pkg
AttributeError: 'Parsed' object has no attribute 'no_recreate_pkg'

```

**Comment by jugmac00** [comment]
@gaborbernat Could you give me a hint what's the proposed solution? Do not allow/evaluate `-r` for `tox config`?

**Comment by gaborbernat** [comment]
I think it makes sense to allow it because it influences the config value recreate :thinking: so I think the solution is to add ``--no-recreate-pkg`` to the config env var :+1:
