### ISSUE TITLE
Allow specification of a single factor in  a `[testenv:...]` block

### ISSUE THREAD

**Issue by Cadair** [tox-dev/tox#2062]
I have a set of factors which can be combined, the top of my `tox.ini` files looks like this:

```
[tox]
envlist =
    py{37,38,39}{,-devdeps,-online,-figure,-conda}
    build_docs
    codestyle
```

For the `-devdeps` factor I want to enable `pip_pre=true` (also add a custom index url by overriding `install_command`, what I want to be able to do is:

```
[testenv:-devdeps]
pip_pre = true
```
But this doesn't work, the only thing I have found which does work, is this little monstrosity:

```
[testenv:py{37,38,39}{,-figure,-online}-devdeps{,-online,-figure}]
pip_pre = true
```

Am I missing something or is this just not supported?

**Comment by gaborbernat** [comment]
That's not supported today, though you could instead do:

```
[testenv]
pip_pre = 
   false
   devdeps: true
```

**Comment by Cadair** [comment]
Thanks for the advice!

That didn't actually work, it gave me:
<details>

```
.tox recreate: /home/stuart/Git/ndcube/.tox/.tox
.tox installdeps: setuptools >= 30.3.0, pip >= 19.3.1, tox-pypi-filter >= 0.12, tox >= 3.23.1
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/__main__.py", line 4, in <module>
    tox.cmdline()
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/session/__init__.py", line 65, in main
    config = load_config(args)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/session/__init__.py", line 81, in load_config
    config = parseconfig(args)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 282, in parseconfig
    ParseIni(config, config_file, content)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1293, in __init__
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: py37-devdeps failed with ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False' at Traceback (most recent call last):
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1269, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1445, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1734, in getbool
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False'

py38-devdeps failed with ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False' at Traceback (most recent call last):
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1269, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1445, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1734, in getbool
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False'

py39-devdeps failed with ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False' at Traceback (most recent call last):
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1269, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1445, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1734, in getbool
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False'

py39-figure-devdeps failed with ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False' at Traceback (most recent call last):
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1269, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1445, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/home/stuart/Git/ndcube/.tox/.tox/lib/python3.9/site-packages/tox/config/__init__.py", line 1734, in getbool
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: pip_pre: boolean value 'false\ntrue' needs to be 'True' or 'False'
```

</details>

What did seem to do the trick was:
```
install_command = 
  devdeps: python -m pip install --pre --extra-index-url=https://pkgs.dev.azure.com/astropy-project/astropy/_packaging/nightly/pypi/simple/ {opts} {packages}
```

**Comment by gaborbernat** [comment]
Ah, this field doesn't support conditional factors yet, in this case you'll need to wait for tox 4 that should handle this. Note though you could achieve the same via setenv that should support conditional factorials.

**Comment by gaborbernat** [comment]
support for this has been added in tox 4.
