### ISSUE TITLE
Parallel build may cause BadZipFile

### ISSUE THREAD

**Issue by ziima** [tox-dev/tox#2067]
Since we started using `parallel` runs with tox in Gitlab CI, we sometimes encounter an `BadZipFile` error. It's not entirely reproducible, but it occurs from time to time with different frequencies on different projects. We have only been able to reproduce it on CI runners. We weren't able to mitigate the issue and it seems there is some kind of race condition.

### Command ###
`tox -rvv --parallel all --notest`

Note: we build environments in parallel and run tests in sequence.

### Output ###
```
ERROR: invocation failed (exit code 1), logfile: /builds/fred/webwhois/.tox/py36-django21/log/py36-django21-0.log
using tox.ini: /builds/fred/webwhois/tox.ini (pid 231)
using tox-3.23.1 from /usr/local/lib/python3.6/site-packages/tox/__init__.py (pid 231)
using package '/builds/fred/webwhois/.tox/.tmp/package/1/fred-webwhois-1.19.0.zip', skipping 'sdist' activity 
package 10/fred-webwhois-1.19.0.zip links to 1/fred-webwhois-1.19.0.zip (/builds/fred/webwhois/.tox/.tmp/package)
py36-django21 uses /usr/local/bin/python
py36-django21 start: getenv /builds/fred/webwhois/.tox/py36-django21
py36-django21 cannot reuse: -r flag
py36-django21 create: /builds/fred/webwhois/.tox/py36-django21
setting PATH=/builds/fred/webwhois/.tox/py36-django21/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[956] /builds/fred/webwhois/.tox$ /usr/local/bin/python -m virtualenv --no-download --python /usr/local/bin/python py36-django21
created virtual environment CPython3.6.13.final.0-64 in 301ms
  creator CPython3Posix(dest=/builds/fred/webwhois/.tox/py36-django21, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.1.1, setuptools==56.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
py36-django21 installdeps: coverage, django==2.1.*
setting PATH=/builds/fred/webwhois/.tox/py36-django21/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[1002] /builds/fred/webwhois$ /builds/fred/webwhois/.tox/py36-django21/bin/pip install -cconstraints.txt coverage 'django==2.1.*'
Looking in indexes: https://pypi.nic.cz/cznic/public
Collecting coverage
  Using cached https://pypi.nic.cz/root/pypi/%2Bf/411/79b8a845742d1/coverage-5.5-cp36-cp36m-manylinux2010_x86_64.whl (240 kB)
Collecting django==2.1.*
  Downloading https://pypi.nic.cz/root/pypi/%2Bf/485/22428f4a285cf/Django-2.1.15-py3-none-any.whl (7.3 MB)
Collecting pytz
  Using cached https://pypi.nic.cz/root/pypi/%2Bf/eb1/0ce3e7736052e/pytz-2021.1-py2.py3-none-any.whl (510 kB)
Installing collected packages: pytz, django, coverage
Successfully installed coverage-5.5 django-2.1.15 pytz-2021.1
py36-django21 finish: getenv /builds/fred/webwhois/.tox/py36-django21 after 12.03 seconds
py36-django21 start: installpkg /builds/fred/webwhois/.tox/.tmp/package/10/fred-webwhois-1.19.0.zip
py36-django21 inst: /builds/fred/webwhois/.tox/.tmp/package/10/fred-webwhois-1.19.0.zip
write config to /builds/fred/webwhois/.tox/py36-django21/.tox-config1 as '0a28da31c8385d205b5bca5005823c62fd095fdad96b5121c7ef98fbaacc6e71 /usr/local/bin/python\n3.23.1 0 0 0\n00000000000000000000000000000000 coverage\n00000000000000000000000000000000 django==2.1.*'
setting PATH=/builds/fred/webwhois/.tox/py36-django21/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[1091] /builds/fred/webwhois$ /builds/fred/webwhois/.tox/py36-django21/bin/pip install -cconstraints.txt --exists-action w '/builds/fred/webwhois/.tox/.tmp/package/10/fred-webwhois-1.19.0.zip[test]'
Looking in indexes: https://pypi.nic.cz/cznic/public
Processing ./.tox/.tmp/package/10/fred-webwhois-1.19.0.zip
Requirement already satisfied: django<3.2.99,>=1.11 in ./.tox/py36-django21/lib/python3.6/site-packages (from fred-webwhois==1.19.0) (2.1.15)
Collecting django-app-settings
  Using cached https://pypi.nic.cz/root/pypi/%2Bf/d27/0dba8383d56bd/django_app_settings-0.4.0-py2.py3-none-any.whl (14 kB)
Collecting idna
  Using cached https://pypi.nic.cz/root/pypi/%2Bf/156/a6814fb5ac1fc/idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting omniORB~=4.2.2
  Using cached https://pypi.nic.cz/cznic/public/%2Bf/a5b/2723a512a662a/omniORB-4.2.3-cp36-cp36m-linux_x86_64.whl (1.8 MB)
Collecting fred-idl~=2.36.0
  Using cached https://pypi.nic.cz/cznic/public/%2Bf/ecc/5e2d551e0655b/fred_idl-2.36.1-py3-none-any.whl (180 kB)
Collecting fred-pyfco~=1.15
  Using cached https://pypi.nic.cz/cznic/public/%2Bf/129/e2f7bbf0ed294/fred-pyfco-1.16.1.tar.gz (37 kB)
Collecting fred-pylogger<3.0,>=1.16
  Using cached https://pypi.nic.cz/cznic/public/%2Bf/1d5/55283998d4ee4/fred-pylogger-2.0.0.tar.gz (29 kB)
Collecting testfixtures
  Downloading https://pypi.nic.cz/root/pypi/%2Bf/334/497d26344e8c0/testfixtures-6.3.0-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: pytz in ./.tox/py36-django21/lib/python3.6/site-packages (from django<3.2.99,>=1.11->fred-webwhois==1.19.0) (2021.1)
Collecting six
  Using cached https://pypi.nic.cz/root/pypi/%2Bf/8ab/b2f1d86890a2d/six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: fred-webwhois, fred-pyfco, fred-pylogger
  Building wheel for fred-webwhois (setup.py): started
  Building wheel for fred-webwhois (setup.py): finished with status 'done'
  Created wheel for fred-webwhois: filename=fred_webwhois-1.19.0-py3-none-any.whl size=160614 sha256=5e4ff059a58bfad523d0e9be121d6d161e3cd63c19d35863621ee3ea056ade30
  Stored in directory: /builds/fred/webwhois/.cache/pip/wheels/88/2c/40/619a32aa261103246efc8ecb5b1bff459b738b1390538be674
  Building wheel for fred-pyfco (setup.py): started
  Building wheel for fred-pyfco (setup.py): finished with status 'done'
  Created wheel for fred-pyfco: filename=fred_pyfco-1.16.1-py3-none-any.whl size=44046 sha256=c5130938fe2c300c48d345d3797eabe608f6ba89ae7ad7479fc4ae10a5691a49
  Stored in directory: /builds/fred/webwhois/.cache/pip/wheels/e1/c6/dd/58cc645d479d8631148be88e624e5e54b86e1f309f64fc8875
  Building wheel for fred-pylogger (setup.py): started
  Building wheel for fred-pylogger (setup.py): finished with status 'done'
  Created wheel for fred-pylogger: filename=fred_pylogger-2.0.0-py3-none-any.whl size=31755 sha256=0e94de04d10c86995fcb62a3eca36cbf5e11da2ee4cf294a4881b74e2d284f4f
  Stored in directory: /builds/fred/webwhois/.cache/pip/wheels/88/72/fb/c180ba74ae3365f9fdc66885d800ab359b2c7d17e3fa3a9dba
ERROR: Exception:
Traceback (most recent call last):
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 350, in run
    global_options=[],
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/wheel_builder.py", line 337, in build
    req, cache_dir, verify, build_options, global_options
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/wheel_builder.py", line 228, in _build_one
    _verify_one(req, wheel_path)
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/wheel_builder.py", line 177, in _verify_one
    dist = get_wheel_distribution(wheel_path, canonical_name)
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/metadata/__init__.py", line 43, in get_wheel_distribution
    return Distribution.from_wheel(wheel_path, canonical_name)
  File "/builds/fred/webwhois/.tox/py36-django21/lib/python3.6/site-packages/pip/_internal/metadata/pkg_resources.py", line 23, in from_wheel
    with zipfile.ZipFile(path, allowZip64=True) as zf:
  File "/usr/local/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
ERROR: invocation failed (exit code 2)
py36-django21 finish: installpkg /builds/fred/webwhois/.tox/.tmp/package/10/fred-webwhois-1.19.0.zip after 8.85 seconds
cleanup /builds/fred/webwhois/.tox/.tmp/package/10/fred-webwhois-1.19.0.zip
```

**Comment by gaborbernat** [comment]
This is a pip bug, please report it under https://github.com/pypa/pip; thanks!
