### ISSUE TITLE
Tox fails to install a dependency from a github repo

### ISSUE THREAD

**Issue by antoinecollet5** [tox-dev/tox#2283]
I struggle to make tox works with a python package that depends on another one ([pyPCGA](https://github.com/jonghyunharrylee/pyPCGA)) that is not on PyPi but only on a github repo.

When I create my package locally and then install it with pip, pyPCGA is cloned and installed (as well as its dependencies) without any trouble. However, it seems that I do something wrong with tox.

Here is my requirements_dev.txt
```
pip
bump2version
cookiecutter>=1.4.0
wheel

twine==1.14.0
pytest
pytest-runner
pytest-cov
pytest-cookies
flake8
coverage
flake8-html


sphinx>=2 # jupyter_sphinx requires sphinx>=2
nbsphinx
sphinx-rtd-theme==0.5.0rc2
sphinxcontrib-blockdiag
jupyter_sphinx>=0.3.2
sphinx-jsonschema>=1.15
pygments==2.6.1

pandas>=1.3
numpy>=1.2
pyvista>=0.32
vtk>=9.1
xmltodict>=0.12.0
regex>=2021.11.10
scipy>=1.6.2
pyesmda>=0.1.0
pydantic>=1.8.2
pyesmda>=0.1.0
pyPCGA @ git+https://git@github.com/jonghyunharrylee/pyPCGA.git
```
Here is my tox.ini

```
[tox]
envlist = clean, py37, py38, docs, flake8, report
skipsdist = true

	
[testenv:py38-docs]
changedir=docs
deps=-rrequirements_dev.txt
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html


[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 hytec_python_auto_hm tests
ignore_outcome = true



[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    python -m pip install --upgrade pip
    pytest --cov=hytec_python_auto_hm --cov-append --cov-report=term-missing --cov-config=.coveragerc --color=yes

depends =
    {py37,py38}: clean
    report: py37,py38

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report -i
    coverage html -i
    coverage xml -i


[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase
```

Here is the error raised by tox when trying to install dependencies

```
==================================================================================================== log start ====================================================================================================
Collecting pyPCGA@ git+https://git@github.com/jonghyunharrylee/pyPCGA.git
  Cloning https://****@github.com/jonghyunharrylee/pyPCGA.git to /tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f
  Running command git clone --filter=blob:none -q 'https://****@github.com/jonghyunharrylee/pyPCGA.git' /tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f
  Resolved https://****@github.com/jonghyunharrylee/pyPCGA.git to commit 8294452a1c67b6cdc0c36d492c7bb2a769f76fb3
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/acollet/workspace/hytec_python_auto_hm/.tox/docs/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0djw58_7
       cwd: /tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f/
  Complete output (9 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f/setup.py", line 8, in <module>
      from pyPCGA import __name__, __author__
    File "/tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f/pyPCGA/__init__.py", line 8, in <module>
      from .pcga import PCGA
    File "/tmp/pip-install-fxf55wbd/pypcga_d5a92564eda646a3ac3d29772a0a533f/pyPCGA/pcga.py", line 3, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
WARNING: Discarding git+https://****@github.com/jonghyunharrylee/pyPCGA.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Requirement already satisfied: pip in ./.tox/docs/lib/python3.8/site-packages (from -r /home/acollet/workspace/hytec_python_auto_hm/requirements_dev.txt (line 1)) (21.3.1)
Collecting bump2version
  Using cached bump2version-1.0.1-py2.py3-none-any.whl (22 kB)
Collecting cookiecutter>=1.4.0
```

Thank you in advance for your help.

**Comment by jugmac00** [comment]
@antoinecollet5 Thank you for the very detailed bug report, so I was able to reproduce the problem.

Unfortunately, there is nothing to help from the `tox` side, as the problem is within your dependency, ie `pyPCGA` is not properly packaged.

I even cannot install it directly from Github:
```
$ pip install git+https://****@github.com/jonghyunharrylee/pyPCGA.git
Collecting git+https://****@github.com/jonghyunharrylee/pyPCGA.git
  Cloning https://****@github.com/jonghyunharrylee/pyPCGA.git to /tmp/pip-req-build-ko5042bo
  Running command git clone --filter=blob:none -q 'https://****@github.com/jonghyunharrylee/pyPCGA.git' /tmp/pip-req-build-ko5042bo
  Resolved https://****@github.com/jonghyunharrylee/pyPCGA.git to commit 8294452a1c67b6cdc0c36d492c7bb2a769f76fb3
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/test/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ko5042bo/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ko5042bo/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x9bt3f13
       cwd: /tmp/pip-req-build-ko5042bo/
  Complete output (9 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-ko5042bo/setup.py", line 8, in <module>
      from pyPCGA import __name__, __author__
    File "/tmp/pip-req-build-ko5042bo/pyPCGA/__init__.py", line 8, in <module>
      from .pcga import PCGA
    File "/tmp/pip-req-build-ko5042bo/pyPCGA/pcga.py", line 3, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
WARNING: Discarding git+https://****@github.com/jonghyunharrylee/pyPCGA.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The problem is clearly described in above (and your traceback).

When installing `pyPCGA` `setup.py` is performed - `setup.py` imports from from the package, ie `from pyPCGA import __name__, __author__`(which is never a good idea).

This triggers `__init__.py` and there is another internal import, and in that file the third party import `import numpy as np` is tried - but as even the package is not installed, also certainly also the dependencies are not installed and this fails.

So, again, this is not a `tox` issue, the dependency `pyPCGA` is not properly set up/packaged.

You mentioned that it works locally - this may be the case as you have installed `numpy` in advance.

My recommendation is to create an issue upstream, ie in `pyPCGA` and get the problem fixed there.

**Comment by jugmac00** [comment]
Alternatively, if the maintainer does not respond, you could e.g. create a fork and remove the problematic line https://github.com/jonghyunharrylee/pyPCGA/blob/8294452a1c67b6cdc0c36d492c7bb2a769f76fb3/setup.py#L8  (and then hardcode the values in https://github.com/jonghyunharrylee/pyPCGA/blob/8294452a1c67b6cdc0c36d492c7bb2a769f76fb3/setup.py#L14 and https://github.com/jonghyunharrylee/pyPCGA/blob/8294452a1c67b6cdc0c36d492c7bb2a769f76fb3/setup.py#L17
