### ISSUE TITLE
Substitution does not happen for loading env.vars from file in setenv

### ISSUE THREAD

**Issue by dalito** [tox-dev/tox#2285]
I had the following in `tox.ini`

```
# reading local configuration from config/.env
setenv = 
    ZZZ = {toxinidir}
    file|{toxinidir}/config/.env
```

and was expecting that `{toxinidir}` is replaced by the actual directory like it is for the environment variable `ZZZ`. 

However, no replacement occurs and since the file is [only loaded when the path is valid](https://github.com/tox-dev/tox/blob/717b7644a2376c0178ad293c41c76ff6631bdc46/src/tox/config/__init__.py#L1703), nothing is read from `config\.env`. Moreover, no error is raised to point out the problem in `tox.ini`. The loading-from-file option was added in #1668.

Details on my system: tox 3.24.4, Python 3.9.9-amd64, Win10Pro

**Comment by gaborbernat** [comment]
> However, no replacement occurs and since the file is [only loaded when the path is valid](https://github.com/tox-dev/tox/blob/717b7644a2376c0178ad293c41c76ff6631bdc46/src/tox/config/__init__.py#L1703), nothing is read from `config\.env`. Moreover, no error is raised to point out the problem in `tox.ini`. The loading-from-file option was added in #1668.

Can you check with tox 4, I think this has been fixed there?

**Comment by dalito** [comment]
The expansion happens with tox4!

However, there is another problem that tox4 tries to split `file|{toxinidir}/config/.env`at `=` which fails. Should I create a tox4 bug for this?

Traceback:
```
λ tox4 --version
4.0.0a9

λ tox4 -e docs                                                                                           
docs: internal error                                                                                     
Traceback (most recent call last):                                                                       
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\session\cmd\run\single.py", line 42, in _evaluate                                                                                             
    tox_env.setup()                                                                                      
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\api.py", line 214, in setup  
    self._setup_env()                                                                                    
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\runner.py", line 121, in _setup_env                                                                                            
    super()._setup_env()                                                                                 
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\api.py", line 156, in _setup_env                                                                                               
    self.ensure_python_env()                                                                             
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\api.py", line 160, in ensure_python_env                                                                                        
    conf = self.python_cache()                                                                           
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 74, in python_cache                                                                                  
    base = super().python_cache()                                                                        
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\api.py", line 194, in python_cache                                                                                             
    "version_info": list(self.base_python.version_info),                                                 
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\api.py", line 203, in base_python                                                                                              
    self._base_python = self._get_python(base_pythons)                                                   
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 130, in _get_python                                                                                  
    interpreter = self.creator.interpreter                                                               
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 122, in creator                                                                                      
    return self.session.creator                                                                          
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 103, in session                                                                                      
    env = self.virtualenv_env_vars()                                                                     
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 108, in virtualenv_env_vars                                                                          
    env = self._environment_variables.copy()                                                             
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\runner.py", line 190, in _environment_variables                                                                                       
    environment_variables = super()._environment_variables                                               
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\tox_env\api.py", line 298, in _environment_variables                                                                                          
    for key in set_env:                                                                                  
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\config\set_env.py", line 63, in __iter__                                                                                                      
    sub_raw = dict(self._extract_key_value(sub_line) for sub_line in expanded_line.splitlines() if sub_line)                                                                                                      
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\config\set_env.py", line 63, in <genexpr>                                                                                                     
    sub_raw = dict(self._extract_key_value(sub_line) for sub_line in expanded_line.splitlines() if sub_line)                                                                                                      
  File "C:\Users\dalito\.local\pipx\venvs\tox\lib\site-packages\tox\config\set_env.py", line 39, in _extract_key_value                                                                                            
    raise ValueError(f"invalid line {line!r} in set_env")                                                
ValueError: invalid line 'file|C:\\Users\\dalito\\MyProg_exp040\\mytool_Dev/config/.env' in set_env       
  docs: FAIL code 2 (0.00 seconds)                                                                       
  evaluation failed :( (0.06 seconds)                                                                    
```

**Comment by gaborbernat** [comment]
> [update]: It seems like you are aware of this. Support for `file|` is listed under `vNEXT (2021-11-17)` on [tox.wiki/en/rewrite/changelog.html](https://tox.wiki/en/rewrite/changelog.html)

Yeah, should be fixed, we just need to cut a new release (in the next month or so will happen).
