### ISSUE TITLE
[tox4] WARNING: Requirement 'xxx.tar.gz' looks like a filename, but the file does not exist

### ISSUE THREAD

**Issue by jugmac00** [tox-dev/tox#2300]
This works with tox3, but fails with tox4 (latest alpha).

## error message

```
WARNING: Requirement '/tmp/flask-reuploaded/.tox/4/.pkg/dist/Flask-Reuploaded-1.2.1.dev0.tar.gz' looks like a filename, but the file does not exist
Processing ./.tox/4/.pkg/dist/Flask-Reuploaded-1.2.1.dev0.tar.gz
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/flask-reuploaded/.tox/4/.pkg/dist/Flask-Reuploaded-1.2.1.dev0.tar.gz'
```

## reproduction

```
$ cd /tmp && git clone git@github.com:jugmac00/flask-reuploaded.git && cd flask-reuploaded && tox4 -rvv
```

## output

https://paste.ubuntu.com/p/fPFSjjDksd/

**Comment by gaborbernat** [comment]
```
❯ tox4 p
py310: OK ✔ in 3.21 seconds
coverage: OK ✔ in 7.39 seconds
py37: OK ✔ in 8.77 seconds
py38: OK ✔ in 9.24 seconds
docs: FAIL ✖ in 9.54 seconds
Traceback (most recent call last):
  File "/tmp/flask-reuploaded/.tox/4/docs/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/tmp/flask-reuploaded/.tox/4/docs/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/tmp/flask-reuploaded/.tox/4/docs/lib/python3.10/site-packages/sphinx/application.py", line 31, in <module>
    from sphinx.config import Config
  File "/tmp/flask-reuploaded/.tox/4/docs/lib/python3.10/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util import logging
  File "/tmp/flask-reuploaded/.tox/4/docs/lib/python3.10/site-packages/sphinx/util/__init__.py", line 41, in <module>
    from sphinx.util.typing import PathMatcher
  File "/tmp/flask-reuploaded/.tox/4/docs/lib/python3.10/site-packages/sphinx/util/typing.py", line 37, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/lib/python3.10/types.py)
docs: install_deps> python -I -m pip install -r docs/requirements.txt
docs: install_package_deps> python -I -m pip install 'Flask>=1.0.4' pytest pytest-cov
docs: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/flask-reuploaded/.tox/4/.pkg/dist/Flask-Reuploaded-1.2.1.dev0.tar.gz
docs: commands[0]> sphinx-build -b html docs _build/html
docs: exit 1 (0.07 seconds) /tmp/flask-reuploaded> sphinx-build -b html docs _build/html pid=1193885
py39: OK ✔ in 9.63 seconds
mypy: OK ✔ in 11.25 seconds
py36: OK ✔ in 12.96 seconds
  py36: OK (12.96=setup[12.18]+cmd[0.77] seconds)
  py37: OK (8.77=setup[8.35]+cmd[0.43] seconds)
  py38: OK (9.24=setup[8.83]+cmd[0.41] seconds)
  py39: OK (9.63=setup[9.22]+cmd[0.42] seconds)
  py310: OK (3.21=setup[2.89]+cmd[0.33] seconds)
  lint: OK (19.04=setup[7.14]+cmd[11.90] seconds)
  mypy: OK (11.25=setup[7.13]+cmd[4.12] seconds)
  coverage: OK (7.39=setup[6.80]+cmd[0.59] seconds)
  docs: FAIL code 1 (9.54=setup[9.47]+cmd[0.07] seconds)
  evaluation failed :( (19.08 seconds)
```

I'm failing to reproduce this :thinking:

**Comment by jugmac00** [comment]
This only happens after `tox4 -rvv`. Follow up runs a la `tox4` or `tox4 p` succeed.

**Comment by gaborbernat** [comment]
Yeah, discovered in the meantime 👌
