### ISSUE TITLE
JSONDecodeError with PyPy3.8 and isolated_build=True

### ISSUE THREAD

**Issue by zariiii9003** [tox-dev/tox#2332]
[Here is the project.](https://github.com/zariiii9003/python-can/tree/b5669ec67a54f87836edae9b571fc648bd304570)

The error occurs with Ubuntu, macOS and Windows, but only with PyPy3.8. CPython and PyPy3.7 works fine. But PyPy3.8 works fine without `isolated_build=True`.

<details open>
<summary>Traceback</summary>

```
  tox -e gh
  shell: /usr/bin/bash -e {0}
  env:
    PY_COLORS: 1
    pythonLocation: /opt/hostedtoolcache/PyPy/3.8.12/x64/bin
.package create: /home/runner/work/python-can/python-can/.tox/.package
.package installdeps: setuptools >= 40.8, wheel
Traceback (most recent call last):
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/session/__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/session/__init__.py", line 213, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)

  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/package/__init__.py", line 16, in tox_package
    session.package, session.dist = get_package(session)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/package/__init__.py", line 29, in get_package
    package = acquire_package(config, session)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/package/__init__.py", line 40, in acquire_package
    path = build_package(config, session)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/package/builder/__init__.py", line 9, in build_package
    return build(config, session)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/package/builder/isolated.py", line 37, in build
    build_requires = get_build_requires(build_info, package_venv, config.setupdir)
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/tox/package/builder/isolated.py", line 149, in get_build_requires
    return json.loads(result.split("\n")[-2])
  File "/opt/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/json/__init__.py", line 364, in loads
    if _pypyjson else _default_decoder.decode(s))
json.decoder.JSONDecodeError: Unexpected 'w': line 1 column 3 (char 2)
```

</details>

```
distlib-0.3.4 
filelock-3.4.2 
packaging-21.3 
platformdirs-2.4.1 
pluggy-1.0.0 
py-1.11.0 
pyparsing-3.0.7 s
ix-1.16.0 
toml-0.10.2 
tox-3.24.5 
virtualenv-20.13.0
```

**Comment by gaborbernat** [comment]
Feel free to put in a PR for this. The core maintainers are now focusing on working on tox version 4, which should have fixed this issue. Please try that and we can reopen if that's not the case.
