### ISSUE TITLE
tox4: Regression for file system dependencies

### ISSUE THREAD

**Issue by daneah** [tox-dev/tox#2366]
We have a runtime application that depends on packages from the file system that live up and over from the runtime application's directory:

```
├── package/
└── runtime-app/
    ├── requirements.txt
    └── setup.cfg
```

In tox3, running the tests in the runtime app, from the runtime app's directory, successfully installs the package via `-e ../package` defined in `requirements.txt`.

In tox4, this situation instead produces the following error:

```python
Traceback (most recent call last):
  File "/.../tox/session/cmd/run/single.py", line 45, in _evaluate
    tox_env.setup()
  File "/.../tox/tox_env/api.py", line 226, in setup
    self._setup_env()
  File "/.../tox/tox_env/python/runner.py", line 91, in _setup_env
    self._install_deps()
  File "/.../tox/tox_env/python/runner.py", line 95, in _install_deps
    self.installer.install(requirements_file, PythonRun.__name__, "deps")
  File "/.../tox/tox_env/python/pip/pip_install.py", line 84, in install
    self._install_requirement_file(arguments, section, of_type)
  File "/.../tox/tox_env/python/pip/pip_install.py", line 95, in _install_requirement_file
    raise HandledError(f"{exception} for tox env py within deps")
tox.report.HandledError: '/.../package' is not in the subpath of '/.../runtime-app' OR one path is relative and the other is absolute. for tox env py within deps
```

**Comment by ssbarnea** [comment]
That is caused by https://bugs.python.org/issue23082#msg366433 - I am writing a fix for it.
