### ISSUE TITLE
InvocationError on Windows 10

### ISSUE THREAD

**Issue by erebodino** [tox-dev/tox#2500]
I'm triying to run tox in windows 10 to test a python library, when I run it in ubuntu it's everything ok, but in windows I get the next error:

`ERROR: InvocationError for command 'E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\Scripts\pytest.EXE' -vv -m 'not live' (exited with code 1)`

before that the error appears to be a missing module `testapp`

```
Traceback (most recent call last):
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pytest_django\plugin.py", line 179, in _handle_import_error
    yield
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pytest_django\plugin.py", line 351, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\django\conf\__init__.py", line 87, in __getattr__
    self._setup(name)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\django\conf\__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\django\conf\__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Machina\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'testapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Machina\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Machina\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\Scripts\pytest.EXE\__main__.py", line 7, in <module>
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\config\__init__.py", line 187, in console_main
    code = main()
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\config\__init__.py", line 1017, in pytest_cmdline_parse
    self.parse(args)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\config\__init__.py", line 1305, in parse
    self._preparse(args, addopts=addopts)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\_pytest\config\__init__.py", line 1207, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pytest_django\plugin.py", line 350, in pytest_load_initial_conftests
    with _handle_import_error(_django_project_scan_outcome):
  File "C:\Users\Machina\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\MachinaData\Escritorio\ToxTest\django-afip\.tox\py310-django40-sqlite\lib\site-packages\pytest_django\plugin.py", line 183, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'testapp'
```

The tox.ini is:

```
[tox]
envlist =
  py{37,38,39,310}-django{32,40}-{sqlite,postgres,mysql},
  live

[testenv]
deps =
  dj-database-url
  coverage
  factory-boy
  freezegun
  pytest-django
  pytest-cov
  postgres: -e .[postgres]
  mysql: -e .[mysql]
  django32: Django>=3.2,<3.3
  django40: Django>=4.0,<4.1
commands = pytest -vv -m "not live" {posargs}
setenv =
  PYTHONPATH={toxinidir}/testapp:{toxinidir}
  sqlite: DATABASE_URL=sqlite:///:memory:
  mysql: DATABASE_URL={env:DATABASE_URL:mysql://root:mysql@127.0.0.1:3306/mysql}
  postgres: DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
passenv =
  CODECOV_TOKEN
  GENTESTCSR

[testenv:live]
deps =
  {[testenv]deps}
  -e .[postgres]
commands = pytest -vv -m "live" {posargs}
setenv =
  PYTHONPATH={toxinidir}/testapp:{toxinidir}
  DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres

[testenv:makemigrations]
deps = {[testenv]deps}
commands = django-admin makemigrations
setenv =
  PYTHONPATH={toxinidir}/testapp:{toxinidir}
  DATABASE_URL=sqlite:///:memory:
  DJANGO_SETTINGS_MODULE=testapp.settings

[testenv:fixtures]
commands = python scripts/dump_metadata.py
setenv =
  PYTHONPATH={toxinidir}/testapp:{toxinidir}
  DJANGO_SETTINGS_MODULE=testapp.settings

[testenv:mypy]
deps =
  django-stubs
  dj_database_url
commands = mypy --show-traceback --pdb django_afip

[testenv:docs]
extras=docs
commands =
  sphinx-autobuild docs/ docs/_build/html --port 9009
whitelist_externals =
  make
```

I supposed that the problem is in the tox.ini but I'm really lost here.

**Comment by jugmac00** [comment]
I neither use Windows nor Django, but this line in your tox.ini looks odd for sure

```
 PYTHONPATH={toxinidir}/testapp:{toxinidir}
```

Why is that necessary? And what do you want to achieve with setting this?

Maybe @adamchainz has some pointers for you.

**Comment by adamchainz** [comment]
I guess this is the project: https://github.com/WhyNotHugo/django-afip

Setting the `PYTHONPATH` here looks legitimate since the `testapp` folder in the root of the reop is like another Django project, and `testapp/testapp` is the module that the code is trying to import.

I suppose the problem may be due to the line using the unix path separator (`/`) instead of the windows one (`\`), and `:` instead of `;`. Change the tox file to use platform-specific variants from [globally available substitutions](https://tox.wiki/en/latest/config.html#globally-available-substitutions):

```
PYTHONPATH={toxinidir}{/}testapp{:}{toxinidir}
```

Then it should work.

**Comment by jugmac00** [comment]
Thanks a lot, @adamchainz 

@erebodino I am closing this issue. If you continue to experience problems, please report back. I'd also appreciate if you tell us whether the suggested solution has worked. Thanks.
