### ISSUE TITLE
3.27.1: cannot buid documentation with pytest 7.2.x in build env

### ISSUE THREAD

**Issue by kloczek** [tox-dev/tox#2563]
## Issue
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Looks lieke `tox` test suite is not ready for pytest 7.2.x

## Environment
Provide at least:

- OS: Linux x86/64
- `pip list` of the host python where `virtualenv` is installed:

<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
appdirs                       1.4.4
attrs                         22.1.0
Babel                         2.11.0
Brlapi                        0.8.3
build                         0.9.0
charset-normalizer            3.0.1
click                         8.1.3
click-default-group           1.2.2
cssselect                     1.1.0
distlib                       0.3.6
distro                        1.8.0
dnspython                     2.2.1
docutils                      0.19
exceptiongroup                1.0.0
execnet                       1.9.0
extras                        1.0.0
filelock                      3.8.0
fixtures                      4.0.0
flaky                         3.7.0
freezegun                     1.2.1
gpg                           1.17.1-unknown
idna                          3.4
imagesize                     1.4.1
importlib-metadata            5.1.0
incremental                   21.3.0
iniconfig                     1.1.1
Jinja2                        3.1.2
libcomps                      0.1.19
louis                         3.23.0
lxml                          4.9.1
MarkupSafe                    2.1.1
numpy                         1.23.1
packaging                     21.3
pbr                           5.9.0
pep517                        0.13.0
pip                           22.3.1
platformdirs                  2.5.2
pluggy                        1.0.0
poetry-core                   1.4.0
Pygments                      2.13.0
PyGObject                     3.42.2
pyparsing                     3.0.9
pytest                        7.2.0
pytest-freezegun              0.4.2
pytest-mock                   3.10.0
pytest-xdist                  3.0.2
python-dateutil               2.8.2
pytz                          2022.4
requests                      2.28.1
rpm                           4.17.0
scour                         0.38.2
setuptools                    65.6.3
setuptools-scm                7.0.5
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        5.3.0
sphinxcontrib-applehelp       1.0.2.dev20220730
sphinxcontrib-autoprogram     0.1.7
sphinxcontrib-devhelp         1.0.2.dev20220730
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220730
sphinxcontrib-qthelp          1.0.3.dev20220730
sphinxcontrib-serializinghtml 1.1.5
testtools                     2.5.0
toml                          0.10.2
tomli                         2.0.1
towncrier                     22.8.0
typing_extensions             4.4.0
urllib3                       1.26.12
virtualenv                    20.16.7
wheel                         0.38.4
zipp                          3.11.0
```
</details>

## Output of the virtual environment creation
N/A

Here output:
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/docs/conf.py", line 14, in <module>
    import tox
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/__init__.py", line 32, in <module>
    from .session import cmdline  # isort:skip
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/session/__init__.py", line 20, in <module>
    from tox import reporter
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 127, in <module>
    _INSTANCE = Reporter()
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 32, in __init__
    self._reset(**kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 38, in _reset
    self.tw = py.io.TerminalWriter()
AttributeError: module 'py' has no attribute 'io'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 363, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/docs/conf.py", line 14, in <module>
    import tox
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/__init__.py", line 32, in <module>
    from .session import cmdline  # isort:skip
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/session/__init__.py", line 20, in <module>
    from tox import reporter
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 127, in <module>
    _INSTANCE = Reporter()
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 32, in __init__
    self._reset(**kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 38, in _reset
    self.tw = py.io.TerminalWriter()
AttributeError: module 'py' has no attribute 'io'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/docs/conf.py", line 14, in <module>
    import tox
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/__init__.py", line 32, in <module>
    from .session import cmdline  # isort:skip
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/session/__init__.py", line 20, in <module>
    from tox import reporter
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 127, in <module>
    _INSTANCE = Reporter()
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 32, in __init__
    self._reset(**kwargs)
  File "/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/src/tox/reporter.py", line 38, in _reset
    self.tw = py.io.TerminalWriter()
AttributeError: module 'py' has no attribute 'io'
```
</details>

New pytest 7.2 procides
```console
[tkloczko@pers-jacek site-packages]$ cat /usr/lib/python3.8/site-packages/py.py
# shim for pylib going away
# if pylib is installed this file will get skipped
# (`py/__init__.py` has higher precedence)
import sys

import _pytest._py.error as error
import _pytest._py.path as path

sys.modules["py.error"] = error
sys.modules["py.path"] = path
```

**Comment by kloczek** [comment]
The same is on testing `tox` using pytest
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -p no:randomly
ImportError while loading conftest '/home/tkloczko/rpmbuild/BUILD/tox-3.27.1/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from tox._pytestplugin import *  # noqa
../../BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/tox/__init__.py:32: in <module>
    from .session import cmdline  # isort:skip
../../BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/tox/session/__init__.py:20: in <module>
    from tox import reporter
../../BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/tox/reporter.py:127: in <module>
    _INSTANCE = Reporter()
../../BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/tox/reporter.py:32: in __init__
    self._reset(**kwargs)
../../BUILDROOT/python-tox-3.27.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/tox/reporter.py:38: in _reset
    self.tw = py.io.TerminalWriter()
E   AttributeError: module 'py' has no attribute 'io'
```

**Comment by jugmac00** [comment]
pytest vendored parts the py package - this is causing your issue. Also see https://github.com/tox-dev/tox/issues/2540

There is nothing tox (version 3) can and will do currently.

tox version 4 does not longer depend on py and will be released shortly.

Meanwhile you can prevent this issue by either using a virtual env for isolation or install py, see https://github.com/tox-dev/tox/issues/2540#issuecomment-1321138045
