### ISSUE TITLE
Parallel cleanup of the tox environment doesn't work

### ISSUE THREAD

**Issue by ni-jsuchocki** [tox-dev/tox#2639]
## Issue

After entering this `except` block: https://github.com/tox-dev/tox/blob/529c2a1d8ee6acdb7ca39d20810227b5ee2d0238/src/tox/tox_env/api.py#L229-L233 because of this `raise`: https://github.com/tox-dev/tox/blob/529c2a1d8ee6acdb7ca39d20810227b5ee2d0238/src/tox/tox_env/api.py#L270, the cleanup of the tox environment fails because the files have already been deleted by another parallel tox process.

## Environment

Provide at least:

- OS: Ubuntu 20.04
- `pip list` of the host Python where `tox` is installed:

```console
Package             Version
------------------- ----------
appdirs             1.4.4
astpretty           2.1.0
attrs               22.1.0
bidict              0.21.4
bleach              5.0.0
build               0.9.0
CacheControl        0.12.11
cachetools          5.2.0
cachy               0.3.0
certifi             2022.9.24
cffi                1.15.0
chardet             5.1.0
charset-normalizer  2.1.1
cleo                0.8.1
click               8.1.3
clikit              0.6.2
colorama            0.4.6
coloredlogs         15.0.1
commonmark          0.9.1
crashtest           0.3.1
cryptography        37.0.2
dacite              1.6.0
distlib             0.3.6
docutils            0.18.1
exceptiongroup      1.0.3
filelock            3.8.2
fire                0.4.0
flake8              4.0.1
flake8-plugin-utils 1.3.2
flake8-polyfill     1.0.2
freezegun           1.2.2
gcovr               5.1
gitdb               4.0.9
GitPython           3.1.27
halo                0.0.31
html5lib            1.1
humanfriendly       10.0
idna                3.4
importlib-metadata  4.11.3
iniconfig           1.1.1
isort               5.9.3
ivy-package-manager 1.1.7
jeepney             0.8.0
Jinja2              3.1.2
jsonschema          4.4.0
keyring             21.8.0
lockfile            0.12.2
log-symbols         0.0.14
lxml                4.8.0
MarkupSafe          2.1.1
mccabe              0.6.1
msgpack             1.0.3
mypy-extensions     0.4.3
packaging           22.0
pastel              0.2.1
patool              1.12
pep517              0.12.0
pexpect             4.8.0
pip                 22.3.1
pipenv              2018.11.26
pkginfo             1.8.2
platformdirs        2.6.0
pluggy              1.0.0
poetry              1.1.12
poetry-core         1.0.8
polling             0.3.2
ptyprocess          0.7.0
punq                0.6.2
py                  1.11.0
pycodestyle         2.8.0
pycparser           2.21
pyflakes            2.4.0
Pygments            2.12.0
pyjavaproperties    0.7
pylev               1.4.0
pyparsing           3.0.9
pyproject_api       1.2.1
pyrsistent          0.18.1
pytest              7.2.0
python-dateutil     2.8.2
PyYAML              6.0
readme-renderer     35.0
requests            2.28.1
requests-toolbelt   0.9.1
rfc3986             2.0.0
rich                12.3.0
robotframework      6.0.1
ruamel.yaml         0.17.21
ruamel.yaml.clib    0.2.6
SecretStorage       3.3.2
semver              2.13.0
setuptools          65.6.3
shellingham         1.4.0
six                 1.16.0
smmap               5.0.0
spinners            0.0.24
strictyaml          1.6.1
termcolor           1.1.0
toml                0.10.2
tomli               2.0.1
tomlkit             0.11.5
tox                 4.0.0
twine               4.0.2
typing_extensions   4.0.1
urllib3             1.26.12
virtualenv          20.17.1
virtualenv-clone    0.5.7
webencodings        0.5.1
wheel               0.38.4
xattr               0.9.9
xmltodict           0.12.0
zipp                3.8.0
```

## Output of running tox

Output of `tox -p auto`:

```console
[2022-12-08T10:16:33.349Z] common_venv_setup: FAIL ✖ in 0.39 seconds

[2022-12-08T10:16:33.350Z] common_venv_setup: commands[0]> poetry install -v -n --no-root

[2022-12-08T10:16:33.350Z] common_venv_setup: failed with poetry is not allowed, use allowlist_externals to allow it

[2022-12-08T10:16:33.350Z] mypy: FAIL ✖ in 0.01 seconds

[2022-12-08T10:16:33.350Z] mypy: recreate env because env type changed from {'name': 'common_venv_setup', 'type': 'VirtualEnvRunner'} to {'name': 'mypy', 'type': 'VirtualEnvRunner'}

[2022-12-08T10:16:33.350Z] mypy: remove tox env folder /var/build/jenkins-build/864845-0/.venv

[2022-12-08T10:16:33.350Z] mypy: internal error

[2022-12-08T10:16:33.351Z] Traceback (most recent call last):

[2022-12-08T10:16:33.351Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/api.py", line 226, in setup

[2022-12-08T10:16:33.351Z]     self._setup_env()

[2022-12-08T10:16:33.351Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/python/runner.py", line 89, in _setup_env

[2022-12-08T10:16:33.351Z]     super()._setup_env()

[2022-12-08T10:16:33.351Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/python/api.py", line 161, in _setup_env

[2022-12-08T10:16:33.351Z]     super()._setup_env()

[2022-12-08T10:16:33.352Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/api.py", line 270, in _setup_env

[2022-12-08T10:16:33.352Z]     raise Recreate(f"env type changed from {old} to {conf}")

[2022-12-08T10:16:33.352Z] tox.tox_env.errors.Recreate: env type changed from {'name': 'common_venv_setup', 'type': 'VirtualEnvRunner'} to {'name': 'mypy', 'type': 'VirtualEnvRunner'}

[2022-12-08T10:16:33.352Z] 

[2022-12-08T10:16:33.352Z] During handling of the above exception, another exception occurred:

[2022-12-08T10:16:33.352Z] 

[2022-12-08T10:16:33.352Z] Traceback (most recent call last):

[2022-12-08T10:16:33.353Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/session/cmd/run/single.py", line 45, in _evaluate

[2022-12-08T10:16:33.354Z]     tox_env.setup()

[2022-12-08T10:16:33.354Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/api.py", line 231, in setup

[2022-12-08T10:16:33.354Z]     self._clean(transitive=False)

[2022-12-08T10:16:33.354Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/runner.py", line 125, in _clean

[2022-12-08T10:16:33.354Z]     super()._clean(transitive)

[2022-12-08T10:16:33.354Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/tox_env/api.py", line 293, in _clean

[2022-12-08T10:16:33.355Z]     ensure_empty_dir(env_dir, except_filename="file.lock")

[2022-12-08T10:16:33.356Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/site-packages/tox/util/path.py", line 16, in ensure_empty_dir

[2022-12-08T10:16:33.356Z]     sub_path.unlink()

[2022-12-08T10:16:33.356Z]   File "/home/developer/.pyenv/versions/3.9.11/lib/python3.9/pathlib.py", line 1354, in unlink

[2022-12-08T10:16:33.356Z]     self._accessor.unlink(self)

[2022-12-08T10:16:33.357Z] FileNotFoundError: [Errno 2] No such file or directory: '/var/build/jenkins-build/864845-0/.venv/bin'
```

## Minimal example

It should be reproducible on any parallel run of `tox` when recreating the environments is necessary.

**Comment by gaborbernat** [comment]
I'm failing to replicate this. Can you provide a replicable?

**Comment by gaborbernat** [comment]
> it seems to be a combination of setting a common `envdir`

Oh my, this behavior was never supported, at best, worked by chance than by design. You cannot share the envdir of tox environments, that's just fundamentally broken.

**Comment by ni-fgenois** [comment]
That behaviour is quite useful to reduce spin-up times of tox envs (creating venv + installing dependencies)

We usually run various tasks that do not require running in isolation; e.g. linting, type checking, merging coverage report files, etc.

Here's a full concrete example of such a file, how would you suggest we achieve similar behaviour and speeds:

```
[tox]
envlist = clean,common_venv_setup,linter,mypy,py38,py39,py310,report
isolated_build = true
requires = poetry
skipsdist = true

[testenv]
whitelist_externals = poetry
passenv = POETRY_*
commands =
    poetry install -v --no-interaction --no-root
    coverage run --parallel-mode --source=MY_SOURCES -m pytest -v tests/
depends =
    {clean,linter,mypy,report}: common_venv_setup
    {py38,py39,py310}: clean
    report: py38,py39,py310

[testenv:common_venv_setup]
envdir = {toxinidir}/.venv
commands = poetry install -v --no-interaction --no-root

[testenv:clean]
envdir = {toxinidir}/.venv
commands = coverage erase

[testenv:linter]
envdir = {toxinidir}/.venv
commands = flake8 --format=abspath

[testenv:mypy]
envdir = {toxinidir}/.venv
setenv =
    MYPYPATH = ./stubs
commands = mypy --no-incremental -p MY_SOURCES -p tests --show-traceback

[testenv:report]
envdir = {toxinidir}/.venv
parallel_show_output = true
commands =
    coverage combine
    coverage xml
    coverage report
```

**Comment by gaborbernat** [comment]
> That behaviour is quite useful to reduce spin-up times of tox envs (creating venv + installing dependencies)

Be that so, now we're joining deps from multiple environments into a single tox env, which is bound to break. E.g. what's your expectation here:

```ini
[testenv:pwd]
envdir = {toxinidir}/.venv
deps = pytest<6
commands = pwd

[testenv:ls]
envdir = {toxinidir}/.venv
deps = pytest>=6
commands = ls
```

We can't satisfy both requirement at the same time 🤦

**Comment by gaborbernat** [comment]
Somone could try to solve the problem via a plugin and if it becomes stable and widely used we can think of adopting it part of the core, but in the meantime is not supported.

**Comment by ni-fgenois** [comment]
We're usually specifying all our dependencies using `poetry` in the `pyproject.toml` file, not in `tox.ini`, so we're not encountering this problem. By using `poetry`, we maintain all our (dev) dependencies in a single place and this integrates well with other tooling (e.g. various IDEs and other task runners).

Could there be a a flag in `tox` to specify not to destroy/recreate an environment?

**Comment by gaborbernat** [comment]
Sorry, this is fundamentally against tox principles so we're not planning to support it in any shape or form.

**Comment by ni-fgenois** [comment]
That's ok, I realize that we are using tox in an unconventional way, we'll try to lessen our reliance on tox; the tool is still quite useful to test multiple python versions, thanks for maintaining it!

**Comment by gaborbernat** [comment]
You should still use tox for those tools, but you should be ok to pay the separate initialization price, it's a one time cost and following calls will not need to do this setup.

**Comment by ni-jsuchocki** [comment]
Thanks for the clarifications!
