### ISSUE TITLE
 Unidecode exception when running tox

### ISSUE THREAD

**Issue by henriquelino** [tox-dev/tox#2642]
## Issue

As the title says, when I'm running `tox` I get the following described below

## Environment

Provide at least:
I'm using tox on system-wide env, and I'm using poetry at my project, I saw that the log says about poetry but IDK if this has something to do with the error.

- OS:
Windows 10 v 21H2

- `pip list` of the host Python where `tox` is installed:
Package                   Version
------------------------- ---------
altgraph                  0.17.3
asgiref                   3.5.2
attrs                     22.1.0
cachetools                5.2.0
certifi                   2022.12.7
chardet                   5.1.0
charset-normalizer        2.1.1
click                     8.1.3
click-log                 0.4.0
colorama                  0.4.6
distlib                   0.3.6
Django                    4.1.3
django-bootstrap5         22.1
filelock                  3.8.2
h11                       0.14.0
idna                      3.4
Jinja2                    3.1.2
MarkupSafe                2.1.1
packaging                 22.0
pip                       22.3
platformdirs              2.6.0
pluggy                    1.0.0
pyinstaller-hooks-contrib 2022.13
pyparsing                 3.0.9
pyproject_api             1.2.1
pywin32-ctypes            0.2.0
PyYAML                    6.0
requests                  2.28.1
scriv                     1.0.0
setuptools                58.1.0
sqlparse                  0.4.3
tomli                     2.0.1
tox                       4.0.2
typing_extensions         4.4.0
tzdata                    2022.5
urllib3                   1.26.13
virtualenv                20.17.1
```console

```

## Output of running tox

Provide the output of `tox -rvv`:
Too big to output here, also idk if it is really relevant, if it is, I could provide

## Minimal example
>pip uninstall tox -y
>pip install tox
>tox (on any dir, with or without config file)

then I get:

```console
PS D:\git\...\project> tox
ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at D:\git\meus gits\py-json-yaml-configfile
.pkg: _optional_hooks> python C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_backend.py True poetry.core.masonry.api
.pkg: get_requires_for_build_sdist> python C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_backend.py True poetry.core.masonry.api
.pkg: prepare_metadata_for_build_wheel> python C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_backend.py True poetry.core.masonry.api
.pkg: build_sdist> python C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_backend.py True poetry.core.masonry.api
py: internal error
Traceback (most recent call last):
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\session\cmd\run\single.py", line 45, in _evaluate
    tox_env.setup()
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\api.py", line 227, in setup
    self._setup_with_env()
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\runner.py", line 149, in _setup_with_env
    self._setup_pkg()
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\runner.py", line 172, in _setup_pkg
    self._packages = self._build_packages()
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\python\runner.py", line 101, in _build_packages
    packages = package_env.perform_packaging(self.conf)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\package.py", line 47, in _func
    return meth(*args, **kwargs)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\python\virtual_env\package\pyproject.py", line 198, in perform_packaging
    sdist = self._frontend.build_sdist(sdist_directory=self.pkg_dir).sdist
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\cachetools\__init__.py", line 641, in wrapper
    v = func(*args, **kwargs)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_frontend.py", line 386, in build_sdist
    basename, out, err = self._send(
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\python\virtual_env\package\pyproject.py", line 333, in _send
    return super()._send(cmd, **kwargs)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_frontend.py", line 491, in _send
    sleep(0.001)  # wait a bit for things to happen
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\python\virtual_env\package\pyproject.py", line 353, in _send_msg
    yield ToxCmdStatus(execute_status)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\api.py", line 408, in execute_async
    self._execute_statuses.pop(execute_id)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\tox_env\api.py", line 459, in _execute_call
    yield execute_status
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\execute\api.py", line 137, in call
    err_sync.text,
  File "C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\tox\execute\stream.py", line 103, in text
    return self._content.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 11: invalid continuation byte
.pkg: _exit> python C:\Users\henri\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproject_api\_backend.py True poetry.core.masonry.api
  py: FAIL code 2 (1.42 seconds)
  evaluation failed :( (1.94 seconds)
```
## Solution?
Changing  `return self._content.decode("utf-8")` to `return self._content` solved, and I seems to have no drawback on the output, maybe a try/except on source?

  Changed this file: `tox\execute\stream.py", line 103, in text`

**Comment by henriquelino** [comment]
Sorry, this is duplicate of  #2422
