### ISSUE TITLE
Tox>=4 breaking change for scenario when install_command invokes a Python script

### ISSUE THREAD

**Issue by detmoo** [tox-dev/tox#2694]
## Issue

We have implemented the ``install_command`` for the Tox environment in the form of a Python script. According to the configuration provided in the ``tox.ini`` we expect this Python script to be invoked with arguments being "-r requirements.txt", and according to the logic implemented by the Python script, for the packages listed in ``requirements.txt`` to be installed into the resulting Tox environment. This is seen to work correctly with ``tox==3.27.1`` but it will not work with ``tox>=4.0.0``. It is not clear to me which of the breaking-changes discussed in the [FAQs](https://tox.wiki/en/latest/faq.html) is concerned in the problem we are seeing. I am requesting assistance to either identify which of the known breaking-changes I need to correct for, or alternatively to possibly raise a new bug impacting ``tox>=4.0.0``.

## Environment

- OS: we can recreate the problem in Windows and Unix environments.

- `pip list` of the host Python where `tox` is installed:

```console
Package            Version
------------------ ---------
ansible            6.1.0
ansible-core       2.13.2
asn1crypto         1.5.1
cachetools         5.2.0
certifi            2022.6.15
cffi               1.15.1
chardet            5.1.0
charset-normalizer 2.1.0
colorama           0.4.6
cryptography       37.0.4
distlib            0.3.6
filelock           3.8.2
google-auth        2.9.1
idna               3.3
ionoscloud         6.1.2
Jinja2             3.1.2
kubernetes         24.2.0
MarkupSafe         2.1.1
oauthlib           3.2.0
packaging          22.0
pip                22.3.1
platformdirs       2.6.0
pluggy             1.0.0
py                 1.11.0
pyasn1             0.4.8
pyasn1-modules     0.2.8
pycparser          2.21
pyparsing          3.0.9
pyproject_api      1.2.1
python-dateutil    2.8.2
PyYAML             6.0
requests           2.28.1
requests-oauthlib  1.3.1
resolvelib         0.8.1
rsa                4.9
setuptools         63.2.0
six                1.16.0
tomli              2.0.1
tox                4.0.8
urllib3            1.26.11
virtualenv         20.17.1
websocket-client   1.3.3
wheel              0.37.1
```

## Output of running tox

Following is the output of `tox -rvv` in the scenario where ``tox==4.0.8``. We believe the key statement in the Traceback is ``subprocess.CalledProcessError: Command '['/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python', '-m', 'pip', 'install', '-r']' returned non-zero exit status 2`` - we believe it indicates that ``tox>=4.0.8`` is failing to handle the arguments we are passing to the Python script which is invoked by the ``install_command``.

```console
(.venv) bowdataadminuser@bd-tools:~/tox4_issue_repro$ tox -rvv
test-py39: 254 I find interpreter for spec PythonSpec(major=3, minor=9) [virtualenv/discovery/builtin.py:56]
test-py39: 254 D discover exe for PythonInfo(spec=CPython3.9.13.final.0-64, exe=/home/bowdataadminuser/.venv/bin/python, platform=linux, version='3.9.13 (main, Jul 26 2022, 10:54:09) \n[GCC 11.2.0]', encoding_fs_io=utf-8-utf-8) in /usr/local [virtualenv/discovery/py_info.py:437]
test-py39: 255 D filesystem is case-sensitive [virtualenv/info.py:24]
test-py39: 256 D got python info of /usr/local/bin/python3.9 from /home/bowdataadminuser/.local/share/virtualenv/py_info/1/397704579725e15f5c7cb49fe5f0341eb7531c82d19f2c29d197e8b64ab5776b.json [virtualenv/app_data/via_disk_folder.py:129]
test-py39: 273 I proposed PythonInfo(spec=CPython3.9.13.final.0-64, system=/usr/local/bin/python3.9, exe=/home/bowdataadminuser/.venv/bin/python, platform=linux, version='3.9.13 (main, Jul 26 2022, 10:54:09) \n[GCC 11.2.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:63]
test-py39: 273 D accepted PythonInfo(spec=CPython3.9.13.final.0-64, system=/usr/local/bin/python3.9, exe=/home/bowdataadminuser/.venv/bin/python, platform=linux, version='3.9.13 (main, Jul 26 2022, 10:54:09) \n[GCC 11.2.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:65]
test-py39: 294 I create virtual environment via CPython3Posix(dest=/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:48]
test-py39: 294 D create folder /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin [virtualenv/util/path/_sync.py:9]
test-py39: 295 D create folder /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages [virtualenv/util/path/_sync.py:9]
test-py39: 295 D write /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:30]
test-py39: 295 D        home = /usr/local/bin [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        implementation = CPython [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        version_info = 3.9.13.final.0 [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        virtualenv = 20.17.1 [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        base-prefix = /usr/local [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        base-exec-prefix = /usr/local [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D        base-executable = /usr/local/bin/python3.9 [virtualenv/create/pyenv_cfg.py:34]
test-py39: 295 D symlink /usr/local/bin/python3.9 to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python [virtualenv/util/path/_sync.py:28]
test-py39: 296 D create virtualenv import hook file /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:89]
test-py39: 296 D create /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:92]
test-py39: 296 D ============================== target debug ============================== [virtualenv/run/session.py:50]
test-py39: 296 D debug via /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python /home/bowdataadminuser/.venv/lib/python3.9/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:197]
test-py39: 296 D {
  "sys": {
    "executable": "/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python",
    "_base_executable": "/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python",
    "prefix": "/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39",
    "base_prefix": "/usr/local",
    "real_prefix": null,
    "exec_prefix": "/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39",
    "base_exec_prefix": "/usr/local",
    "path": [
      "/usr/local/lib/python39.zip",
      "/usr/local/lib/python3.9",
      "/usr/local/lib/python3.9/lib-dynload",
      "/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.9.13 (main, Jul 26 2022, 10:54:09) \n[GCC 11.2.0]",
  "makefile_filename": "/usr/local/lib/python3.9/config-3.9-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/local/lib/python3.9/os.py'>",
  "site": "<module 'site' from '/usr/local/lib/python3.9/site.py'>",
  "datetime": "<module 'datetime' from '/usr/local/lib/python3.9/datetime.py'>",
  "math": "<module 'math' from '/usr/local/lib/python3.9/lib-dynload/math.cpython-39-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/usr/local/lib/python3.9/json/__init__.py'>"
} [virtualenv/run/session.py:51]
test-py39: 325 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/bowdataadminuser/.local/share/virtualenv) [virtualenv/run/session.py:55]
test-py39: 328 D got embed update of distribution setuptools from /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/embed/3/setuptools.json [virtualenv/app_data/via_disk_folder.py:129]
test-py39: 329 D got embed update of distribution pip from /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/embed/3/pip.json [virtualenv/app_data/via_disk_folder.py:129]
test-py39: 331 D got embed update of distribution wheel from /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/embed/3/wheel.json [virtualenv/app_data/via_disk_folder.py:129]
test-py39: 332 D install setuptools from wheel /home/bowdataadminuser/.venv/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/setuptools-65.6.3-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
test-py39: 332 D install wheel from wheel /home/bowdataadminuser/.venv/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/wheel-0.38.4-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
test-py39: 332 D install pip from wheel /home/bowdataadminuser/.venv/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/pip-22.3.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
test-py39: 334 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/pkg_resources to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/pkg_resources [virtualenv/util/path/_sync.py:36]
test-py39: 334 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/wheel [virtualenv/util/path/_sync.py:36]
test-py39: 335 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/pip [virtualenv/util/path/_sync.py:36]
test-py39: 346 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.dist-info to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/wheel-0.38.4.dist-info [virtualenv/util/path/_sync.py:36]
test-py39: 352 D copy /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.virtualenv to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/wheel-0.38.4.virtualenv [virtualenv/util/path/_sync.py:36]
test-py39: 355 D generated console scripts wheel3 wheel3.9 wheel wheel-3.9 [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
test-py39: 364 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/setuptools [virtualenv/util/path/_sync.py:36]
test-py39: 427 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools-65.6.3.dist-info to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/setuptools-65.6.3.dist-info [virtualenv/util/path/_sync.py:36]
test-py39: 430 D copy /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/distutils-precedence.pth to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:36]
test-py39: 431 D copy /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools-65.6.3.virtualenv to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/setuptools-65.6.3.virtualenv [virtualenv/util/path/_sync.py:36]
test-py39: 431 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/_distutils_hack to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:36]
test-py39: 433 D generated console scripts  [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
test-py39: 452 D copy /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.virtualenv to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/pip-22.3.1.virtualenv [virtualenv/util/path/_sync.py:36]
test-py39: 452 D copy directory /home/bowdataadminuser/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.dist-info to /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/lib/python3.9/site-packages/pip-22.3.1.dist-info [virtualenv/util/path/_sync.py:36]
test-py39: 453 D generated console scripts pip pip3 pip3.9 pip-3.9 [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
test-py39: 454 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:61]
test-py39: 455 D write /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:30]
test-py39: 455 D        home = /usr/local/bin [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        implementation = CPython [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        version_info = 3.9.13.final.0 [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        virtualenv = 20.17.1 [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        base-prefix = /usr/local [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        base-exec-prefix = /usr/local [virtualenv/create/pyenv_cfg.py:34]
test-py39: 455 D        base-executable = /usr/local/bin/python3.9 [virtualenv/create/pyenv_cfg.py:34]
test-py39: 459 W install_deps> python /home/bowdataadminuser/tox4_issue_repro/install.py -r requirements.txt [tox/tox_env/api.py:408]

Usage:
  /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python -m pip install [options] [-e] <vcs project url> ...
  /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python -m pip install [options] [-e] <local project path> ...
  /home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python -m pip install [options] <archive url/path> ...

-r option requires 1 argument
Requirement already satisfied: pip in ./.tox/test-py39/lib/python3.9/site-packages (22.3.1)

Traceback (most recent call last):
  File "/home/bowdataadminuser/tox4_issue_repro/install.py", line 17, in <module>
    print(subprocess.check_output([sys.executable, '-m', 'pip', 'install', pkg]).decode())
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/bowdataadminuser/tox4_issue_repro/.tox/test-py39/bin/python', '-m', 'pip', 'install', '-r']' returned non-zero exit status 2.
test-py39: 2279 C exit 1 (1.82 seconds) /home/bowdataadminuser/tox4_issue_repro> python /home/bowdataadminuser/tox4_issue_repro/install.py -r requirements.txt pid=6126 [tox/execute/api.py:275]
  test-py39: FAIL code 1 (2.03 seconds)
  evaluation failed :( (2.18 seconds)
```

## Minimal example

Following is a minimal reproducer for the issue. The script will first install ``tox==3.27.1`` and complete successfully but then will install ``tox>=4.0.0`` and will fail to complete.

A key feature of this scenario example is the specific ``install_command`` for the Tox environment: 
``install_command = python {toxinidir}/install.py {packages}``. i.e. the ``install_command`` runs a python script. 

NB// all necessary files {``tox.ini`` | ``install.py`` | ``requirements.txt``} required for the scenario are created by the script itself.

### Getting Started
1.	copy the code below into a Python file (e.g. ``run.py``) within an empty directory of your choice.
2.	change the terminal working directory to the directory where the file now exists. 
3.	run the script - e.g. ``python run.py``

```console
import subprocess
import sys

TOX3_VERSION = "tox==3.27.1"
TOX4_VERSION = "tox>=4.0.0"
REQUIREMENTS_TXT_FILE_CONTENTS = "click\n"  # this is just providing click as an arbitrary/dummy requirement for the demo
INSTALL_PY_FILE_CONTENTS = """import subprocess
import sys

from pkg_resources import parse_requirements

print(subprocess.check_output([sys.executable, '-m', 'pip', 'install', '-U', 'pip',
                              '--isolated']).decode())

for pkg in sys.argv[1:]:

    if 'requirements.txt' in pkg:
        with open('requirements.txt') as f:
            for req in parse_requirements(f.read()):
                print(subprocess.check_output([sys.executable,
                                              '-m', 'pip', 'install', str(req)]).decode())
    else:
        print(subprocess.check_output([sys.executable, '-m', 'pip', 'install', pkg]).decode())
"""
TOX_INI_FILE_CONTENTS = """[tox]
envlist = {test}-{py39}

[testenv]
skip_install=True
install_command = python {toxinidir}/install.py {packages}
deps =
    -r requirements.txt
"""


def run_tox(tox_version):
    print(f"\n..........RUNNING WITH {tox_version}............\n")
    print(subprocess.check_output([sys.executable, '-m', 'pip', 'install', tox_version]).decode())
    print(subprocess.check_output(['pip', 'list']).decode())
    print(subprocess.check_output(['tox', '-e', 'test']).decode())


def main():
    # create required files for the scenario we are recreating {tox.ini | requirements.txt | install.py}
    with open("requirements.txt", "w") as f:
        f.write(REQUIREMENTS_TXT_FILE_CONTENTS)

    with open("install.py", "w") as f:
        f.write(INSTALL_PY_FILE_CONTENTS)

    with open("tox.ini", "w") as f:
        f.write(TOX_INI_FILE_CONTENTS)


    # using Tox 3 - expect success
    run_tox(TOX3_VERSION)

    # using Tox 4 - expect failure
    run_tox(TOX4_VERSION)


if __name__ == "__main__":
    main()
```

**Comment by gaborbernat** [comment]
This is one of those things where your script worked by chance with version 3, but not by design. Please fix as described by @mgedmin.
