### ISSUE TITLE
tox 4.0.14+ : Problem parsing enviroment with space in name

### ISSUE THREAD

**Issue by Timm638** [tox-dev/tox#2762]
## Issue

Since `4.0.14`, tox has stopped to correctly parse the tox.ini. Up until `4.0.13` it worked fine. 
It seems, that enviroments with a space in their name (e. g. `py39 pypy`) are the problem.
I've added a minimal example tox.ini based on `tox quickstart`.

## Environment

Provide at least:

- OS: Windows 10
- `pip list` of my venv, where I tested this bug:

```console

(base) PS C:\Users\user\Desktop\Arbeit\Pipeline\Python\Project\test\Project> pip list
Package                       Version
----------------------------- ---------
anaconda-client               1.11.0
anaconda-navigator            2.1.2
anyio                         3.5.0
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.5
attrs                         21.4.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
beautifulsoup4                4.11.1
bleach                        4.1.0
brotlipy                      0.7.0
cachetools                    5.2.0
certifi                       2022.9.24
cffi                          1.15.1
chardet                       5.1.0
charset-normalizer            2.0.4
click                         8.0.4
clyent                        1.2.2
colorama                      0.4.6
conda                         22.9.0
conda-build                   3.22.0
conda-content-trust           0.1.3
conda-package-handling        1.9.0
conda-repo-cli                1.0.20
conda-token                   0.4.0
conda-verify                  3.4.2
cryptography                  37.0.1
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
deprecation                   2.1.0
distlib                       0.3.6
entrypoints                   0.4
executing                     0.8.3
fastjsonschema                2.16.2
filelock                      3.8.2
future                        0.18.2
glob2                         0.7
idna                          3.3
img2pdf                       0.4.4
ipykernel                     6.15.2
ipython                       8.4.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
jedi                          0.18.1
Jinja2                        2.11.3
json5                         0.9.6
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter_core                  4.11.1
jupyter-server                1.18.1
jupyterlab                    3.4.4
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.0
libarchive-c                  2.9
lxml                          4.9.1
MarkupSafe                    2.0.1
matplotlib-inline             0.1.6
menuinst                      1.4.18
mistune                       0.8.4
navigator-updater             0.2.1
nbclassic                     0.3.5
nbclient                      0.5.13
nbconvert                     6.4.4
nbformat                      5.5.0
nest-asyncio                  1.5.5
notebook                      6.4.12
packaging                     22.0
pandocfilters                 1.5.0
parso                         0.8.3
pathlib                       1.0.1
pickleshare                   0.7.5
pikepdf                       6.2.1
Pillow                        9.2.0
pip                           22.2.2
pkginfo                       1.8.2
platformdirs                  2.6.0
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.20
psutil                        5.9.0
pure-eval                     0.2.2
pycosat                       0.6.3
pycparser                     2.21
Pygments                      2.11.2
PyJWT                         2.4.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
pyproject_api                 1.2.1
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2022.1
pywin32                       302
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         23.2.0
QtPy                          2.2.0
requests                      2.28.1
ruamel-yaml-conda             0.15.100
Send2Trash                    1.8.0
setuptools                    63.4.1
sip                           6.6.2
six                           1.16.0
sniffio                       1.2.0
soupsieve                     2.3.1
stack-data                    0.2.0
terminado                     0.13.1
testpath                      0.6.0
toml                          0.10.2
tomli                         2.0.1
toolz                         0.11.2
tornado                       6.2
tox                           4.0.14
tqdm                          4.64.1
traitlets                     5.1.1
typing_extensions             4.3.0
ujson                         5.4.0
urllib3                       1.26.11
virtualenv                    20.17.1
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
wheel                         0.37.1
widgetsnbextension            3.5.2
win-inet-pton                 1.1.0
wincertstore                  0.2

```

## Output of running tox

Provide the output of `tox -rvv`:

```console

(base) PS C:\Users\user\Desktop\Arbeit\Pipeline\Python\Project\test\Project> tox -rvv
ROOT: 613 W will run in automatically provisioned tox, host C:\Users\user\anaconda3\python.exe is missing [requires (has)]: tox>=4.0.16 (4.0.14) [tox\provision.py:123]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\anaconda3\lib\site-packages\tox\run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "C:\Users\user\anaconda3\lib\site-packages\tox\run.py", line 41, in main
    result = provision(state)
  File "C:\Users\user\anaconda3\lib\site-packages\tox\provision.py", line 124, in provision
    return run_provision(provision_tox_env, state)
  File "C:\Users\user\anaconda3\lib\site-packages\tox\provision.py", line 142, in run_provision
    tox_env: PythonRun = cast(PythonRun, state.envs[name])
  File "C:\Users\user\anaconda3\lib\site-packages\tox\session\env_select.py", line 317, in __getitem__
    return self._defined_envs[item].env
  File "C:\Users\user\anaconda3\lib\site-packages\tox\session\env_select.py", line 176, in _defined_envs
    env_name_to_active = self._env_name_to_active()
  File "C:\Users\user\anaconda3\lib\site-packages\tox\session\env_select.py", line 150, in _env_name_to_active
    for a_collection, is_active in self._collect_names():
  File "C:\Users\user\anaconda3\lib\site-packages\tox\session\env_select.py", line 136, in _collect_names
    env_list, everything_active = self._state.conf.core["env_list"], False
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\sets.py", line 114, in __getitem__
    return self.load(item)
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\sets.py", line 125, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\of_type.py", line 102, in __call__
    value = loader.load(key, self.of_type, self.factory, conf, args)
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\loader\api.py", line 127, in load
    converted = self.to(prepared, of_type, factory)
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\loader\convert.py", line 46, in to
    return self.to_env_list(raw)  # type: ignore[return-value]
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\loader\str_convert.py", line 75, in to_env_list
    elements = list(chain.from_iterable(extend_factors(expr) for expr in value.split("\n")))
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\loader\ini\factor.py", line 41, in extend_factors
    for group in find_factor_groups(value):
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\loader\ini\factor.py", line 65, in find_factor_groups
    for env in expand_env_with_negation(value):
  File "C:\Users\user\anaconda3\lib\site-packages\tox\config\loader\ini\factor.py", line 80, in expand_env_with_negation
    raise ValueError(variant_str)
ValueError: py39 pypy

```

## Minimal example

Tox.ini

```tox.ini

[tox]
env_list =
    py39 pypy
minversion = 4.0.16

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
commands =
    pytest {tty:--color=yes} {posargs}


```

Console

``` console
// Tox won't run
pip install -I tox==4.0.14
tox
// Tox runs
pip install -I tox==4.0.13
tox
```

**Comment by gaborbernat** [comment]
This worked in the past but going ahead we no longer accept environments with space in their name.

**Comment by igor-susic** [comment]
@gaborbernat this was introduced with patch `4.0.13` as `4.0.12` could we add this to `CHANGELOG`  as nothing is really visible at:

**Comment by gaborbernat** [comment]
Sure, but this was never supported, to begin with; it just happened to work. PR is welcome to add it.
