### ISSUE TITLE
tox > 3.2.8 fails with tox.env not found on Ubuntu

### ISSUE THREAD

**Issue by oharboe** [tox-dev/tox#2855]
## Issue

```
$ pip3 install "tox==4.2.8"
$ tox
[deleted]
    from tox.venv import cleanup_for_venv
ModuleNotFoundError: No module named 'tox.venv'
$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tox.venv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tox.venv'
$ pip3 install "tox==3.28.0"
$ tox --version
3.28.0 imported from /usr/local/lib/python3.10/dist-packages/tox/__init__.py
registered plugins:
    tox-venv-0.4.0 at /usr/local/lib/python3.10/dist-packages/tox_venv/hooks.py
```

## Environment

Same thing under Ubuntu 20.04

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

- OS:
- `pip list` of the host Python where `tox` is installed:

```console
pip list
Package                  Version
------------------------ ---------------
apturl                   0.5.2
beautifulsoup4           4.10.0
blinker                  1.4
Brlapi                   0.8.3
cachetools               5.2.1
certifi                  2020.6.20
chardet                  5.1.0
click                    8.0.3
colorama                 0.4.6
command-not-found        0.3
cryptography             3.4.8
cupshelpers              1.0
dbus-python              1.2.18
defer                    1.0.6
distlib                  0.3.6
distro                   1.7.0
distro-info              1.1build1
dnspython                2.1.0
docutils                 0.17.1
filelock                 3.9.0
google-api-core          2.7.3
google-auth              2.6.6
google-cloud-core        2.3.0
google-cloud-datastore   2.5.1
googleapis-common-protos 1.56.0
grpcio                   1.46.0
grpcio-status            1.46.0
gyp                      0.1
html5lib                 1.1
httplib2                 0.20.2
idna                     3.3
importlib-metadata       4.6.4
jeepney                  0.7.1
keyring                  23.5.0
language-selector        0.1
launchpadlib             1.10.18
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
LinkChecker              10.0.1
louis                    3.20.0
lxml                     4.8.0
macaroonbakery           1.3.1
more-itertools           8.10.0
netifaces                0.11.0
numpy                    1.21.5
oauthlib                 3.2.0
olefile                  0.46
packaging                23.0
pbr                      5.8.1
pexpect                  4.8.0
Pillow                   9.0.1
pip                      22.3.1
platformdirs             2.6.2
pluggy                   1.0.0
proto-plus               1.20.3
protobuf                 3.20.1
psutil                   5.9.0
ptyprocess               0.7.0
py                       1.11.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycairo                  1.20.1
pycups                   2.0.1
Pygments                 2.11.2
PyGObject                3.42.1
PyJWT                    2.3.0
pymacaroons              0.13.0
PyNaCl                   1.5.0
pyparsing                2.4.7
pyproject_api            1.4.0
pyRFC3339                1.1
python-apt               2.3.0+ubuntu2.1
python-dateutil          2.8.1
python-debian            0.1.43ubuntu1
pytz                     2022.1
pyxdg                    0.27
PyYAML                   5.4.1
reportlab                3.6.8
requests                 2.25.1
requests-toolbelt        0.9.1
roman                    3.3
rsa                      4.8
scour                    0.38.2
screen-resolution-extra  0.0.0
SecretStorage            3.3.1
setuptools               65.6.3
six                      1.16.0
soupsieve                2.3.1
ssh-import-id            5.11
systemd-python           234
testresources            2.0.1
toml                     0.10.2
tomli                    2.0.1
tox                      3.28.0
tox-venv                 0.4.0
tzdata                   2022.1
ubuntu-advantage-tools   27.12
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
unattended-upgrades      0.1
urllib3                  1.26.5
usb-creator              0.3.7
vboxapi                  1.0
virtualenv               20.17.1
wadllib                  1.3.6
webencodings             0.5.1
wheel                    0.38.4
xdg                      5
xdot                     1.2
xkit                     0.0.0
yapf                     0.32.0
zipp                     1.0.0

```

## Output of running tox

Provide the output of `tox -rvv`:

```console
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/usr/local/lib/python3.10/dist-packages/tox/run.py", line 38, in main
    state = setup_state(args)
  File "/usr/local/lib/python3.10/dist-packages/tox/run.py", line 53, in setup_state
    options = get_options(*args)
  File "/usr/local/lib/python3.10/dist-packages/tox/config/cli/parse.py", line 38, in get_options
    guess_verbosity, log_handler, source = _get_base(args)
  File "/usr/local/lib/python3.10/dist-packages/tox/config/cli/parse.py", line 61, in _get_base
    MANAGER.load_plugins(source.path)
  File "/usr/local/lib/python3.10/dist-packages/tox/plugin/manager.py", line 90, in load_plugins
    self._register_plugins(inline)
  File "/usr/local/lib/python3.10/dist-packages/tox/plugin/manager.py", line 38, in _register_plugins
    self.manager.load_setuptools_entrypoints(NAME)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tox_venv/hooks.py", line 5, in <module>
    from tox.venv import cleanup_for_venv
ModuleNotFoundError: No module named 'tox.venv'

```

## Minimal example

If possible, provide a minimal reproducer for the issue:

```console

```

**Comment by gaborbernat** [comment]
`tox-venv                 0.4.0` is not compatible with tox 4.

**Comment by oharboe** [comment]
> `tox-venv 0.4.0` is not compatible with tox 4.

Shouldn't tox then express this dependency such that it is not possible to install an incompatible version?

**Comment by oharboe** [comment]
Aha!

To fix the problem uninstall tox-venv, tox-venv is deprecated.

```
pip uninstall tox-venv
```

**Comment by gaborbernat** [comment]
That's not possible. The bug is with tox-venv that claims compatibility with tox 4, which is not true.

**Comment by oharboe** [comment]
> That's not possible. The bug is with tox-venv that claims compatibility with tox 4, which is not true.

Not sure I understand what is not possible. I uninstalled tox-venv and now "tox --version" no longer gives me an exception.
