### ISSUE TITLE
testenv cannot specify `runner = X` when `X` runner type is provided by a plugin in `[tox] requires` list

### ISSUE THREAD

**Issue by masenf** [tox-dev/tox#2862]
## Issue

Please see the minimal [repro repo](https://github.com/masenf/repro-requires-runner-plugin-repro)

In short:
  * My plugin is registering a new runner type, call it "example"
  * A `tox.ini` file has a test environment that wants to set `runner = example`
  * The `tox.ini` file depends on the plugin via [`requires`](https://tox.wiki/en/latest/config.html#requires)

### Expect:

`tox` provisions a new virtualenv, `.tox`, containing the named dependencies from `requires` and then re-executes in the new environment.

### Actual:

`tox` fails with the following stack

```
ROOT: 71 D setup logging to DEBUG on pid 12802 [tox/report.py:221]
ROOT: 99 W will run in automatically provisioned tox, host /Users/masen/code/tox-dev/venv/tox-upstream/bin/python3.11 is missing [requires (has)]: tox-example-plugin [tox/provision.py:124]
Traceback (most recent call last):
  File "/Users/masen/code/tox-dev/minimal-plugin2/../venv/tox-upstream/bin/tox", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/run.py", line 41, in main
    result = provision(state)
             ^^^^^^^^^^^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/provision.py", line 125, in provision
    return run_provision(provision_tox_env, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/provision.py", line 143, in run_provision
    tox_env: PythonRun = cast(PythonRun, state.envs[name])
                                         ~~~~~~~~~~^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/session/env_select.py", line 336, in __getitem__
    return self._defined_envs[item].env
           ^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/session/env_select.py", line 192, in _defined_envs
    run_env = self._build_run_env(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/session/env_select.py", line 251, in _build_run_env
    runner = REGISTER.runner(cast(str, env_conf["runner"]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/tox-dev/venv/tox-upstream/lib/python3.11/site-packages/tox/tox_env/register.py", line 72, in runner
    return self._run_envs[name]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'example'
```

## Environment

Provide at least:

- OS: macOS ventura 13.1, homebrew python 3.11
- `pip list` of the host Python where `tox` is installed:

```console
cachetools==5.2.1
chardet==5.1.0
colorama==0.4.6
distlib==0.3.6
filelock==3.9.0
packaging==23.0
platformdirs==2.6.2
pluggy==1.0.0
pyproject_api==1.4.0
tox==4.2.8
virtualenv==20.17.1
```

## Output of running tox / minimal example

https://github.com/masenf/repro-requires-runner-plugin-repro

## Possible Fix

With the following patch, I no longer see the issue (and all existing tests pass)

```
diff --git a/src/tox/session/env_select.py b/src/tox/session/env_select.py
index f926beda..786d3d4b 100644
--- a/src/tox/session/env_select.py
+++ b/src/tox/session/env_select.py
@@ -248,6 +248,14 @@ class EnvSelector:
             env_conf.loaders.insert(0, self._provision[2])
         desc = "the tox execute used to evaluate this environment"
         env_conf.add_config(keys="runner", desc=desc, of_type=str, default=self._state.conf.options.default_runner)
+        runner_name = env_conf["runner"]
+        try:
+            runner = REGISTER.runner(cast(str, runner_name))
+        except KeyError:
+            if self._provision and self._provision[0]:
+                LOGGER.warning("provision: skip environment %s with unknown runner %r", name, runner_name)
+                return None
+            raise
         runner = REGISTER.runner(cast(str, env_conf["runner"]))
         journal = self._journal.get_env_journal(name)
         args = ToxEnvCreateArgs(env_conf, self._state.conf.core, self._state.conf.options, journal, self._log_handler)
```

Not sure if this is the "correct" fix, so @gaborbernat, I'll see if you have any comment before opening PR.

**Comment by gaborbernat** [comment]
I'd say we should not even try getting the runner if provision is on. So instead try/catch just make it if/else.

**Comment by masenf** [comment]
The other wrinkle that i discovered later is that `testenv:.tox` inherits from `testenv`, so if someone sets

```
[tox]
require = tox-example-plugin

[testenv]
runner = example
```

Even with my fix, _this_ still blows up, because provision `.tox` cannot proceed without a runner.

I'm thinking that maybe the `.tox` provision runner should _always_ be `virtualenv`?

**Comment by gaborbernat** [comment]
> 'm thinking that maybe the `.tox` provision runner should _always_ be `virtualenv`?

Yes!
