### ISSUE TITLE
tox does not work on my Windows environment due to char-code incorrespondence

### ISSUE THREAD

**Issue by kou65536** [tox-dev/tox#3073]
## Issue

tox does not work due to try to read with invalid encoding (try to read "UTF-8" but actual encoding is "sjis")

```
  py39: commands succeeded
  lint: commands succeeded
ERROR:   strictlint: undefined
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\repopath\.venv\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "C:\repopath\.venv\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "C:\repopath\.venv\lib\site-packages\tox\session\__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "C:\repopath\.venv\lib\site-packages\tox\session\__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "C:\repopath\.venv\lib\site-packages\tox\session\__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "C:\repopath\.venv\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "C:\repopath\.venv\lib\site-packages\tox\venv.py", line 649, in setupenv
    status = self.update(action=action)
  File "C:\repopath\.venv\lib\site-packages\tox\venv.py", line 282, in update
    self.hook.tox_testenv_install_deps(action=action, venv=self)
  File "C:\repopath\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\repopath\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\repopath\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\repopath\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\repopath\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\repopath\.venv\lib\site-packages\tox\venv.py", line 803, in tox_testenv_install_deps
    venv._install(deps, action=action)
  File "C:\repopath\.venv\lib\site-packages\tox\venv.py", line 495, in _install
    self.run_install_command(packages=packages, options=options, action=action)
  File "C:\repopath\.venv\lib\site-packages\tox\venv.py", line 437, in run_install_command
    self._pcall(
  File "C:\repopath\.venv\lib\site-packages\tox\venv.py", line 618, in _pcall
    return action.popen(
  File "C:\repopath\.venv\lib\site-packages\tox\action.py", line 132, in popen
    lines = out_path.read_text("UTF-8").split("\n")
  File "C:\repopath\.venv\lib\site-packages\py\_path\common.py", line 171, in read_text
    return f.read()
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 10466: invalid start byte
```

It worked correctly anyway by change char code literal in the above stacktrace
```python
lines = out_path.read_text("UTF-8").split("\n")
```

as sjis

```python
lines = out_path.read_text("sjis").split("\n")
```

Is there any way to specify the literal charcode, or any way to the files be UTF-8 (what files?)?

## Environment

Provide at least:

- OS: Windows 10

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console

```

</details>

## Output of running tox

<details open>
<summary>Output of <code>tox -rvv</code></summary>

```console

```

</details>

## Minimal example

```console

```

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by gaborbernat** [comment]
This was reported against tox 3 (the traceback shows tox 3 code paths). Tox 3 is no longer maintained. If this issue persists with tox 4, please open a new issue.
