### ISSUE TITLE
--extra-index-url in requirements.txt

### ISSUE THREAD

**Issue by SerGeRybakov** [tox-dev/tox#3083]
## Issue

I have a `requirements.txt` file with a dependency stored at https://test.pypi.org/simple/ 

```
numpy>=1.18
attrs>=23.1.0
typing-extensions>=4.4.0
tqdm>=4.64.1
psutil>=5.9.5

--extra-index-url https://test.pypi.org/simple/
deker-local-adapters==1.0.1b
```

Trying to run tox tests (tox version is 4.6.3) I'm getting the following:
```
setuptools.extern.packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier
    --extra-index-url https://test.pypi.org/simple/
```
Neither `-i` key, nor direct link to the package set in the file is accepted by tox. 
It happens on my local machine and in gitlab CI.

My tox.ini configuration is:
<details open>

```console
[tox]
requires =
    tox>=4
env_list = {py39,py310,py311}-lint, py{39,310,311}-test

[testenv:{py39,py310,py311}-test]
description = run unit tests
deps =
    setuptools>=45
    coverage==7.1.0
    deepdiff==6.3.0
    pytest>=7
    pytest-sugar
    pytest-mock==3.10.0
    xarray>=2023.5.0

commands =
    pytest {posargs:tests}

set_env =
    PIP_EXTRA_INDEX_URL = {env:PIP_EXTRA_INDEX_URL}

[testenv:{py39,py310,py311}-lint]
ignore_base_python_conflict = true
description = run linters
deps =
   setuptools>=45
   black==23.1.0
   darglint==1.8.1
   flake8==5.0.4
   flake8-bugbear==23.1.20
   flake8-docstrings==1.7.0
   flake8-import-order==0.18.2
   flake8-pytest-style==1.7.0
   isort==5.12.0
   mypy==1.0.0
   mypy-extensions==1.0.0
   pep8-naming==0.13.3
   bandit==1.7.5
   ssort==0.11.6
   deepdiff==6.3.0
   xarray>=2023.5.0

commands = isort {posargs:deker}
           black {posargs:deker}
           flake8 {posargs:deker}
           bandit -r {posargs:deker} -c pyproject.toml
           mypy {posargs:deker}  --install-types --non-interactive --config-file pyproject.toml

set_env =
    PIP_EXTRA_INDEX_URL = {env:PIP_EXTRA_INDEX_URL}
```
</details>

How that could be solved? 

## Environment

Provide at least:

- OS: Ubuntu 20.04

</details>

## Output of running tox

<details open>
<summary>Output of <code>tox -rvv</code></summary>

```console
(venv) serge@dell:~/owm/deker/deker$ tox
.pkg: _optional_hooks> python /home/serge/owm/deker/deker/venv/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/serge/owm/deker/deker/venv/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py39-lint: packaging backend failed (code=1), with InvalidRequirement: Expected package name at the start of dependency specifier
    --extra-index-url https://test.pypi.org/simple/
    ^
/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  config = read_configuration(filepath, True, ignore_option_errors, dist)
Traceback (most recent call last):
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 73, in _parse_requirement
    name_token = tokenizer.expect(
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 140, in expect
    raise self.raise_syntax_error(f"Expected {expected}")
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected package name at the start of dependency specifier
    --extra-index-url https://test.pypi.org/simple/
    ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/serge/owm/deker/deker/venv/lib/python3.9/site-packages/pyproject_api/_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
  File "/home/serge/owm/deker/deker/venv/lib/python3.9/site-packages/pyproject_api/_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 344, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 5, in <module>
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/_virtualenv.py", line 23, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/dist.py", line 898, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
    return _apply(dist, config, filepath)
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 49, in apply
    dist._finalize_requires()
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/dist.py", line 597, in _finalize_requires
    self._move_install_requirements_markers()
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/dist.py", line 637, in _move_install_requirements_markers
    inst_reqs = list(_reqs.parse(spec_inst_reqs))
  File "/home/serge/owm/deker/deker/.tox/.pkg/lib/python3.9/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
setuptools.extern.packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier
    --extra-index-url https://test.pypi.org/simple/
    ^
Backend: run command get_requires_for_build_sdist with args {'config_settings': None}
Backend: Wrote response {'code': 1, 'exc_type': 'InvalidRequirement', 'exc_msg': 'Expected package name at the start of dependency specifier\n    --extra-index-url https://test.pypi.org/simple/\n    ^'} to /tmp/pep517_get_requires_for_build_sdist-72bk78l6.json
py39-lint: FAIL ✖ in 0.28 seconds
```

</details>

**Comment by gaborbernat** [comment]
As you can see from the stacktrace this is a setuptools bug. Using another build backend like hatchling might help 🤷

**Comment by zengqingfu1442** [comment]
+1
