### ISSUE TITLE
Tox having trouble installing force includes

### ISSUE THREAD

**Issue by hguturu** [tox-dev/tox#3170]
## Issue
Currently we are using `tox` with `hatch` with a force-include.

Until recently this worked fine, but now we are getting 
```
      FileNotFoundError: Forced include not found: /private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-req-build-i2ehley9/external/stylelib
      [end of output]
```

Our relevant toml config was:
```
[tool.hatch.build.force-include]
"external/stylelib" = "src/foo/stylelib"
```

Now we can resolve this if we change the config to 
```
[tool.hatch.build.targets.sdist.force-include]
"external/stylelib" = "src/foo/stylelib"
```

But this change requires us also adding 
```
[tool.hatch.build.targets.wheel.force-include]
"external/stylelib" = "src/foo/stylelib"
```
so `pip install .` still works with the force include (otherwise pip doesn't install the force include).

The problem arises, when both `[tool.hatch.build.targets.sdist.force-include]` and `[tool.hatch.build.targets.wheel.force-include]` tox seems to be triggering the above `FileNotFoundError` error.

## Environment

Provide at least:

- OS: MacOS Sonoma 14.1.2 

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console
Package            Version
------------------ -------
cachetools         5.3.2
chardet            5.2.0
colorama           0.4.6
distlib            0.3.8
filelock           3.13.1
importlib-metadata 7.0.0
packaging          23.2
pip                23.3.1
platformdirs       4.1.0
pluggy             1.3.0
pyproject-api      1.6.1
setuptools         68.2.2
tomli              2.0.1
tox                4.11.4
typing_extensions  4.9.0
virtualenv         20.25.0
wheel              0.42.0
zipp               3.17.0
```

</details>

## Output of running tox

<details open>
<summary>Output of <code>tox -rvv</code></summary>

```console
ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /Users/hguturu/git/test_repo
py: 303 W remove tox env folder /Users/hguturu/git/test_repo/.tox/py [tox/tox_env/api.py:322]
.pkg: 638 W remove tox env folder /Users/hguturu/git/test_repo/.tox/.pkg [tox/tox_env/api.py:322]
py: 979 I find interpreter for spec PythonSpec(path=/Users/hguturu/miniforge3/envs/tox/bin/python3.12) [virtualenv/discovery/builtin.py:58]
py: 980 I proposed PythonInfo(spec=CPython3.12.0.final.0-64, exe=/Users/hguturu/miniforge3/envs/tox/bin/python3.12, platform=darwin, version='3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:65]
py: 980 D accepted PythonInfo(spec=CPython3.12.0.final.0-64, exe=/Users/hguturu/miniforge3/envs/tox/bin/python3.12, platform=darwin, version='3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:67]
py: 984 D filesystem is not case-sensitive [virtualenv/info.py:26]
py: 1044 I create virtual environment via CPython3Posix(dest=/Users/hguturu/git/test_repo/.tox/py, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:50]
py: 1045 D create folder /Users/hguturu/git/test_repo/.tox/py/bin [virtualenv/util/path/_sync.py:12]
py: 1045 D create folder /Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages [virtualenv/util/path/_sync.py:12]
py: 1046 D write /Users/hguturu/git/test_repo/.tox/py/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:32]
py: 1046 D 	home = /Users/hguturu/miniforge3/envs/tox/bin [virtualenv/create/pyenv_cfg.py:36]
py: 1046 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:36]
py: 1046 D 	version_info = 3.12.0.final.0 [virtualenv/create/pyenv_cfg.py:36]
py: 1046 D 	virtualenv = 20.25.0 [virtualenv/create/pyenv_cfg.py:36]
py: 1046 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:36]
py: 1046 D 	base-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
py: 1046 D 	base-exec-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
py: 1047 D 	base-executable = /Users/hguturu/miniforge3/envs/tox/bin/python3.12 [virtualenv/create/pyenv_cfg.py:36]
py: 1047 D symlink /Users/hguturu/miniforge3/envs/tox/bin/python3.12 to /Users/hguturu/git/test_repo/.tox/py/bin/python [virtualenv/util/path/_sync.py:32]
py: 1049 D create virtualenv import hook file /Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:91]
py: 1050 D create /Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:94]
py: 1051 D ============================== target debug ============================== [virtualenv/run/session.py:52]
py: 1051 D debug via /Users/hguturu/git/test_repo/.tox/py/bin/python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:200]
py: 1051 D {
  "sys": {
    "executable": "/Users/hguturu/git/test_repo/.tox/py/bin/python",
    "_base_executable": "/Users/hguturu/miniforge3/envs/tox/bin/python3.12",
    "prefix": "/Users/hguturu/git/test_repo/.tox/py",
    "base_prefix": "/Users/hguturu/miniforge3/envs/tox",
    "real_prefix": null,
    "exec_prefix": "/Users/hguturu/git/test_repo/.tox/py",
    "base_exec_prefix": "/Users/hguturu/miniforge3/envs/tox",
    "path": [
      "/Users/hguturu/miniforge3/envs/tox/lib/python312.zip",
      "/Users/hguturu/miniforge3/envs/tox/lib/python3.12",
      "/Users/hguturu/miniforge3/envs/tox/lib/python3.12/lib-dynload",
      "/Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]",
  "makefile_filename": "/Users/hguturu/miniforge3/envs/tox/lib/python3.12/config-3.12-darwin/Makefile",
  "os": "<module 'os' (frozen)>",
  "site": "<module 'site' (frozen)>",
  "datetime": "<module 'datetime' from '/Users/hguturu/miniforge3/envs/tox/lib/python3.12/datetime.py'>",
  "math": "<module 'math' from '/Users/hguturu/miniforge3/envs/tox/lib/python3.12/lib-dynload/math.cpython-312-darwin.so'>",
  "json": "<module 'json' from '/Users/hguturu/miniforge3/envs/tox/lib/python3.12/json/__init__.py'>"
} [virtualenv/run/session.py:53]
py: 1716 I add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/hguturu/Library/Application Support/virtualenv) [virtualenv/run/session.py:57]
py: 1718 D install pip from wheel /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/virtualenv/seed/wheels/embed/pip-23.3.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py: 1719 D copy /Users/hguturu/Library/Application Support/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-23.3.1-py3-none-any/pip-23.3.1.virtualenv to /Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/pip-23.3.1.virtualenv [virtualenv/util/path/_sync.py:40]
py: 1719 D copy directory /Users/hguturu/Library/Application Support/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-23.3.1-py3-none-any/pip-23.3.1.dist-info to /Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/pip-23.3.1.dist-info [virtualenv/util/path/_sync.py:40]
py: 1724 D copy directory /Users/hguturu/Library/Application Support/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-23.3.1-py3-none-any/pip to /Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/pip [virtualenv/util/path/_sync.py:40]
py: 2645 D generated console scripts pip-3.12 pip3.12 pip3 pip [virtualenv/seed/embed/via_app_data/pip_install/base.py:43]
py: 2646 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:63]
py: 2650 D write /Users/hguturu/git/test_repo/.tox/py/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:32]
py: 2650 D 	home = /Users/hguturu/miniforge3/envs/tox/bin [virtualenv/create/pyenv_cfg.py:36]
py: 2650 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:36]
py: 2650 D 	version_info = 3.12.0.final.0 [virtualenv/create/pyenv_cfg.py:36]
py: 2650 D 	virtualenv = 20.25.0 [virtualenv/create/pyenv_cfg.py:36]
py: 2651 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:36]
py: 2651 D 	base-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
py: 2651 D 	base-exec-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
py: 2651 D 	base-executable = /Users/hguturu/miniforge3/envs/tox/bin/python3.12 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2655 I find interpreter for spec PythonSpec(path=/Users/hguturu/miniforge3/envs/tox/bin/python3.12) [virtualenv/discovery/builtin.py:58]
.pkg: 2656 I proposed PythonInfo(spec=CPython3.12.0.final.0-64, exe=/Users/hguturu/miniforge3/envs/tox/bin/python3.12, platform=darwin, version='3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:65]
.pkg: 2656 D accepted PythonInfo(spec=CPython3.12.0.final.0-64, exe=/Users/hguturu/miniforge3/envs/tox/bin/python3.12, platform=darwin, version='3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:67]
.pkg: 2657 I create virtual environment via CPython3Posix(dest=/Users/hguturu/git/test_repo/.tox/.pkg, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:50]
.pkg: 2657 D create folder /Users/hguturu/git/test_repo/.tox/.pkg/bin [virtualenv/util/path/_sync.py:12]
.pkg: 2658 D create folder /Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages [virtualenv/util/path/_sync.py:12]
.pkg: 2658 D write /Users/hguturu/git/test_repo/.tox/.pkg/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:32]
.pkg: 2658 D 	home = /Users/hguturu/miniforge3/envs/tox/bin [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	version_info = 3.12.0.final.0 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	virtualenv = 20.25.0 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	base-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	base-exec-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2658 D 	base-executable = /Users/hguturu/miniforge3/envs/tox/bin/python3.12 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 2659 D symlink /Users/hguturu/miniforge3/envs/tox/bin/python3.12 to /Users/hguturu/git/test_repo/.tox/.pkg/bin/python [virtualenv/util/path/_sync.py:32]
.pkg: 2659 D create virtualenv import hook file /Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:91]
.pkg: 2660 D create /Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:94]
.pkg: 2660 D ============================== target debug ============================== [virtualenv/run/session.py:52]
.pkg: 2661 D debug via /Users/hguturu/git/test_repo/.tox/.pkg/bin/python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:200]
.pkg: 2661 D {
  "sys": {
    "executable": "/Users/hguturu/git/test_repo/.tox/.pkg/bin/python",
    "_base_executable": "/Users/hguturu/miniforge3/envs/tox/bin/python3.12",
    "prefix": "/Users/hguturu/git/test_repo/.tox/.pkg",
    "base_prefix": "/Users/hguturu/miniforge3/envs/tox",
    "real_prefix": null,
    "exec_prefix": "/Users/hguturu/git/test_repo/.tox/.pkg",
    "base_exec_prefix": "/Users/hguturu/miniforge3/envs/tox",
    "path": [
      "/Users/hguturu/miniforge3/envs/tox/lib/python312.zip",
      "/Users/hguturu/miniforge3/envs/tox/lib/python3.12",
      "/Users/hguturu/miniforge3/envs/tox/lib/python3.12/lib-dynload",
      "/Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:38) [Clang 15.0.7 ]",
  "makefile_filename": "/Users/hguturu/miniforge3/envs/tox/lib/python3.12/config-3.12-darwin/Makefile",
  "os": "<module 'os' (frozen)>",
  "site": "<module 'site' (frozen)>",
  "datetime": "<module 'datetime' from '/Users/hguturu/miniforge3/envs/tox/lib/python3.12/datetime.py'>",
  "math": "<module 'math' from '/Users/hguturu/miniforge3/envs/tox/lib/python3.12/lib-dynload/math.cpython-312-darwin.so'>",
  "json": "<module 'json' from '/Users/hguturu/miniforge3/envs/tox/lib/python3.12/json/__init__.py'>"
} [virtualenv/run/session.py:53]
.pkg: 2712 I add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/hguturu/Library/Application Support/virtualenv) [virtualenv/run/session.py:57]
.pkg: 2713 D install pip from wheel /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/virtualenv/seed/wheels/embed/pip-23.3.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
.pkg: 2714 D copy /Users/hguturu/Library/Application Support/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-23.3.1-py3-none-any/pip-23.3.1.virtualenv to /Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages/pip-23.3.1.virtualenv [virtualenv/util/path/_sync.py:40]
.pkg: 2715 D copy directory /Users/hguturu/Library/Application Support/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-23.3.1-py3-none-any/pip-23.3.1.dist-info to /Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages/pip-23.3.1.dist-info [virtualenv/util/path/_sync.py:40]
.pkg: 2720 D copy directory /Users/hguturu/Library/Application Support/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-23.3.1-py3-none-any/pip to /Users/hguturu/git/test_repo/.tox/.pkg/lib/python3.12/site-packages/pip [virtualenv/util/path/_sync.py:40]
.pkg: 3639 D generated console scripts pip pip3.12 pip3 pip-3.12 [virtualenv/seed/embed/via_app_data/pip_install/base.py:43]
.pkg: 3640 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:63]
.pkg: 3644 D write /Users/hguturu/git/test_repo/.tox/.pkg/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:32]
.pkg: 3644 D 	home = /Users/hguturu/miniforge3/envs/tox/bin [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	version_info = 3.12.0.final.0 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	virtualenv = 20.25.0 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	base-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	base-exec-prefix = /Users/hguturu/miniforge3/envs/tox [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3644 D 	base-executable = /Users/hguturu/miniforge3/envs/tox/bin/python3.12 [virtualenv/create/pyenv_cfg.py:36]
.pkg: 3647 W install_requires> python -I -m pip install hatch-vcs hatchling [tox/tox_env/api.py:427]
Collecting hatch-vcs
  Using cached hatch_vcs-0.4.0-py3-none-any.whl.metadata (8.6 kB)
Collecting hatchling
  Using cached hatchling-1.19.1-py3-none-any.whl.metadata (3.8 kB)
Collecting setuptools-scm>=6.4.0 (from hatch-vcs)
  Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
Collecting editables>=0.3 (from hatchling)
  Using cached editables-0.5-py3-none-any.whl.metadata (3.1 kB)
Collecting packaging>=21.3 (from hatchling)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pathspec>=0.10.1 (from hatchling)
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Collecting pluggy>=1.0.0 (from hatchling)
  Using cached pluggy-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting trove-classifiers (from hatchling)
  Using cached trove_classifiers-2023.11.29-py3-none-any.whl.metadata (2.2 kB)
Collecting setuptools (from setuptools-scm>=6.4.0->hatch-vcs)
  Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
Collecting typing-extensions (from setuptools-scm>=6.4.0->hatch-vcs)
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Using cached hatch_vcs-0.4.0-py3-none-any.whl (8.4 kB)
Using cached hatchling-1.19.1-py3-none-any.whl (76 kB)
Using cached editables-0.5-py3-none-any.whl (5.1 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
Using cached trove_classifiers-2023.11.29-py3-none-any.whl (13 kB)
Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Installing collected packages: trove-classifiers, typing-extensions, setuptools, pluggy, pathspec, packaging, editables, setuptools-scm, hatchling, hatch-vcs
Successfully installed editables-0.5 hatch-vcs-0.4.0 hatchling-1.19.1 packaging-23.2 pathspec-0.12.1 pluggy-1.3.0 setuptools-69.0.2 setuptools-scm-8.0.4 trove-classifiers-2023.11.29 typing-extensions-4.9.0
.pkg: 8183 I exit 0 (4.53 seconds) /Users/hguturu/git/test_repo> python -I -m pip install hatch-vcs hatchling pid=59952 [tox/execute/api.py:279]
.pkg: 8186 W _optional_hooks> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
Backend: run command _optional_hooks with args {}
Backend: Wrote response {'return': {'get_requires_for_build_sdist': True, 'prepare_metadata_for_build_wheel': True, 'get_requires_for_build_wheel': True, 'build_editable': True, 'get_requires_for_build_editable': True, 'prepare_metadata_for_build_editable': True}} to /var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pep517__optional_hooks-2heteuwo.json
.pkg: 8624 I exit None (0.44 seconds) /Users/hguturu/git/test_repo> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=59991 [tox/execute/api.py:279]
.pkg: 8626 W get_requires_for_build_sdist> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
Backend: run command get_requires_for_build_sdist with args {'config_settings': None}
Backend: Wrote response {'return': []} to /var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pep517_get_requires_for_build_sdist-ea1dp6gf.json
.pkg: 8727 I exit None (0.10 seconds) /Users/hguturu/git/test_repo> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=59991 [tox/execute/api.py:279]
.pkg: 8729 W build_sdist> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
Backend: run command build_sdist with args {'sdist_directory': '/Users/hguturu/git/test_repo/.tox/.pkg/dist', 'config_settings': None}
Backend: Wrote response {'return': 'foo-1.0.tar.gz'} to /var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pep517_build_sdist-kb6m9t14.json
.pkg: 8784 I exit None (0.05 seconds) /Users/hguturu/git/test_repo> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=59991 [tox/execute/api.py:279]
.pkg: 8787 D package .tmp/package/19/foo-1.0.tar.gz links to .pkg/dist/foo-1.0.tar.gz (/Users/hguturu/git/test_repo/.tox) [tox/util/file_view.py:39]
py: 8789 W install_package> python -I -m pip install --force-reinstall --no-deps /Users/hguturu/git/test_repo/.tox/.tmp/package/19/foo-1.0.tar.gz [tox/tox_env/api.py:427]
Processing ./.tox/.tmp/package/19/foo-1.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/hguturu/git/test_repo/.tox/py/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-build-env-1w9bpgtn/overlay/lib/python3.12/site-packages/hatchling/build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-build-env-1w9bpgtn/overlay/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
          artifact = version_api[version](directory, **build_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-build-env-1w9bpgtn/overlay/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 407, in build_standard
          for included_file in self.recurse_included_files():
        File "/private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-build-env-1w9bpgtn/overlay/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 177, in recurse_included_files
          yield from self.recurse_forced_files(self.config.get_force_include())
        File "/private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-build-env-1w9bpgtn/overlay/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 231, in recurse_forced_files
          raise FileNotFoundError(msg)
      FileNotFoundError: Forced include not found: /private/var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pip-req-build-2i8e8_c9/external/stylelib
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
py: 15058 C exit 1 (6.27 seconds) /Users/hguturu/git/test_repo> python -I -m pip install --force-reinstall --no-deps /Users/hguturu/git/test_repo/.tox/.tmp/package/19/foo-1.0.tar.gz pid=60000 [tox/execute/api.py:279]
.pkg: 15059 W _exit> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
Backend: run command _exit with args {}
Backend: Wrote response {'return': 0} to /var/folders/y7/j4sy0j_d5tl4j_wq512w178m0000gp/T/pep517__exit-d5gtglvf.json
.pkg: 15062 I exit None (0.00 seconds) /Users/hguturu/git/test_repo> python /Users/hguturu/miniforge3/envs/tox/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=59991 [tox/execute/api.py:279]
.pkg: 15089 D delete package /Users/hguturu/git/test_repo/.tox/.tmp/package/19/foo-1.0.tar.gz [tox/tox_env/python/virtual_env/package/pyproject.py:206]
  py: FAIL code 1 (14.79 seconds)
  evaluation failed :( (14.92 seconds)

```

</details>

## Minimal example

# pyproject.toml
```console
[project]
name = "foo"
version = "1.0"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/foo"]

[tool.hatch.build.force-include]
"external/stylelib" = "src/foo/stylelib"

#[tool.hatch.build.targets.sdist.force-include]
#"external/stylelib" = "src/foo/stylelib"

#[tool.hatch.build.targets.wheel.force-include]
#"external/stylelib" = "src/foo/stylelib"
```
If we comment out `[tool.hatch.build.force-include]` and uncomment `[tool.hatch.build.targets.sdist.force-include]` tox starts working. But, then `pip install .` no longer installs the force include until we also uncomment `[tool.hatch.build.targets.wheel.force-include]`, but then tox stops working again.

# Directory structure
```console
.
├── external
│   └── stylelib
│       └── test.tsv
├── pyproject.toml
└── src
    └── foo
        ├── __init__.py
        └── code.py
```

**Comment by hguturu** [comment]
Looks like you are right. Looks like there was a recent update to hatchling that broke things.

The temporary fix is adding an upper bound.
```
[build-system]
requires = ["hatchling<1.19", "hatch-vcs"]
build-backend = "hatchling.build"
```

Created a new issue at https://github.com/pypa/hatch/issues/1130 for others that might run into this problem.

**Comment by ofek** [comment]
https://github.com/pypa/hatch/issues/1130#issuecomment-1853296562
