### ISSUE TITLE
Confusion wrt posargs+extend

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#3400]
## Issue

Inspired by the docs, I have this in `pyproject.toml`:

```
[tool.tox.env_run_base]
description = "run test under {base_python}"
extras = ["test"]
commands = [["pytest", { replace = "posargs", default = ["-v"], extend = true }]]
```

When I run `tox`, it runs `pytest -v`. This is expected.

When I run `tox -- -k "not foo"`, it runs `pytest -k "not foo"`. The `-v` is gone. This is unexpected.

Should `extend = true` mean it runs `pytest -v -k "not foo"`?

And with `extend = false`, I get `TypeError: ['-v'] is not of type 'str'` if I pass no options, and `TypeError: ['-k', 'not foo'] is not of type 'str'` if I do. That is also not expected.

Not sure if this is a bug, two bugs, or if I misunderstood the docs.

## Environment

Provide at least:

- OS: Fedora Linux

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console
Package       Version
------------- -------
cachetools    5.5.0
chardet       5.2.0
colorama      0.4.6
distlib       0.3.8
filelock      3.16.1
packaging     24.1
platformdirs  4.3.6
pluggy        1.5.0
pyproject-api 1.8.0
tox           4.21.2
virtualenv    20.26.6
```

</details>

## Output of running tox

<details>
<summary>Output of <code>tox -rvv</code></summary>

```console
$ tox -e 3.12 -rvv
.pkg: 530 W remove tox env folder .../pyprojectize/.tox/.pkg [tox/tox_env/api.py:324]
3.12: 549 I find interpreter for spec PythonSpec(major=3, minor=12) [virtualenv/discovery/builtin.py:72]
3.12: 550 D got python info of %s from (PosixPath('/usr/bin/python3.12'), PosixPath('/home/churchyard/.local/share/virtualenv/py_info/1/f0d7a494a3f776233427cb85a7e198c7cf4913b50a203c6febc678cc4f5bf265.json')) [virtualenv/app_data/via_disk_folder.py:131]
3.12: 552 D filesystem is case-sensitive [virtualenv/info.py:25]
3.12: 552 I proposed PythonInfo(spec=CPython3.12.6.final.0-64, system=/usr/bin/python3.12, exe=.../pyprojectize/venv/bin/python3, platform=linux, version='3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:79]
3.12: 553 D accepted PythonInfo(spec=CPython3.12.6.final.0-64, system=/usr/bin/python3.12, exe=.../pyprojectize/venv/bin/python3, platform=linux, version='3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:81]
3.12: 629 I create virtual environment via CPython3Posix(dest=.../pyprojectize/.tox/3.12, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:50]
3.12: 630 D create folder .../pyprojectize/.tox/3.12/bin [virtualenv/util/path/_sync.py:12]
3.12: 631 D create folder .../pyprojectize/.tox/3.12/lib/python3.12/site-packages [virtualenv/util/path/_sync.py:12]
3.12: 631 D create folder .../pyprojectize/.tox/3.12/lib64/python3.12/site-packages [virtualenv/util/path/_sync.py:12]
3.12: 632 D write .../pyprojectize/.tox/3.12/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:33]
3.12: 632 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:38]
3.12: 632 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
3.12: 633 D 	version_info = 3.12.6.final.0 [virtualenv/create/pyenv_cfg.py:38]
3.12: 633 D 	virtualenv = 20.26.6 [virtualenv/create/pyenv_cfg.py:38]
3.12: 633 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
3.12: 633 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
3.12: 634 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
3.12: 634 D 	base-executable = /usr/bin/python3.12 [virtualenv/create/pyenv_cfg.py:38]
3.12: 635 D symlink /usr/bin/python3.12 to .../pyprojectize/.tox/3.12/bin/python [virtualenv/util/path/_sync.py:32]
3.12: 636 D create virtualenv import hook file .../pyprojectize/.tox/3.12/lib/python3.12/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:91]
3.12: 637 D create .../pyprojectize/.tox/3.12/lib/python3.12/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:94]
3.12: 637 D ============================== target debug ============================== [virtualenv/run/session.py:52]
3.12: 638 D debug via .../pyprojectize/.tox/3.12/bin/python .../pyprojectize/venv/lib64/python3.12/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:200]
3.12: 638 D {
  "sys": {
    "executable": ".../pyprojectize/.tox/3.12/bin/python",
    "_base_executable": "/usr/bin/python3.12",
    "prefix": ".../pyprojectize/.tox/3.12",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": ".../pyprojectize/.tox/3.12",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib64/python312.zip",
      "/usr/lib64/python3.12",
      "/usr/lib64/python3.12/lib-dynload",
      ".../pyprojectize/.tox/3.12/lib64/python3.12/site-packages",
      ".../pyprojectize/.tox/3.12/lib/python3.12/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]",
  "makefile_filename": "/usr/lib64/python3.12/config-3.12-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' (frozen)>",
  "site": "<module 'site' (frozen)>",
  "datetime": "<module 'datetime' from '/usr/lib64/python3.12/datetime.py'>",
  "math": "<module 'math' from '/usr/lib64/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/usr/lib64/python3.12/json/__init__.py'>"
} [virtualenv/run/session.py:53]
3.12: 732 I add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/churchyard/.local/share/virtualenv) [virtualenv/run/session.py:57]
3.12: 734 D got embed update of distribution %s from ('pip', PosixPath('/home/churchyard/.local/share/virtualenv/wheel/3.12/embed/3/pip.json')) [virtualenv/app_data/via_disk_folder.py:131]
3.12: 739 D install pip from wheel .../pyprojectize/venv/lib64/python3.12/site-packages/virtualenv/seed/wheels/embed/pip-24.2-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
3.12: 742 D copy directory /home/churchyard/.local/share/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-24.2-py3-none-any/pip to .../pyprojectize/.tox/3.12/lib/python3.12/site-packages/pip [virtualenv/util/path/_sync.py:40]
3.12: 865 D copy directory /home/churchyard/.local/share/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-24.2-py3-none-any/pip-24.2.dist-info to .../pyprojectize/.tox/3.12/lib/python3.12/site-packages/pip-24.2.dist-info [virtualenv/util/path/_sync.py:40]
3.12: 867 D copy /home/churchyard/.local/share/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-24.2-py3-none-any/pip-24.2.virtualenv to .../pyprojectize/.tox/3.12/lib/python3.12/site-packages/pip-24.2.virtualenv [virtualenv/util/path/_sync.py:40]
3.12: 870 D generated console scripts pip pip3.12 pip3 pip-3.12 [virtualenv/seed/embed/via_app_data/pip_install/base.py:43]
3.12: 871 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:63]
3.12: 884 D write .../pyprojectize/.tox/3.12/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:33]
3.12: 885 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:38]
3.12: 886 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
3.12: 886 D 	version_info = 3.12.6.final.0 [virtualenv/create/pyenv_cfg.py:38]
3.12: 886 D 	virtualenv = 20.26.6 [virtualenv/create/pyenv_cfg.py:38]
3.12: 886 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
3.12: 886 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
3.12: 886 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
3.12: 887 D 	base-executable = /usr/bin/python3.12 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 902 I find interpreter for spec PythonSpec(path=.../pyprojectize/venv/bin/python3) [virtualenv/discovery/builtin.py:72]
.pkg: 907 I proposed PythonInfo(spec=CPython3.12.6.final.0-64, system=/usr/bin/python3.12, exe=.../pyprojectize/venv/bin/python3, platform=linux, version='3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:79]
.pkg: 907 D accepted PythonInfo(spec=CPython3.12.6.final.0-64, system=/usr/bin/python3.12, exe=.../pyprojectize/venv/bin/python3, platform=linux, version='3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:81]
.pkg: 911 I create virtual environment via CPython3Posix(dest=.../pyprojectize/.tox/.pkg, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:50]
.pkg: 912 D create folder .../pyprojectize/.tox/.pkg/bin [virtualenv/util/path/_sync.py:12]
.pkg: 912 D create folder .../pyprojectize/.tox/.pkg/lib/python3.12/site-packages [virtualenv/util/path/_sync.py:12]
.pkg: 913 D create folder .../pyprojectize/.tox/.pkg/lib64/python3.12/site-packages [virtualenv/util/path/_sync.py:12]
.pkg: 913 D write .../pyprojectize/.tox/.pkg/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:33]
.pkg: 914 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:38]
.pkg: 914 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
.pkg: 914 D 	version_info = 3.12.6.final.0 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 914 D 	virtualenv = 20.26.6 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 914 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
.pkg: 914 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
.pkg: 914 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
.pkg: 915 D 	base-executable = /usr/bin/python3.12 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 915 D symlink /usr/bin/python3.12 to .../pyprojectize/.tox/.pkg/bin/python [virtualenv/util/path/_sync.py:32]
.pkg: 916 D create virtualenv import hook file .../pyprojectize/.tox/.pkg/lib/python3.12/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:91]
.pkg: 917 D create .../pyprojectize/.tox/.pkg/lib/python3.12/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:94]
.pkg: 917 D ============================== target debug ============================== [virtualenv/run/session.py:52]
.pkg: 918 D debug via .../pyprojectize/.tox/.pkg/bin/python .../pyprojectize/venv/lib64/python3.12/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:200]
.pkg: 918 D {
  "sys": {
    "executable": ".../pyprojectize/.tox/.pkg/bin/python",
    "_base_executable": "/usr/bin/python3.12",
    "prefix": ".../pyprojectize/.tox/.pkg",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": ".../pyprojectize/.tox/.pkg",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib64/python312.zip",
      "/usr/lib64/python3.12",
      "/usr/lib64/python3.12/lib-dynload",
      ".../pyprojectize/.tox/.pkg/lib64/python3.12/site-packages",
      ".../pyprojectize/.tox/.pkg/lib/python3.12/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]",
  "makefile_filename": "/usr/lib64/python3.12/config-3.12-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' (frozen)>",
  "site": "<module 'site' (frozen)>",
  "datetime": "<module 'datetime' from '/usr/lib64/python3.12/datetime.py'>",
  "math": "<module 'math' from '/usr/lib64/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/usr/lib64/python3.12/json/__init__.py'>"
} [virtualenv/run/session.py:53]
.pkg: 1019 I add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/churchyard/.local/share/virtualenv) [virtualenv/run/session.py:57]
.pkg: 1021 D got embed update of distribution %s from ('pip', PosixPath('/home/churchyard/.local/share/virtualenv/wheel/3.12/embed/3/pip.json')) [virtualenv/app_data/via_disk_folder.py:131]
.pkg: 1022 D install pip from wheel .../pyprojectize/venv/lib64/python3.12/site-packages/virtualenv/seed/wheels/embed/pip-24.2-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
.pkg: 1024 D copy directory /home/churchyard/.local/share/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-24.2-py3-none-any/pip to .../pyprojectize/.tox/.pkg/lib/python3.12/site-packages/pip [virtualenv/util/path/_sync.py:40]
.pkg: 1162 D copy directory /home/churchyard/.local/share/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-24.2-py3-none-any/pip-24.2.dist-info to .../pyprojectize/.tox/.pkg/lib/python3.12/site-packages/pip-24.2.dist-info [virtualenv/util/path/_sync.py:40]
.pkg: 1166 D copy /home/churchyard/.local/share/virtualenv/wheel/3.12/image/1/CopyPipInstall/pip-24.2-py3-none-any/pip-24.2.virtualenv to .../pyprojectize/.tox/.pkg/lib/python3.12/site-packages/pip-24.2.virtualenv [virtualenv/util/path/_sync.py:40]
.pkg: 1169 D generated console scripts pip pip3 pip3.12 pip-3.12 [virtualenv/seed/embed/via_app_data/pip_install/base.py:43]
.pkg: 1170 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:63]
.pkg: 1177 D write .../pyprojectize/.tox/.pkg/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:33]
.pkg: 1177 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1177 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1177 D 	version_info = 3.12.6.final.0 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1178 D 	virtualenv = 20.26.6 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1178 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1178 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1178 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1178 D 	base-executable = /usr/bin/python3.12 [virtualenv/create/pyenv_cfg.py:38]
.pkg: 1181 W install_requires> python -I -m pip install hatch-vcs hatchling [tox/tox_env/api.py:426]
Collecting hatch-vcs
  Using cached hatch_vcs-0.4.0-py3-none-any.whl.metadata (8.6 kB)
Collecting hatchling
  Using cached hatchling-1.25.0-py3-none-any.whl.metadata (3.8 kB)
Collecting setuptools-scm>=6.4.0 (from hatch-vcs)
  Using cached setuptools_scm-8.1.0-py3-none-any.whl.metadata (6.6 kB)
Collecting packaging>=23.2 (from hatchling)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pathspec>=0.10.1 (from hatchling)
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Collecting pluggy>=1.0.0 (from hatchling)
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting trove-classifiers (from hatchling)
  Using cached trove_classifiers-2024.9.12-py3-none-any.whl.metadata (2.2 kB)
Collecting setuptools (from setuptools-scm>=6.4.0->hatch-vcs)
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Using cached hatch_vcs-0.4.0-py3-none-any.whl (8.4 kB)
Using cached hatchling-1.25.0-py3-none-any.whl (84 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached setuptools_scm-8.1.0-py3-none-any.whl (43 kB)
Using cached trove_classifiers-2024.9.12-py3-none-any.whl (13 kB)
Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
Installing collected packages: trove-classifiers, setuptools, pluggy, pathspec, packaging, setuptools-scm, hatchling, hatch-vcs
Successfully installed hatch-vcs-0.4.0 hatchling-1.25.0 packaging-24.1 pathspec-0.12.1 pluggy-1.5.0 setuptools-75.1.0 setuptools-scm-8.1.0 trove-classifiers-2024.9.12
.pkg: 4686 I exit 0 (3.50 seconds) .../pyprojectize> python -I -m pip install hatch-vcs hatchling pid=2617749 [tox/execute/api.py:286]
.pkg: 4687 W _optional_hooks> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:426]
Backend: run command _optional_hooks with args {}
Backend: Wrote response {'return': {'get_requires_for_build_sdist': True, 'prepare_metadata_for_build_wheel': True, 'get_requires_for_build_wheel': True, 'build_editable': True, 'get_requires_for_build_editable': True, 'prepare_metadata_for_build_editable': True}} to /tmp/pep517__optional_hooks-kbn1h1nw.json
.pkg: 4720 I exit None (0.03 seconds) .../pyprojectize> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=2617807 [tox/execute/api.py:286]
.pkg: 4720 W get_requires_for_build_sdist> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:426]
Backend: run command get_requires_for_build_sdist with args {'config_settings': None}
Backend: Wrote response {'return': []} to /tmp/pep517_get_requires_for_build_sdist-80ok3q_o.json
.pkg: 4759 I exit None (0.04 seconds) .../pyprojectize> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=2617807 [tox/execute/api.py:286]
.pkg: 4759 W build_sdist> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:426]
Backend: run command build_sdist with args {'sdist_directory': '.../pyprojectize/.tox/.pkg/dist', 'config_settings': None}
Backend: Wrote response {'return': 'pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz'} to /tmp/pep517_build_sdist-0m4iac4j.json
.pkg: 4880 I exit None (0.12 seconds) .../pyprojectize> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=2617807 [tox/execute/api.py:286]
.pkg: 4881 D package .tmp/package/1/pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz links to .pkg/dist/pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz (.../pyprojectize/.tox) [tox/util/file_view.py:39]
3.12: 4881 W install_package_deps> python -I -m pip install packaging pytest specfile [tox/tox_env/api.py:426]
Collecting packaging
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pytest
  Using cached pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)
Collecting specfile
  Using cached specfile-0.32.3-py3-none-any.whl.metadata (11 kB)
Collecting iniconfig (from pytest)
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting pluggy<2,>=1.5 (from pytest)
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting rpm (from specfile)
  Using cached rpm-0.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting typing-extensions (from specfile)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pytest-8.3.3-py3-none-any.whl (342 kB)
Using cached specfile-0.32.3-py3-none-any.whl (64 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached rpm-0.2.0-py3-none-any.whl (4.4 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions, rpm, pluggy, packaging, iniconfig, specfile, pytest
Successfully installed iniconfig-2.0.0 packaging-24.1 pluggy-1.5.0 pytest-8.3.3 rpm-0.2.0 specfile-0.32.3 typing-extensions-4.12.2
3.12: 6847 I exit 0 (1.97 seconds) .../pyprojectize> python -I -m pip install packaging pytest specfile pid=2617827 [tox/execute/api.py:286]
3.12: 6848 W install_package> python -I -m pip install --force-reinstall --no-deps .../pyprojectize/.tox/.tmp/package/1/pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz [tox/tox_env/api.py:426]
Processing ./.tox/.tmp/package/1/pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyprojectize
  Building wheel for pyprojectize (pyproject.toml) ... done
  Created wheel for pyprojectize: filename=pyprojectize-1a2.dev1+gee34bd9.d20241009-py3-none-any.whl size=10499 sha256=059821fe8312504601fb3ccdd25877e207726bc0f70e105d1beb11f2431b557c
  Stored in directory: /home/churchyard/.cache/pip/wheels/a7/68/c7/aa3af2d64d929d501ababf484fd4e611f43624baeeff0b7534
Successfully built pyprojectize
Installing collected packages: pyprojectize
Successfully installed pyprojectize-1a2.dev1+gee34bd9.d20241009
3.12: 9741 I exit 0 (2.89 seconds) .../pyprojectize> python -I -m pip install --force-reinstall --no-deps .../pyprojectize/.tox/.tmp/package/1/pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz pid=2617864 [tox/execute/api.py:286]
3.12: 9742 E internal error [tox/session/cmd/run/single.py:60]
Traceback (most recent call last):
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/session/cmd/run/single.py", line 48, in _evaluate
    code, outcomes = run_commands(tox_env, no_test)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/session/cmd/run/single.py", line 85, in run_commands
    status_main = run_command_set(tox_env, "commands", chdir, ignore_errors, outcomes)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/session/cmd/run/single.py", line 104, in run_command_set
    command_set: list[Command] = tox_env.conf[key]
                                 ~~~~~~~~~~~~^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/sets.py", line 116, in __getitem__
    return self.load(item)
           ^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/sets.py", line 127, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))  # noqa: PLC2801
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/of_type.py", line 109, in __call__
    value = loader.load(key, self.of_type, self.factory, conf, args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/api.py", line 148, in load
    converted = self.build(key, of_type, factory, conf, raw, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/toml/__init__.py", line 66, in build
    return self.to(exploded, of_type, factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/convert.py", line 33, in to
    return self._to_typing(raw, of_type, factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/convert.py", line 60, in _to_typing
    result = [self.to(i, entry_type, factory) for i in self.to_list(raw, entry_type)]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/toml/__init__.py", line 82, in to_list
    return iter(validate(value, of))  # type: ignore[call-overload,no-any-return]
                ^^^^^^^^^^^^^^^^^^^
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/toml/_validate.py", line 37, in validate
    validate(va, entry_type)
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/toml/_validate.py", line 42, in validate
    validate(val, List[str])
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/toml/_validate.py", line 37, in validate
    validate(va, entry_type)
  File ".../pyprojectize/venv/lib64/python3.12/site-packages/tox/config/loader/toml/_validate.py", line 78, in validate
    raise TypeError(msg)
TypeError: ['-v'] is not of type 'str'
.pkg: 9743 W _exit> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:426]
Backend: run command _exit with args {}
Backend: Wrote response {'return': 0} to /tmp/pep517__exit-m5z5m1j7.json
.pkg: 9745 I exit None (0.00 seconds) .../pyprojectize> python .../pyprojectize/venv/lib64/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build pid=2617807 [tox/execute/api.py:286]
.pkg: 9770 D delete package .../pyprojectize/.tox/.tmp/package/1/pyprojectize-1a2.dev1+gee34bd9.d20241009.tar.gz [tox/tox_env/python/virtual_env/package/pyproject.py:224]
  3.12: FAIL code 2 (9.24 seconds)
  evaluation failed :( (9.42 seconds)
```

</details>

## Minimal example

```toml
[tool.tox]
requires = ["tox>=4.21"]
env_list = ["3.13"]

[tool.tox.env_run_base]
description = "run test under {base_python}"
extras = ["test"]
commands = [["pytest", { replace = "posargs", default = ["-v"], extend = false }]]
```

**Comment by gaborbernat** [comment]
Extend here means to extend the value in the host container, not extend the default. Does that make sense?
