### ISSUE TITLE
a directory path using forward slashes in deps fails on Windows

### ISSUE THREAD

**Issue by brechtm** [tox-dev/tox#384]
Including a directory path in a test environment's `deps` list will fail to install the dependency.

```
[testenv:regression]
deps =
    tests_regression/sphinx
```

results in a pip error:

```
Invalid requirement: 'tests_regression/sphinx'
Traceback (most recent call last):
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\packaging\requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\pyparsing.py", line 1172, in parseString
    raise exc
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\pyparsing.py", line 1162, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\pyparsing.py", line 1028, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\pyparsing.py", line 2462, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\pyparsing.py", line 1032, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\pyparsing.py", line 2265, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 16), (line:1, col:17)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\req\req_install.py", line 78, in __init__
    req = Requirement(req)
  File "c:\users\veerle\documents\opqode\rinohtype\.tox\regression\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'/sphinx'"


ERROR: could not install deps [pytest, pytest-cov, coverage, pygments, pytest-assume, tests_regression/sphinx]; v = InvocationError('C:\\Users\\Veerle\\Documents\\Opqode\\rinohtype\\.tox\\regression\\Scripts\\pip.EXE install pytest pytest-cov coverage pygments pytest-assume tests_regression/sphinx (see C:\\Users\\Veerle\\Documents\\Opqode\\rinohtype\\.tox\\regression\\log\\regression-1.log)', 1)
```

Using a backslash does work:

```
[testenv:regression]
deps =
    tests_regression\sphinx
```

It would be nice if such a test environment could be used both on UNIXes and Windows.

I'm not sure whether tox should perform translation, or whether pip should accept forward slashes also on Windows...

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell this is NOT a tox issue

**Comment by hpk42** [comment]
Why is it not a tox issue?  I think tox could try to normalize things as the goal of being able to specify paths working on both unix and windows makes sense to me.  @brechtm do you feel like doing a PR which adds xfailing tests to tests/test_config.py?

**Comment by brechtm** [comment]
I suppose it's better if pip supports forward slashes on Windows. Let's wait for the reaction of the pip developers...

**Comment by posita** [comment]
I'm not sure it's realistic to expect `pip` to solve this issue for arguments that are normally delivered via the command line in native format? Consider:

```
deps =
    -r test/requirements.txt
```

I also don't know how Tox would deal with this. Maybe:

```
deps =
    -r {nativepath:test/requrements.txt}  # what if a filename has a '}' in it?
    -r {pathjoin:"test" "requirements.txt"}  # what if a filename has a '"' in it?
```

That seems kind of clunky though.

**Comment by obestwalter** [comment]
**Update** this is was fixed on pip side (PR merged recently) but is not released yet. 🆒

**Comment by gaborbernat** [comment]
Fied as per above.
