### ISSUE TITLE
Error creating virtual environment

### ISSUE THREAD

**Issue by ewhauser** [tox-dev/tox#463]
This works fine on my local environment (OSX), but when trying to run under Docker on Jenkins I am getting an error when trying to create the venv.

Running under Docker

```
$ uname -a
Linux e7aee5b90052 4.4.41-boot2docker #1 SMP Wed Jan 11 03:05:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

```
root@3e5b70a132e2:/drone_common# cat tox.ini
[tox]
envlist = check,py27

[testenv]
setenv =
    DDENV=docker
deps =
    -r{toxinidir}/dev-requirements.txt
    -r{toxinidir}/requirements.txt
commands =
    nosetests --with-coverage --cover-package=drone_common --cover-inclusive --cover-erase --cover-html --cover-html-dir={envdir}/reports/cover {posargs}

[testenv:check]
commands =
    mkdir -p {envdir}/reports
    flake8 --exit-zero --tee --output-file={envdir}/reports/flake8 src tests setup.py
```
 
```
root@3e5b70a132e2:/drone_common# pip freeze
GDAL==1.10.1
Pillow==2.3.0
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
decorator==3.4.0
drone-setuptools==0.0.1
html5lib==0.999
matplotlib==1.3.1
numpy==1.8.2
pluggy==0.4.0
py==1.4.32
pyparsing==2.0.1
python-dateutil==1.5
pytz==2012c
requests==2.2.1
scipy==0.13.3
six==1.5.2
tox==2.6.0
urllib3==1.7.1
virtualenv==15.1.0
wheel==0.24.0
wsgiref==0.1.2
```

```
root@3e5b70a132e2:/drone_common# tox -e py27
GLOB sdist-make: /drone_common/setup.py
py27 create: /drone_common/.tox/py27
py27 installdeps: -r/drone_common/dev-requirements.txt, -r/drone_common/requirements.txt
ERROR: invocation failed (exit code 1), logfile: /drone_common/.tox/py27/log/py27-1.log
ERROR: actionid: py27
msg: getenv
cmdargs: ['/drone_common/.tox/py27/bin/pip', 'install', '-r/drone_common/dev-requirements.txt', '-r/drone_common/requirements.txt']
env: {'TERM': 'xterm', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'PYPI_UPLOAD_URL': 'dronedeploy.jfrog.io/dronedeploy/api/pypi/pypi-local', 'PIP_CONF_DIR': '/root/.pip/', 'HOSTNAME': '3e5b70a132e2', 'PYPI_URL': 'dronedeploy.jfrog.io/dronedeploy/api/pypi/pypi/simple', 'VIRTUAL_ENV': '/drone_common/.tox/py27', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'SHLVL': '1', 'PWD': '/drone_common', 'PYTHONHASHSEED': '2265182949', 'PATH': '/drone_common/.tox/py27/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'DDENV': 'docker', 'HOME': '/root', 'GIT_HASH': '', '_': '/usr/local/bin/tox'}

Exception:
Traceback (most recent call last):
  File "/drone_common/.tox/py27/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/drone_common/.tox/py27/local/lib/python2.7/site-packages/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/drone_common/.tox/py27/local/lib/python2.7/site-packages/pip/basecommand.py", line 69, in _build_session
    if options.cache_dir else None
  File "/drone_common/.tox/py27/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'int' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/drone_common/.tox/py27/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/drone_common/.tox/py27/local/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/drone_common/.tox/py27/local/lib/python2.7/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/drone_common/.tox/py27/local/lib/python2.7/site-packages/pip/basecommand.py", line 69, in _build_session
    if options.cache_dir else None
  File "/drone_common/.tox/py27/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'int' object has no attribute 'endswith'

ERROR: could not install deps [-r/drone_common/dev-requirements.txt, -r/drone_common/requirements.txt]; v = InvocationError('/drone_common/.tox/py27/bin/pip install -r/drone_common/dev-requirements.txt -r/drone_common/requirements.txt (see /drone_common/.tox/py27/log/py27-1.log)', 1)
__________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   py27: could not install deps [-r/drone_common/dev-requirements.txt, -r/drone_common/requirements.txt]; v = InvocationError('/drone_common/.tox/py27/bin/pip install -r/drone_common/dev-requirements.txt -r/drone_common/requirements.txt (see /drone_common/.tox/py27/log/py27-1.log)', 1)
```

**Comment by obestwalter** [comment]
Huh ... thanks. Sounds like a tricky one, if it only happens in Docker on Jenkins. No idea how an int can end up in a path. 

If you have any further info or get the chance to debug it yourself: please let us know.

**Comment by ewhauser** [comment]
I tracked this down when trying to do a min reproduction of the issue. My Docker configuration was set to disable the pip cache which was causing the problem. Specifically, I had the lines:

```
   && (echo "no-cache-dir = true" >> ${PIP_CONF_DIR}/pip.conf) \
   && (echo "cache-dir = none" >> ${PIP_CONF_DIR}/pip.conf)
```

Removing those lines solved the problem. Sorry for the false alarm.
