### ISSUE TITLE
2.8.0rc1 does not install with easy_install on CentOS 6, python 2.6 and python-setuptools-0.6.10-3.el6.noarch.rpm

### ISSUE THREAD

**Issue by alexntt** [tox-dev/tox#576]
```
$ docker run --rm -it centos:6 bash
# yum install -y python-setuptools
[...]
Installed:
  python-setuptools.noarch 0:0.6.10-3.el6
[...]
# easy_install tox
Searching for tox
Reading http://pypi.python.org/simple/tox/
Best match: tox 2.8.0rc1
Downloading https://pypi.python.org/packages/1c/12/0d7436f19b9f85b7c6186f25002a2160f2d342fdc0811aff2d0ed214f4be/tox-2.8.0rc1.tar.gz#md5=8370a662519562959082014b3790d389
Processing tox-2.8.0rc1.tar.gz
Running tox-2.8.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-R16H4t/tox-2.8.0rc1/egg-dist-tmp-ILCLr6
Checking .pth file support in .
/usr/bin/python -E -c pass
Searching for setuptools-scm
Reading http://pypi.python.org/simple/setuptools_scm/
Best match: setuptools-scm 1.15.6
Downloading https://pypi.python.org/packages/16/4e/c023700958861d2ab52a985e1a15c42809fec9c3b80aae3812ff88efaf2c/setuptools_scm-1.15.6-py2.6.egg#md5=83d7365ed86a7847e8d838a56562419d
Processing setuptools_scm-1.15.6-py2.6.egg
creating /tmp/easy_install-R16H4t/tox-2.8.0rc1/setuptools_scm-1.15.6-py2.6.egg
Extracting setuptools_scm-1.15.6-py2.6.egg to /tmp/easy_install-R16H4t/tox-2.8.0rc1

Installed /tmp/easy_install-R16H4t/tox-2.8.0rc1/setuptools_scm-1.15.6-py2.6.egg
your setuptools is too old (<12)
setuptools_scm functionality is degraded
zip_safe flag not set; analyzing archive contents...
tox.interpreters: module MAY be using inspect.getsource
tox.config: module references __file__
tox.session: module references __file__
tox._pytestplugin: module references __file__
Adding tox 2.8.0rc1 to easy-install.pth file
Installing tox script to /usr/bin
Installing tox-quickstart script to /usr/bin

Installed /usr/lib/python2.6/site-packages/tox-2.8.0rc1-py2.6.egg
Processing dependencies for tox
Searching for virtualenv>=1.11.2
Reading http://pypi.python.org/simple/virtualenv/
Best match: virtualenv 15.1.0
Downloading https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz#md5=44e19f4134906fe2d75124427dc9b716
Processing virtualenv-15.1.0.tar.gz
Running virtualenv-15.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6IuZw5/virtualenv-15.1.0/egg-dist-tmp-gjHLGf
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1715, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1696, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1719, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 504, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 545, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 538, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 780, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 792, in obtain
    return installer(requirement)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 123, in <module>
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    self.run_command("egg_info")
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 179, in run
    self.find_sources()
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 254, in find_sources
    mm.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 308, in run
    self.add_defaults()
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 335, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/usr/lib/python2.6/site-packages/setuptools/command/sdist.py", line 46, in walk_revctrl
    for item in ep.load()(dirname):
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named setuptools_scm.integration
```

but it does work if I `easy_install pip` and then install using pip.

**Comment by RonnyPfannschmidt** [comment]
this looks like the nested setuptools sandbox usage is breaking its neck as it tries to load a setuptools plugin that had been disable prior

since your setuptools version is very old and findanmentally broken in many ways (yay enterprise versioning)
its hard to solve

please avoid easy_install - its in the process of being deprecated since years now

also note, that your python version is EOL since a few years now

**Comment by alexntt** [comment]
Yeah, no worries- we have switched to using pip, I was just reporting this in case it bore some utility. A WONTFIX close is fine :)

**Comment by RonnyPfannschmidt** [comment]
closing as wontfix due to prehistoric software in enterprise distros

**Comment by obestwalter** [comment]
Hi @alexntt thanks for reporting anyway. 

About easy_install: we removed all references to easy_install from the docs with this release. So we don't support tox installation through easy_install at all anymore (https://github.com/tox-dev/tox/issues/276).

If problems like this only affect systems using really outdated tooling this is o.k. for me. Those users can just stay on tox 2.7 until they are ready to update the rest of their tooling.
