### ISSUE TITLE
Tox tests are failed due to broken PYTHONPATH env var

### ISSUE THREAD

**Issue by stanislavlevin** [tox-dev/tox#653]
Command with passing of environment variable doesn't pass it

`export PYTHONPATH=/usr/src/tmp/python-module-tox-buildroot/usr/lib/python2.7/site-packages;export PATH=$PATH:/usr/src/tmp/python-module-tox-buildroot/usr/bin;python setup.py pytest --addopt "--cov-config=tox.ini --cov=tox --timeout=180"`

tox.ini:

```
[pytest]
addopts = --verbose
rsyncdirs = tests tox
looponfailroots = tox tests
norecursedirs = .hg .tox
xfail_strict = True
passenv = PYTHONPATH
```

Log:
```
running pytest
running egg_info
writing requirements to tox.egg-info/requires.txt
writing tox.egg-info/PKG-INFO
writing top-level names to tox.egg-info/top_level.txt
writing dependency_links to tox.egg-info/dependency_links.txt
writing entry points to tox.egg-info/entry_points.txt
reading manifest file 'tox.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tox.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux2 -- Python 2.7.11, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: .cache
tox comes from: '/usr/src/RPM/BUILD/python-module-tox-2.9.1/tox/__init__.pyc'
rootdir: /usr/src/RPM/BUILD/python-module-tox-2.9.1, inifile: tox.ini
plugins: xdist-1.11, timeout-1.2.0, cov-2.4.0
timeout: 180.0s method: signal
collecting ... collected 50 items

tests/test_z_cmdline.py::test_report_protocol PASSED
tests/test_z_cmdline.py::test__resolve_pkg PASSED
tests/test_z_cmdline.py::test__resolve_pkg_doubledash PASSED
tests/test_z_cmdline.py::TestSession::test_make_sdist PASSED
tests/test_z_cmdline.py::TestSession::test_make_sdist_distshare PASSED
tests/test_z_cmdline.py::TestSession::test_summary_status PASSED
tests/test_z_cmdline.py::test_minversion FAILED
tests/test_z_cmdline.py::test_notoxini_help_still_works FAILED
tests/test_z_cmdline.py::test_notoxini_help_ini_still_works FAILED
tests/test_z_cmdline.py::test_envdir_equals_toxini_errors_out FAILED
tests/test_z_cmdline.py::test_run_custom_install_command_error FAILED
tests/test_z_cmdline.py::test_unknown_interpreter_and_env FAILED
tests/test_z_cmdline.py::test_unknown_interpreter FAILED
tests/test_z_cmdline.py::test_skip_platform_mismatch FAILED
tests/test_z_cmdline.py::test_skip_unknown_interpreter FAILED
tests/test_z_cmdline.py::test_unknown_dep FAILED
tests/test_z_cmdline.py::test_venv_special_chars_issue252 FAILED
tests/test_z_cmdline.py::test_unknown_environment FAILED
tests/test_z_cmdline.py::test_skip_sdist FAILED
tests/test_z_cmdline.py::test_minimal_setup_py_empty FAILED
tests/test_z_cmdline.py::test_minimal_setup_py_comment_only FAILED
tests/test_z_cmdline.py::test_minimal_setup_py_non_functional FAILED
tests/test_z_cmdline.py::test_sdist_fails FAILED
tests/test_z_cmdline.py::test_package_install_fails FAILED
tests/test_z_cmdline.py::TestToxRun::test_toxuone_env FAILED
tests/test_z_cmdline.py::TestToxRun::test_different_config_cwd FAILED
tests/test_z_cmdline.py::TestToxRun::test_json FAILED
tests/test_z_cmdline.py::test_develop FAILED
tests/test_z_cmdline.py::test_usedevelop FAILED
```

And so on.

Error messages like:

```
initproj = <function initproj at 0x7fc614752398>
cmd = <tox._pytestplugin.Cmd instance at 0x7fc61485c8c0>

    def test_develop(initproj, cmd):
        initproj("example123", filedefs={'tox.ini': """
        """})
        result = cmd.run("tox", "-vv", "--develop")
>       assert not result.ret
E       assert not 1
E        +  where 1 = <tox._pytestplugin.RunResult instance at 0x7fc61485c368>.ret

/usr/src/RPM/BUILD/python-module-tox-2.9.1/tests/test_z_cmdline.py:548: AssertionError
----------------------------------------- Captured stdout call ------------------------------------------
created project in /usr/src/tmp/pytest-of-builder/pytest-45/test_develop0/example123
/usr/src/tmp/pytest-of-builder/pytest-45/test_develop0/example123$ tox -vv --develop
----------------------------------------- Captured stderr call ------------------------------------------
Traceback (most recent call last):
  File "/usr/src/tmp/python-module-tox-buildroot/usr/bin/tox", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tox==2.9.1' distribution was not found and is required by the application

```

There is a problem with passing env var(in my case PYTHONPATH).

**Comment by The-Compiler** [comment]
`passenv` is a tox and not a pytest setting, so it'll need to be in a `[testenv]` section.

**Comment by stanislavlevin** [comment]
Ok, i've passed PYTHONPATH by TOX_TESTENV_PASSENV:
TOX_TESTENV_PASSENV='PYTHONPATH' python setup.py pytest --addopt "--verbose --cov-config=tox.ini --cov=tox --timeout=180"

There is a new issue:
```
tests/test_venv.py::TestCreationConfig::test_basic PASSED
tests/test_venv.py::TestCreationConfig::test_matchingdependencies PASSED
tests/test_venv.py::TestCreationConfig::test_matchingdependencies_file PASSED
tests/test_venv.py::TestCreationConfig::test_matchingdependencies_latest PASSED
tests/test_venv.py::TestCreationConfig::test_python_recreation PASSED
tests/test_venv.py::TestCreationConfig::test_dep_recreation PASSED
tests/test_venv.py::TestCreationConfig::test_develop_recreation PASSED
tests/test_venv.py::TestVenvTest::test_envbinddir_path PASSED
tests/test_venv.py::TestVenvTest::test_pythonpath_usage FAILED
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

self = <test_venv.TestVenvTest instance at 0x7fa484340b90>
newmocksession = <function newmocksession at 0x7fa483f00230>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch instance at 0x7fa484340758>

    def test_pythonpath_usage(self, newmocksession, monkeypatch):
        monkeypatch.setenv("PYTHONPATH", "/my/awesome/library")
        mocksession = newmocksession([], """
                [testenv:python]
                commands=abc
            """)
        venv = mocksession.getenv("python")
        action = mocksession.newaction(venv, "getenv")
        venv.run_install_command(['qwe'], action=action)
>       assert 'PYTHONPATH' not in os.environ
E       AssertionError: assert 'PYTHONPATH' not in {'LESS': '-MM', 'LESSOPEN': '|/usr/share/less/lesspipe.sh %s', 'LOGNAME': 'builder', 'USER': 'builder', 'HOME': '/usr/...a=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}
E        +  where {'LESS': '-MM', 'LESSOPEN': '|/usr/share/less/lesspipe.sh %s', 'LOGNAME': 'builder', 'USER': 'builder', 'HOME': '/usr/...a=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'} = os.environ

/usr/src/RPM/BUILD/python-module-tox-2.9.1/tests/test_venv.py:576: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /usr/src/RPM/BUILD/python-module-tox-2.9.1/tests/test_venv.py(576)test_pythonpath_usage()
-> assert 'PYTHONPATH' not in os.environ
(Pdb) 'PYTHONPATH' not in os.environ
False
(Pdb) os.environ['PYTHONPATH']
'/my/awesome/library'
```

So, how to properly pass PYTHONPATH to ALL tox self tests?
Thank you.

**Comment by obestwalter** [comment]
Hi @stanislavlevin, can you explain what you are trying to accomplish? ``python setup.py pytest`` does not work at all in my setup and I don't understand why you want to run the tests like that. I also do not understand why passing PYTHONPATH is necessary in your setup. If you would explain what problem you are trying to solve, we might be able to help.

**Comment by obestwalter** [comment]
Hi @stanislavlevin whatever it is, it does not occur anymore on current master builds. I did not like into the details, but if you can still reproduce the problem, please open a new issue and detail the circumstances under which they happen.
