### ISSUE TITLE
Change 'envdir' default

### ISSUE THREAD

**Issue by rpkilby** [tox-dev/tox#696]
## Problem

Some testenv names may unintentionally conflict with other directories created in the `toxworkdir`. For example, I recently wanted to add a specific build for testing the distribution, naturally naming it `dist`. My tox.ini looked something like:

```ini
[tox]
envlist = py27,py34,py35,py36,dist

[testenv]
commands = coverage run setup.py test
usedevelop = True

[testenv:dist]
commands = python setup.py test
usedevelop = False
```

Running `tox -e dist` generating the following error, which was a little confusing:

```python
Traceback (most recent call last):
  File "./.venv/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "./.venv/lib/python3.6/site-packages/tox/session.py", line 40, in main
    retcode = Session(config).runcommand()
  File "./.venv/lib/python3.6/site-packages/tox/session.py", line 392, in runcommand
    return self.subcommand_test()
  File "./.venv/lib/python3.6/site-packages/tox/session.py", line 567, in subcommand_test
    self.installpkg(venv, path)
  File "./.venv/lib/python3.6/site-packages/tox/session.py", line 503, in installpkg
    self.resultlog.set_header(installpkg=py.path.local(path))
  File "./.venv/lib/python3.6/site-packages/tox/result.py", line 25, in set_header
    md5=installpkg.computehash("md5"),
  File "./.venv/lib/python3.6/site-packages/py/_path/local.py", line 232, in computehash
    f = self.open('rb')
  File "./.venv/lib/python3.6/site-packages/py/_path/local.py", line 361, in open
    return py.error.checked_call(open, self.strpath, mode)
  File "./.venv/lib/python3.6/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: open('./.tox/dist/package-0.0.1.zip', 'rb')
```

The issue was that the sdist was being built in the `dist` directory, which conflicted with the `dist` testenv.

## Proposed changes
- Change the default `envdir` to something like `{toxworkdir}/venvs/{envname}`. idk if this would be considered backwards incompatible. 
- Raise a more infromative exception that complains about known bad testenv names, suggesting that they either change the name or set `envdir` to `{toxworkdir}/venvs/{envname}`.

This isn't exactly a high priority issue or anything. The immediate fix is to just change the `envdir`, as demonstrated above.

**Comment by gaborbernat** [comment]
Fair point, I don't think this would be backward incompatible upfront as the workdir is kinda private; could prove breaking with users scripts. I would probably prefer having the other way around, e.g. having a ``.tmp`` folder in the workdir where we build the dist, and wheels and so on.

**Comment by asottile** [comment]
fwiw, the longer we make the paths for envdirs the more likely we'll run into shebang length limits on posix platforms

**Comment by obestwalter** [comment]
I am -1 on changing this for the same reason that @asottile mentioned. The 80 char limit is there to stay for a long time, so we better make sure we don't add to the length of the path mor than we already do.

To prevent the above error and make it clearer to users we could add a check that makes sure that no envname is chosen that is "reserved" by tox. This is `dist` and `logs` so far and I don't think that list will grow much in the future.

**Comment by rpkilby** [comment]
Just as a note, tox should probably check conflicting paths instead of conflicting names. eg, if a user sets `envdir` to `{toxworkdir}/venvs/{envname}`, a `dist` env would no longer conflict with `{toxworkdir}/dist`.

**Comment by altendky** [comment]
I haven't dug much so this may be a silly idea.  Instead of `.tox/{dist,log}` have those in `.tox-meta` or such and leave `.tox` for purely envs?

But yes, at least an error message on anything using those non-env directories.

**Comment by gaborbernat** [comment]
I would say that we'll keep things as they are for backward compatibility. However, we'll warn if you try to define an environment with the reserved name.

**Comment by rpkilby** [comment]
This seems to be fixed in tox 4. `dist` testenvs work without having to specify a custom `envdir`, and it internal directories are named like `.pkg` and `.tmp`, which seem to be invalid testenv names that avoid the naming conflict. e.g., `[testenv:.pkg]`

```
$ tox -e .pkg
ROOT: HandledError| cannot run packaging environment(s) .pkg
```

**Comment by altendky** [comment]
that strikes me as more of just a quieter error as opposed to useful feedback to the user as to why things won't work and what they need to do to make their env work.
