### ISSUE TITLE
test_alwayscopy fails on openSUSE

### ISSUE THREAD

**Issue by ederag** [tox-dev/tox#752]
On openSUSE 42.2 (python2.7 or python3.4), `test_alwayscopy` fails.
This seems due to a `virtualenv` issue (https://github.com/pypa/virtualenv/issues/565).
So this is more a report for anybody searching for this error + "tox".

Here is the log:
```
tox -e py34    
GLOB sdist-make: /home/ederag/share/prog/python/tox/setup.py
py34 inst-nodeps: /home/ederag/share/prog/python/tox/.tox/dist/tox-2.9.1.zip
py34 installed: apipkg==1.4,attrs==17.4.0,coverage==4.4.2,execnet==1.5.0,pluggy==0.6.0,py==1.5.2,pytest==3.3.2,pytest-cov==2.5.1,pytest-forked==0.2,pytest-timeout==1.2.1,pytest-xdist==1.22.0,six==1.11.0,tox==2.9.1,virtualenv==15.1.0
py34 runtests: PYTHONHASHSEED='1275035432'
py34 runtests: commands[0] | pytest tests --cov-config=/home/ederag/share/prog/python/tox/tox.ini --cov=/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/tox --timeout=180
========================================================= test session starts ==========================================================
platform linux -- Python 3.4.6, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
tox comes from: '/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/tox/__init__.py'
rootdir: /home/ederag/share/prog/python/tox, inifile: tox.ini
plugins: xdist-1.22.0, timeout-1.2.1, forked-0.2, cov-2.5.1
timeout: 180.0s method: signal
collected 303 items                                                                                                                    

tests/test_config.py ........................................................................................................... [ 35%]
.................................................................x............s                                                  [ 61%] 
tests/test_interpreters.py s......                                                                                               [ 63%]
tests/test_quickstart.py ................                                                                                        [ 68%]
tests/test_result.py ....                                                                                                        [ 70%]
tests/test_venv.py ...................s..................                                                                        [ 82%]
tests/test_z_cmdline.py ..................................F.................                                                     [100%]

----------- coverage: platform linux, python 3.4.6-final-0 -----------
Name                                                         Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------------------------------
.tox/py34/lib/python3.4/site-packages/tox/__init__.py           30      2      0      0    93%
.tox/py34/lib/python3.4/site-packages/tox/__main__.py            1      1      0      0     0%
.tox/py34/lib/python3.4/site-packages/tox/_pytestplugin.py     249     16     67     11    91%
.tox/py34/lib/python3.4/site-packages/tox/_quickstart.py       143     25     51      8    80%
.tox/py34/lib/python3.4/site-packages/tox/_verlib.py            95     32     44      8    61%
.tox/py34/lib/python3.4/site-packages/tox/config.py            785     20    292     21    96%
.tox/py34/lib/python3.4/site-packages/tox/hookspecs.py          12      0      0      0   100%
.tox/py34/lib/python3.4/site-packages/tox/interpreters.py      128     49     28      3    55%
.tox/py34/lib/python3.4/site-packages/tox/result.py             52      0      2      0   100%
.tox/py34/lib/python3.4/site-packages/tox/session.py           548     33    192     15    92%
.tox/py34/lib/python3.4/site-packages/tox/venv.py              321     14    118     10    94%
----------------------------------------------------------------------------------------------
TOTAL                                                         2364    192    794     76    90%

======================================================= short test summary info ========================================================
SKIP [1] tests/test_config.py:2348: condition: sys.platform != 'win32'
SKIP [1] /home/ederag/share/prog/python/tox/tests/test_venv.py:390: needs python3.3
SKIP [1] tests/test_interpreters.py:21: condition: sys.platform != 'win32'
XFAIL tests/test_config.py::TestCmdInvocation::()::test_colon_symbol_in_directory_name
  Upstream bug. See #203

=============================================================== FAILURES ===============================================================
___________________________________________________________ test_alwayscopy ____________________________________________________________

initproj = <function initproj.<locals>.initproj at 0x7ff41311a0d0>, cmd = <tox._pytestplugin.Cmd object at 0x7ff4130c0358>

    @pytest.mark.skipif(_alwayscopy_not_supported(), reason="Platform doesnt support alwayscopy")
    def test_alwayscopy(initproj, cmd):
        initproj("example123", filedefs={'tox.ini': """
                [testenv]
                commands={envpython} --version
                alwayscopy=True
        """})
        result = cmd.run("tox", "-vv")
>       assert not result.ret
E       assert not 1
E        +  where 1 = <tox._pytestplugin.RunResult object at 0x7ff4130c0780>.ret

/home/ederag/share/prog/python/tox/tests/test_z_cmdline.py:662: AssertionError
--------------------------------------------------------- Captured stdout call ---------------------------------------------------------
created project in /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123
/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123$ tox -vv
using tox.ini: /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/tox.ini
using tox-2.9.1 from /home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/tox/__init__.py
GLOB start: packaging 
GLOB sdist-make: /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/setup.py
  /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123$ /home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/setup.py sdist --formats=zip --dist-dir /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/dist >/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/log/tox-0.log
GLOB finish: packaging after 0.22 seconds
copying new sdistfile to '/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/distshare/example123-0.1.zip'
python start: getenv /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python
python create: /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python
setting PATH=/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/bin:/home/ederag/share/prog/python/tox/.tox/py34/bin:/home/ederag/share/bin:/home/ederag/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0/jre/bin
  /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox$ /home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 -m virtualenv --always-copy --python /home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 python >/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/log/python-0.log
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/log/python-0.log
ERROR: actionid: python
msg: getenv
cmdargs: ['/home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4', '-m', 'virtualenv', '--always-copy', '--python', '/home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4', 'python']

Already using interpreter /home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4
Using real prefix '/usr'
Cannot find file lib (bad symlink)
New python executable in /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/bin/python3.4
Also creating executable in /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /tmp/pytest-of-edera...python/bin/python3.4 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/lib64/python3.4/tempfile.py", line 34, in <module>
    import shutil as _shutil
  File "/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/lib64/python3.4/shutil.py", line 14, in <module>
    import tarfile
  File "/tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/lib64/python3.4/tarfile.py", line 47, in <module>
    import time
ImportError: No module named 'time'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/pytest-of-edera...python/bin/python3.4 - setuptools pip wheel failed with error code 1

ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 -m virtualenv --always-copy --python /home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 python (see /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/log/python-0.log)', 1)
python finish: getenv after 0.41 seconds
___________________________________ summary ____________________________________
ERROR:   python: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 -m virtualenv --always-copy --python /home/ederag/share/prog/python/tox/.tox/py34/bin/python3.4 python (see /tmp/pytest-of-ederag/pytest-51/test_alwayscopy0/example123/.tox/python/log/python-0.log)', 1)
===================================== 1 failed, 298 passed, 3 skipped, 1 xfailed in 108.83 seconds =====================================
ERROR: InvocationError: '/home/ederag/share/prog/python/tox/.tox/py34/bin/pytest tests --cov-config=/home/ederag/share/prog/python/tox/tox.ini --cov=/home/ederag/share/prog/python/tox/.tox/py34/lib/python3.4/site-packages/tox --timeout=180'
_______________________________________________________________ summary ________________________________________________________________
ERROR:   py34: commands failed

```

**Comment by obestwalter** [comment]
Fixed in 3.0, just forgot to close - thanks @ederag!
