### ISSUE TITLE
tox configuration to show test result details

### ISSUE THREAD

**Issue by MikeG451** [tox-dev/tox#770]
We have multiple repo's and tox shows the results differently.

Sometimes I'll get just summary results like:
```
test_get_all_success (abc.tests.tests_lcp_controller.TestLcpController) ... ok
test_get_one_get_zones_error (abc.tests.tests_lcp_controller.TestLcpController) ... ok
test_get_one_not_found (abc.tests.tests_lcp_controller.TestLcpController) ... ok
```

or, it shows how long each test runs with no other details for each test:
```
Test id                                                                                                    Runtime (s)
-------------------------------------------------------------------------  -----------
xyz.tests.unit.client.test_getrec.GetRecTestCase.test_fail_pull_template      1.054
```

What I want is to see the output from each test:
```
2018-02-23 09:23:08,845 [INFO    ] [abc_rest.controllers.v1.openstack.flavors.os_extra_specs][MainThread] OsExtraSpecsController - extra specs updated
2018-02-23 09:23:08,846 [ERROR   ] [abc_rest.controllers.v1.openstack.flavors.os_extra_specs][MainThread] OsExtraSpecsController - Failed to update extra specs Exception:
Traceback (most recent call last):
  File "/home/stack/test/openstack-abc/abc_rest/controllers/v1/openstack/flavors/os_extra_specs.py", line 157, in put
    request.headers, flavor_id)
  File "/home/stack/test/openstack-abc/.tox/cover/local/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/stack/test/openstack-abc/.tox/cover/local/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
SystemError
ok
```

This way I can see if a test is designed to fail that it fails for the right reason.

I've compared the tox.ini between each repo and haven't found where I can manage that.  I've checked the documentation, but it seems to be focused on basic configuration options.  I may not be using the correct verbiage in my searches though.

Any suggestions?

**Comment by Pawamoy** [comment]
I don't think this is tox responsibility to show the tests results in a way or another but more the test suite runner you are using, such as pytest, nose, mamba, etc.

**Comment by MikeG451** [comment]
Thanks.  I wasn't aware of that.

**Comment by The-Compiler** [comment]
Indeed - tox only invokes your testrunner, similar to how e.g. `make` would. You'll need to configure the test runner accordingly.
